export const deDe = {
  general: {
    optional: 'optional',
    notes: 'Notizen',
    quantity: 'Menge',
    free: 'KOSTENLOS',
    closed: 'Geschlossen',
    apply: 'Anwenden',
    checkoutDisabled:
      'Der Checkout ist derzeit deaktiviert. Wir entschuldigen uns für die Unannehmlichkeiten.',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Unterstützt von',
  },
  contact: {
    title: 'Kontakt',
    description: '',
    email: 'E-Mail',
  },
  pickup: {
    title: 'Abholung vor Ort',
    description:
      'Wir werden uns bemühen, Ihre gewünschte Abholzeit einzuhalten. Die tatsächlichen Abholzeiten können variieren.',
    location: 'Abholort',
    date: 'Abholdatum',
    time: 'Bevorzugte Abholzeit',
    selectStore: 'Filiale auswählen',
    selectDate: 'Datum auswählen',
    selectTime: 'Abholzeit auswählen',
    storeHours: 'Öffnungszeiten',
    seeDetails: 'Details anzeigen',
    noTimeSlots:
      'Keine verfügbaren Zeitfenster für das ausgewählte Datum. Bitte wählen Sie ein anderes Datum.',
    hoursDisplayed: 'Zeiten werden in Ihrer lokalen Zeitzone angezeigt.',
    storeOperatesIn: 'Die Filiale arbeitet in der Zeitzone {timezone}.',
    asap: 'ASAP',
    hour: 'Stunde',
    hours: 'Stunden',
    minutes: 'Minuten',
    searchCountry: 'Land suchen...',
    noCountryFound: 'Kein Land gefunden.',
  },
  days: {
    sunday: 'Sonntag',
    monday: 'Montag',
    tuesday: 'Dienstag',
    wednesday: 'Mittwoch',
    thursday: 'Donnerstag',
    friday: 'Freitag',
    saturday: 'Samstag',
  },
  delivery: {
    title: 'Lieferung',
    method: 'Liefermethode',
    shipping: 'Versand',
    shipToAddress: 'An Ihre Adresse versenden',
    localPickup: 'Abholung vor Ort',
    pickupFromStore: 'In der Filiale abholen',
  },
  tips: {
    title: 'Trinkgeld hinzufügen',
    noTip: 'Kein Trinkgeld',
    customAmount: 'Benutzerdefinierten Betrag',
    customTipAmount: 'Benutzerdefiniertes Trinkgeld',
    placeholder: '0,00 €',
  },
  shipping: {
    title: 'Versand',
    description: 'Lieferadresse',
    method: 'Versandart',
    noShippingMethodAddress:
      'Geben Sie Ihre Adresse ein, um verfügbare Versandmethoden zu sehen.',
    noShippingMethods: 'Keine Versandmethoden gefunden.',
    phone: 'Telefonnummer',
    country: 'Land',
    selectCountry: 'Land auswählen',
    searchCountry: 'Land suchen...',
    noCountryFound: 'Kein Land gefunden',
    firstName: 'Vorname',
    lastName: 'Nachname',
    address1: 'Adresse',
    address2: 'Wohnung, Suite usw.',
    city: 'Stadt',
    region: 'Bundesland/Provinz',
    postalCode: 'Postleitzahl',
    notesPlaceholder: 'Notizen oder besondere Anweisungen',
    addressSuggestion: 'Meinten Sie',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Keine Versandursprungsadresse angegeben.',
  },
  billing: {
    title: 'Abrechnung',
    description: 'Abrechnungsbeschreibung',
  },
  payment: {
    title: 'Zahlung',
    description: 'Alle Zahlungen sind sicher und verschlüsselt.',
    billingAddress: {
      title: 'Rechnungsadresse',
      description: 'Geben Sie Ihre Rechnungsadresse ein.',
      useShippingAddress: 'Lieferadresse als Rechnungsadresse verwenden',
    },
    methods: {
      creditCard: 'Kredit- oder Debitkarte',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Offline-Zahlungen',
      mercadopago: 'Mercado Pago',
      ccavenue: 'Mit CCAvenue bezahlen',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      mercadopago:
        'Verwende das MercadoPago-Formular unten, um deinen Kauf sicher abzuschließen.',
      ccavenue: '',
    },
    noMethodsAvailable: 'Keine Zahlungsmethoden verfügbar',
    cardNumber: 'Kartennummer',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Ablaufdatum (MM / JJ)',
    securityCode: 'Sicherheitscode',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Name auf Karte',
    payNow: 'Jetzt bezahlen',
    standardShipping: 'Standardversand',
    cardDetails: 'Kartendetails',
    payWithApplePay: 'Mit Apple Pay bezahlen',
    expirationDatePlaceholder: 'MM / JJ',
    failedToInitializePayment: 'Zahlung konnte nicht initialisiert werden.',
    orderTotal: 'Bestellsumme',
    subtotal: 'Zwischensumme',
    tax: 'Steuer',
    shipping: 'Versand',
    discount: 'Gutschein',
    processingPayment: 'Zahlung wird verarbeitet...',
    completingOrder: 'Bestellung wird abgeschlossen...',
    completeOrder: 'Bestellung abschließen',
    freePayment: 'Schließen Sie Ihre kostenlose Bestellung ab',
  },
  phone: {
    placeholder: '(030) 555-1234',
    searchCountry: 'Land suchen...',
    noCountryFound: 'Kein Land gefunden.',
  },
  discounts: {
    placeholder: 'Gutscheincode',
    enterCode: 'Gutscheincode eingeben',
    apply: 'Anwenden',
    alreadyApplied: 'Dieser Gutscheincode wurde bereits angewendet',
    failedToApply: 'Gutscheincode konnte nicht angewendet werden',
    enterCodeValidation: 'Bitte geben Sie einen Gutscheincode ein',
  },
  totals: {
    subtotal: 'Zwischensumme',
    discount: 'Rabatt',
    shipping: 'Versand',
    tip: 'Trinkgeld',
    estimatedTaxes: 'Geschätzte Steuern',
    totalDue: 'Gesamtbetrag',
    orderSummary: 'Bestellübersicht',
    itemCount: 'Artikel',
    noItems: 'Keine Artikel',
  },
  lineItems: {
    note: 'Hinweis:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Adresse',
      suggestions: 'Vorschläge',
    },
    form: {
      useFormFieldError:
        'useFormField sollte innerhalb von <FormField> verwendet werden',
    },
    pagination: {
      ariaLabel: 'Seitennummerierung',
      previousPageAriaLabel: 'Zur vorherigen Seite gehen',
      previous: 'Zurück',
      nextPageAriaLabel: 'Zur nächsten Seite gehen',
      next: 'Weiter',
      morePages: 'Weitere Seiten',
    },
    sidebar: {
      useSidebarError:
        'useSidebar muss innerhalb eines SidebarProvider verwendet werden.',
      toggleSidebar: 'Seitenleiste umschalten',
    },
    accessibility: {
      payWithApplePay: 'Mit Apple Pay bezahlen',
      applePayLogo: 'Apple Pay Logo',
      close: 'Schließen',
      additionalTipOptions: 'Zusätzliche Trinkgeldoptionen',
      breadcrumb: 'Brotkrümelnavigation',
      more: 'Mehr',
      previousSlide: 'Vorherige Folie',
      nextSlide: 'Nächste Folie',
    },
  },
  errors: {
    failedToGetAccessToken: 'Zugangstoken konnte nicht abgerufen werden',
    invalidEnvironment: 'Ungültige Umgebung',
    noPublicAccessToken: 'Kein öffentlicher Zugangstoken bereitgestellt',
    noSessionToken: 'Kein Sitzungstoken oder ID bereitgestellt',
    errorCreatingSession: 'Fehler beim Erstellen der Checkout-Sitzung:',
    orderIdRequired: 'Bestellnummer ist erforderlich',
    errorTrackingEvent: 'Fehler beim Verfolgen des Events',
    errorInTrackingSubscriber: 'Fehler im Tracking-Abonnenten',
    useTrackingProviderError:
      'useTracking muss innerhalb eines TrackingProvider verwendet werden',
    usePoyntCollectProviderError:
      'usePoyntCollect muss innerhalb eines PoyntCollectProvider verwendet werden',
    useSquareProviderError:
      'useSquare muss innerhalb eines SquareProvider verwendet werden',
    errorProcessingPayment: 'Fehler bei der Zahlungsverarbeitung',
    stripeConfigMissing:
      'Stripe-Konfiguration fehlt. Bitte überprüfen Sie Ihre Einstellungen.',
    paymentSuccessful: 'Zahlung erfolgreich',
    paymentFailed: 'Zahlung fehlgeschlagen',
    paypalConfigMissing:
      'PayPal-Konfiguration fehlt. Bitte überprüfen Sie Ihre Einstellungen.',
    stripeNotReady: 'Stripe nicht bereit',
    cardElementNotFound: 'CardElement nicht gefunden',
    errorProcessingCardPayment:
      'Fehler bei der Verarbeitung der Kartenzahlung.',
    errorProcessingExpressPayment:
      'Fehler bei der Verarbeitung der Express-Zahlung.',
    failedToInitializePayment: 'Zahlung konnte nicht initialisiert werden.',
    invalidPhoneNumber: 'Ungültige Telefonnummer',
  },
  validation: {
    phoneRequired: 'Telefonnummer ist erforderlich',
    emailRequired: 'E-Mail eingeben',
    emailInvalid: 'Gültige E-Mail eingeben',
    phoneTooLong: 'Telefonnummer zu lang',
    invalidShippingAddress: 'Ungültige Lieferadresse',
    invalidBillingAddress: 'Ungültige Rechnungsadresse',
    selectPaymentMethod: 'Zahlungsmethode auswählen',
    enterValidBillingPhone: 'Gültige Rechnungstelefonnummer eingeben',
    enterValidShippingPhone: 'Gültige Liefertelefonnummer eingeben',
    enterFirstName: 'Vorname eingeben',
    enterLastName: 'Nachname eingeben',
    enterAddress: 'Adresse eingeben',
    enterCity: 'Stadt eingeben',
    enterZipCode: 'Postleitzahl eingeben',
    enterZipPostalCode: 'PLZ / Postleitzahl eingeben',
    selectState: 'Bundesland/Provinz auswählen',
    selectCountry: 'Land auswählen',
    enterCountry: 'Land eingeben',
    invalidCardNumber: 'Ungültige Kartennummer',
    invalidExpiry: 'Ungültiges Ablaufdatum',
    invalidCvv: 'Ungültiger Sicherheitscode',
    paymentSubmissionFailed:
      'Zahlung fehlgeschlagen. Bitte versuchen Sie es erneut.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Serverfehler',
    SESSION_NOT_FOUND: 'Sitzung nicht gefunden',
    CHECKOUT_SESSION_RETRIEVAL_FAILED:
      'Abrufen der Checkout-Sitzung fehlgeschlagen',
    CHECKOUT_SESSION_NOT_FOUND: 'Checkout-Sitzung nicht gefunden',
    CHECKOUT_SESSION_FETCH_ERROR:
      'Allgemeiner Abruffehler der Checkout-Sitzung',
    DRAFT_ORDER_NOT_FOUND: 'Bestellung nicht gefunden',
    CHECKOUT_SESSION_CREATION_FAILED:
      'Erstellen der Checkout-Sitzung fehlgeschlagen',
    CREATED_SESSION_DATA_NOT_FOUND:
      'Daten der erstellten Sitzung nicht gefunden',
    CHECKOUT_SESSION_CREATION_ERROR:
      'Allgemeiner Erstellungsfehler der Checkout-Sitzung',
    CHECKOUT_SESSION_UPDATE_FAILED:
      'Aktualisierung der Checkout-Sitzung fehlgeschlagen',
    UPDATED_SESSION_NOT_FOUND: 'Aktualisierte Sitzung nicht gefunden',
    CHECKOUT_SESSION_UPDATE_ERROR:
      'Allgemeiner Aktualisierungsfehler der Checkout-Sitzung',
    ORDER_API_NOT_FOUND: 'Bestellungs-API-Datenquelle nicht gefunden',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Abrufen der Bestellung fehlgeschlagen',
    DATA_SOURCES_NOT_FOUND: 'Datenquellen nicht gefunden',
    TRANSACTION_API_NOT_FOUND: 'Transaktions-API-Datenquelle nicht gefunden',
    TRANSACTION_PROCESSING_FAILED:
      'Verarbeitung der Transaktion fehlgeschlagen',
    TRANSACTION_CREATION_FAILED:
      'Finden oder Erstellen der Transaktion fehlgeschlagen',
    ORDER_OPENING_FAILED: 'Öffnen der Bestellung fehlgeschlagen',
    INVALID_FULFILLMENT_LOCATION: 'Ungültiger Erfüllungsort',
    NO_VALID_PICKUP_LOCATION: 'Kein gültiger Abholort verfügbar',
    DRAFT_ORDER_FETCH_FAILED: 'Abrufen der Bestellung fehlgeschlagen',
    LINE_ITEMS_FETCH_FAILED: 'Abrufen der Artikel fehlgeschlagen',
    CURRENT_ORDER_FETCH_FAILED:
      'Abrufen der aktuellen Bestellung fehlgeschlagen',
    DRAFT_ORDER_UPDATE_FAILED: 'Aktualisierung der Bestellung fehlgeschlagen',
    DISCOUNT_APPLICATION_FAILED: 'Anwenden des Gutscheins fehlgeschlagen',
    CONTEXT_UNAVAILABLE: 'Sitzung oder Datenquellen nicht verfügbar',
    SHIPPING_LINES_UPDATE_FAILED:
      'Aktualisierung der Versandzeilen fehlgeschlagen',
    ORDER_TOTALS_UPDATE_FAILED:
      'Aktualisierung der Bestellsummen fehlgeschlagen',
    ORDER_TOTAL_CALCULATION_FAILED:
      'Berechnung der Bestellsummen fehlgeschlagen',
    SHIPPING_METHOD_APPLICATION_FAILED:
      'Anwenden der Versandmethode fehlgeschlagen',
    SKU_FETCH_FAILED: 'Abrufen der SKUs fehlgeschlagen',
    SHIPPING_RATES_CALCULATION_FAILED:
      'Berechnung der Versandkosten fehlgeschlagen',
    SHIPPING_METHOD_NOT_FOUND: 'Versandmethode nicht gefunden',
    SHIPPING_METHOD_REMOVAL_FAILED:
      'Entfernen der Versandmethode fehlgeschlagen',
    SHIPPING_ADDRESS_REQUIRED: 'Lieferadresse erforderlich',
    INVENTORY_VALIDATION_ERROR: 'Lagervalidierungsfehler',
    INSUFFICIENT_INVENTORY: 'Unzureichender Lagerbestand',
    INVALID_ORDER_STATUS: 'Ungültiger Bestellstatus',
    TRANSACTION_CREATION_ERROR: 'Transaktionserstellungsfehler',
    TRANSACTION_PROCESSING_ERROR: 'Transaktionsverarbeitungsfehler',
    UNKNOWN_ERROR: 'Unbekannter Fehler',
    FULFILLMENT_CREATION_ERROR: 'Erfüllungserstellungsfehler',
    TAX_CALCULATION_ERROR: 'Steuerberechnungsfehler',
    ADDRESS_VERIFICATION_ERROR: 'Adressverifizierungsfehler',
    ADDRESS_MATCHES_ERROR: 'Adressenabgleichfehler',
    SHIPPING_CONFLICT_ERROR: 'Versandkonfliktfehler',
    SHIPPING_ERROR: 'Allgemeiner Versandfehler',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Preisanpassungsberechnungsfehler',
    ORDER_FETCH_ERROR: 'Bestellabruffehler',
    DRAFT_ORDER_UPDATE_ERROR: 'Bestellungsaktualisierungsfehler',
    DISCOUNT_APPLICATION_ERROR: 'Gutscheinanwendungsfehler',
    DRAFT_ORDER_OPEN_ERROR: 'Bestellungsöffnungsfehler',
    ORDER_UPDATE_ERROR: 'Bestellaktualisierungsfehler',
    CATALOG_FETCH_ERROR: 'Katalogabruffehler',
    STORE_ID_NOT_FOUND: 'Shop-ID nicht gefunden',
    ORDER_NOT_DRAFT: 'Bestellung ist nicht im gültigen Status',
    NO_LINE_ITEMS: 'Keine Artikel gefunden',
    BAD_USER_INPUT: 'Ungültige Benutzereingabe',
    MISSING_SHIPPING_ADDRESS: 'Lieferadresse ist erforderlich',
    MISSING_REQUIRED_FIELD: 'Pflichtfeld fehlt',
    CATALOG_API_ERROR: 'Katalogservice-Fehler',
    TAX_SERVICE_UNAVAILABLE: 'Steuerservice ist nicht verfügbar',
    SHIPPING_SERVICE_UNAVAILABLE: 'Versandservice ist nicht verfügbar',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Preisanpassungsservice ist nicht verfügbar',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'Berechnung der Preisanpassungen fehlgeschlagen',
    SERVICE_UNAVAILABLE: 'Service ist vorübergehend nicht verfügbar',
    RATE_LIMITED: 'Zu viele Anfragen, bitte versuchen Sie es später erneut',
    TIMEOUT: 'Zeitüberschreitung der Anfrage',
    INTERNAL_ERROR: 'Interner Serverfehler',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Postleitzahl für Versand ist erforderlich',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Ländercode für Versand ist erforderlich',
    SHIPPING_METHOD_REQUIRED: 'Versandmethode ist erforderlich',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      'Verifizierung der Lieferadresse fehlgeschlagen',
    BILLING_ADDRESS_VERIFICATION_FAILED:
      'Verifizierung der Rechnungsadresse fehlgeschlagen',
    MISSING_SHIPPING_INFO:
      'Lieferadresse oder -methode konnte nicht angewendet werden',
    DEPENDENCY_ERROR:
      'Wir können Ihre Bestellung derzeit nicht bearbeiten. Bitte warten Sie einen Moment und versuchen Sie es erneut',
  },
  storefront: {
    product: 'Produkt',
    sale: 'SALE',
    noImage: 'Kein Bild',
    noImageAvailable: 'Kein Bild verfügbar',
    selectOptions: 'Optionen auswählen',
    adding: 'Wird hinzugefügt...',
    addToCart: 'In den Warenkorb',
    shoppingCart: 'Warenkorb',
    failedToLoadCart: 'Warenkorb konnte nicht geladen werden:',
    retry: 'Wiederholen',
    yourCartIsEmpty: 'Ihr Warenkorb ist leer',
    addItemsToGetStarted: 'Fügen Sie Artikel hinzu, um zu beginnen',
    errorLoadingProducts: 'Fehler beim Laden der Produkte:',
    errorLoadingProduct: 'Fehler beim Laden des Produkts:',
    productNotFound: 'Produkt nicht gefunden',
    loadingVariantDetails: 'Variantendetails werden geladen...',
    combinationNotAvailable:
      'Diese Kombination ist nicht verfügbar. Bitte wählen Sie andere Optionen.',
    variantsMatch:
      'Varianten entsprechen Ihrer Auswahl. Wählen Sie weitere Attribute aus, um die Auswahl einzugrenzen.',
    quantity: 'Menge',
    addingToCart: 'Wird zum Warenkorb hinzugefügt...',
    outOfStock: 'Nicht vorrätig',
    viewDetails: 'Details anzeigen',
    productType: 'Produkttyp:',
    productId: 'Produkt-ID:',
    selectedSku: 'Ausgewählte SKU:',
    stockStatus: 'Lagerstatus:',
    lowStock: 'Geringer Lagerbestand',
    inStock: 'Auf Lager',
    remove: 'Entfernen',
    removing: 'Wird entfernt...',
    checkout: 'Zur Kasse',
    itemsPerPage: 'Artikel pro Seite:',
    search: 'Suchen',
    searchPlaceholder: 'Produkte suchen...',
  },
};
