export const enIe = {
  general: {
    optional: 'optional',
    notes: 'Notes',
    quantity: 'Quantity',
    free: 'FREE',
    closed: 'Closed',
    apply: 'Apply',
    checkoutDisabled:
      'Checkout is currently disabled. We apologise for the inconvenience.',
  },
  contact: {
    title: 'Contact',
    description: '',
    email: 'Email',
  },
  pickup: {
    title: 'Local Pickup',
    description:
      'All efforts will be made to meet your expected pickup time. Actual pickup times may vary.',
    location: 'Pickup Location',
    date: 'Pickup Date',
    time: 'Preferred Pickup Time',
    selectStore: 'Select a store location',
    selectDate: 'Select a date',
    selectTime: 'Select a pickup time',
    storeHours: 'Store Hours',
    seeDetails: 'See details',
    noTimeSlots:
      'No available time slots for the selected date. Please select another date.',
    hoursDisplayed: 'Hours displayed in your local timezone.',
    storeOperatesIn: 'Store operates in {timezone} timezone.',
    asap: 'ASAP',
    hour: 'hour',
    hours: 'hours',
    minutes: 'minutes',
    searchCountry: 'Search country...',
    noCountryFound: 'No country found.',
  },
  days: {
    sunday: 'Sunday',
    monday: 'Monday',
    tuesday: 'Tuesday',
    wednesday: 'Wednesday',
    thursday: 'Thursday',
    friday: 'Friday',
    saturday: 'Saturday',
  },
  delivery: {
    title: 'Delivery',
    method: 'Delivery method',
    shipping: 'Shipping',
    shipToAddress: 'Ship to your address',
    localPickup: 'Local Pickup',
    pickupFromStore: 'Pick up from store location',
  },
  tips: {
    title: 'Add a tip',
    noTip: 'No Tip',
    customAmount: 'Custom Amount',
    customTipAmount: 'Custom Tip Amount',
    placeholder: '€0.00',
  },
  shipping: {
    title: 'Shipping',
    description: 'Shipping address',
    method: 'Shipping method',
    noShippingMethodAddress:
      'Enter your address to see available shipping methods.',
    noShippingMethods: 'No shipping methods found.',
    phone: 'Phone Number',
    country: 'Country',
    selectCountry: 'Select country',
    searchCountry: 'Search country...',
    noCountryFound: 'No country found',
    firstName: 'First Name',
    lastName: 'Last Name',
    address1: 'Address',
    address2: 'Apartment, suite, etc. (optional)',
    city: 'City',
    region: 'State/County',
    postalCode: 'Postal Code',
    notesPlaceholder: 'Notes or special instructions',
    addressSuggestion: 'Did you mean',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'No shipping origin address provided.',
  },
  billing: {
    title: 'Billing',
    description: 'Billing description',
  },
  payment: {
    title: 'Payment',
    description: 'All payments are secure and encrypted.',
    billingAddress: {
      title: 'Billing Address',
      description: 'Enter your billing address.',
      useShippingAddress: 'Use shipping address as billing address',
    },
    methods: {
      creditCard: 'Credit or Debit Card',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Offline payments',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
    },
    noMethodsAvailable: 'No payment methods available',
    cardNumber: 'Card number',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Expiration date (MM / YY)',
    securityCode: 'Security code',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Name on card',
    payNow: 'Pay now',
    standardShipping: 'Standard Shipping',
    cardDetails: 'Card details',
    payWithApplePay: 'Pay with Apple Pay',
    expirationDatePlaceholder: 'MM / YY',
    failedToInitializePayment: 'Failed to initialise payment.',
    orderTotal: 'Order Total',
    subtotal: 'Subtotal',
    tax: 'VAT',
    shipping: 'Shipping',
    discount: 'Voucher',
    processingPayment: 'Processing payment...',
    completingOrder: 'Completing order...',
    completeOrder: 'Complete your order',
    freePayment: 'Complete your free order',
  },
  phone: {
    placeholder: '+353 1 234 5678',
    searchCountry: 'Search country...',
    noCountryFound: 'No country found.',
  },
  discounts: {
    placeholder: 'Voucher code',
    enterCode: 'Enter voucher code',
    apply: 'Apply',
    alreadyApplied: 'This voucher code has already been applied',
    failedToApply: 'Failed to apply voucher code',
    enterCodeValidation: 'Please enter a voucher code',
  },
  totals: {
    subtotal: 'Subtotal',
    discount: 'Discount',
    shipping: 'Shipping',
    tip: 'Tip',
    estimatedTaxes: 'Estimated VAT',
    totalDue: 'Total Due',
    orderSummary: 'Order Summary',
    itemCount: 'items',
    noItems: 'No items',
  },
  lineItems: {
    note: 'Note:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Address',
      suggestions: 'Suggestions',
    },
    form: {
      useFormFieldError: 'useFormField should be used within <FormField>',
    },
    pagination: {
      ariaLabel: 'pagination',
      previousPageAriaLabel: 'Go to previous page',
      previous: 'Previous',
      nextPageAriaLabel: 'Go to next page',
      next: 'Next',
      morePages: 'More pages',
    },
    sidebar: {
      useSidebarError: 'useSidebar must be used within a SidebarProvider.',
      toggleSidebar: 'Toggle Sidebar',
    },
    accessibility: {
      payWithApplePay: 'Pay with Apple Pay',
      applePayLogo: 'Apple Pay Logo',
      close: 'Close',
      additionalTipOptions: 'Additional tip options',
      breadcrumb: 'breadcrumb',
      more: 'More',
      previousSlide: 'Previous slide',
      nextSlide: 'Next slide',
    },
  },
  errors: {
    failedToGetAccessToken: 'Failed to get access token',
    invalidEnvironment: 'Invalid environment',
    noPublicAccessToken: 'No public access token provided',
    noSessionToken: 'No session token or ID provided',
    errorCreatingSession: 'Error creating checkout session:',
    orderIdRequired: 'Order ID is required',
    errorTrackingEvent: 'Error tracking event',
    errorInTrackingSubscriber: 'Error in tracking subscriber',
    useTrackingProviderError:
      'useTracking must be used within a TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect must be used within a PoyntCollectProvider',
    useSquareProviderError: 'useSquare must be used within a SquareProvider',
    errorProcessingPayment: 'Error processing payment',
    stripeConfigMissing:
      'Stripe configuration is missing. Please check your setup.',
    paymentSuccessful: 'Payment successful',
    paymentFailed: 'Payment failed',
    paypalConfigMissing:
      'PayPal configuration is missing. Please check your setup.',
    stripeNotReady: 'Stripe not ready',
    cardElementNotFound: 'CardElement not found',
    errorProcessingCardPayment: 'Error processing card payment.',
    errorProcessingExpressPayment: 'Error processing express payment.',
    failedToInitializePayment: 'Failed to initialise payment.',
    invalidPhoneNumber: 'invalid phone number',
  },
  validation: {
    phoneRequired: 'Phone number is required',
    emailRequired: 'Enter an email',
    emailInvalid: 'Enter a valid email',
    phoneTooLong: 'Phone number too long',
    invalidShippingAddress: 'Invalid shipping address',
    invalidBillingAddress: 'Invalid billing address',
    selectPaymentMethod: 'Select a payment method',
    enterValidBillingPhone: 'Enter a valid billing phone number',
    enterValidShippingPhone: 'Enter a valid shipping phone number',
    enterFirstName: 'Enter a first name',
    enterLastName: 'Enter a last name',
    enterAddress: 'Enter an address',
    enterCity: 'Enter a city',
    enterZipCode: 'Enter a postal code',
    enterZipPostalCode: 'Enter a postal code',
    selectState: 'Select a county',
    selectCountry: 'Select a country',
    enterCountry: 'Enter a country',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Server error',
    SESSION_NOT_FOUND: 'Session not found',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Failed to retrieve checkout session',
    CHECKOUT_SESSION_NOT_FOUND: 'Checkout session not found',
    CHECKOUT_SESSION_FETCH_ERROR: 'General checkout session fetch error',
    DRAFT_ORDER_NOT_FOUND: 'Order not found',
    CHECKOUT_SESSION_CREATION_FAILED: 'Failed to create checkout session',
    CREATED_SESSION_DATA_NOT_FOUND: 'Created session data not found',
    CHECKOUT_SESSION_CREATION_ERROR: 'General checkout session creation error',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Failed to update checkout session',
    UPDATED_SESSION_NOT_FOUND: 'Updated session not found',
    CHECKOUT_SESSION_UPDATE_ERROR: 'General checkout session update error',
    ORDER_API_NOT_FOUND: 'Order API data source not found',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Failed to retrieve order',
    DATA_SOURCES_NOT_FOUND: 'Data sources not found',
    TRANSACTION_API_NOT_FOUND: 'Transaction API data source not found',
    TRANSACTION_PROCESSING_FAILED: 'Failed to process transaction',
    TRANSACTION_CREATION_FAILED: 'Failed to find or create transaction',
    ORDER_OPENING_FAILED: 'Failed to open order',
    INVALID_FULFILLMENT_LOCATION: 'Invalid fulfillment location',
    NO_VALID_PICKUP_LOCATION: 'No valid pickup location available',
    DRAFT_ORDER_FETCH_FAILED: 'Failed to fetch order',
    LINE_ITEMS_FETCH_FAILED: 'Failed to fetch line items',
    CURRENT_ORDER_FETCH_FAILED: 'Failed to fetch current order',
    DRAFT_ORDER_UPDATE_FAILED: 'Failed to update order',
    DISCOUNT_APPLICATION_FAILED: 'Failed to apply voucher',
    CONTEXT_UNAVAILABLE: 'Session or data sources not available',
    SHIPPING_LINES_UPDATE_FAILED: 'Failed to update shipping lines',
    ORDER_TOTALS_UPDATE_FAILED: 'Failed to update order totals',
    ORDER_TOTAL_CALCULATION_FAILED: 'Failed to calculate order totals',
    SHIPPING_METHOD_APPLICATION_FAILED: 'Failed to apply shipping method',
    SKU_FETCH_FAILED: 'Failed to fetch SKUs',
    SHIPPING_RATES_CALCULATION_FAILED: 'Failed to calculate shipping rates',
    SHIPPING_METHOD_NOT_FOUND: 'Shipping method not found',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Failed to remove shipping method',
    SHIPPING_ADDRESS_REQUIRED: 'Shipping address required',
    INVENTORY_VALIDATION_ERROR: 'Inventory validation error',
    INSUFFICIENT_INVENTORY: 'Insufficient inventory',
    INVALID_ORDER_STATUS: 'Invalid order status',
    TRANSACTION_CREATION_ERROR: 'Transaction creation error',
    TRANSACTION_PROCESSING_ERROR: 'Transaction processing error',
    UNKNOWN_ERROR: 'Unknown error',
    FULFILLMENT_CREATION_ERROR: 'Fulfillment creation error',
    TAX_CALCULATION_ERROR: 'VAT calculation error',
    ADDRESS_VERIFICATION_ERROR: 'Address verification error',
    ADDRESS_MATCHES_ERROR: 'Address matches error',
    SHIPPING_CONFLICT_ERROR: 'Shipping conflict error',
    SHIPPING_ERROR: 'General shipping error',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Price adjustment calculation error',
    ORDER_FETCH_ERROR: 'Order fetch error',
    DRAFT_ORDER_UPDATE_ERROR: 'Order update error',
    DISCOUNT_APPLICATION_ERROR: 'Voucher application error',
    DRAFT_ORDER_OPEN_ERROR: 'Order open error',
    ORDER_UPDATE_ERROR: 'Order update error',
    CATALOG_FETCH_ERROR: 'Catalogue fetch error',
    STORE_ID_NOT_FOUND: 'Store ID not found',
    ORDER_NOT_DRAFT: 'Order is not in valid status',
    NO_LINE_ITEMS: 'No line items found',
    BAD_USER_INPUT: 'Invalid user input',
    MISSING_SHIPPING_ADDRESS: 'Shipping address is required',
    MISSING_REQUIRED_FIELD: 'Required field is missing',
    CATALOG_API_ERROR: 'Catalogue service error',
    TAX_SERVICE_UNAVAILABLE: 'VAT service is unavailable',
    SHIPPING_SERVICE_UNAVAILABLE: 'Shipping service is unavailable',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Price adjustments service is unavailable',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'Failed to calculate price adjustments',
    SERVICE_UNAVAILABLE: 'Service is temporarily unavailable',
    RATE_LIMITED: 'Too many requests, please try again later',
    TIMEOUT: 'Request timed out',
    INTERNAL_ERROR: 'Internal server error',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Shipping postal code is required',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Shipping country code is required',
    SHIPPING_METHOD_REQUIRED: 'Shipping method is required',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      'Shipping address verification failed',
    BILLING_ADDRESS_VERIFICATION_FAILED: 'Billing address verification failed',
    MISSING_SHIPPING_INFO: 'Shipping address or method failed to apply',
    DEPENDENCY_ERROR:
      "We're unable to process your order right now. Please wait a moment and try again",
  },
  storefront: {
    product: 'Product',
    sale: 'SALE',
    noImage: 'No image',
    noImageAvailable: 'No image available',
    selectOptions: 'Select Options',
    adding: 'Adding...',
    addToCart: 'Add to Cart',
    shoppingCart: 'Shopping Cart',
    failedToLoadCart: 'Failed to load cart:',
    retry: 'Retry',
    yourCartIsEmpty: 'Your cart is empty',
    addItemsToGetStarted: 'Add items to get started',
    errorLoadingProducts: 'Error loading products:',
    errorLoadingProduct: 'Error loading product:',
    productNotFound: 'Product not found',
    loadingVariantDetails: 'Loading variant details...',
    combinationNotAvailable:
      'This combination is not available. Please select different options.',
    variantsMatch:
      'variants match your selection. Select more attributes to narrow down.',
    quantity: 'Quantity',
    addingToCart: 'Adding to Cart...',
    outOfStock: 'Out of Stock',
    productType: 'Product Type:',
    productId: 'Product ID:',
    selectedSku: 'Selected SKU:',
    stockStatus: 'Stock Status:',
    lowStock: 'Low Stock',
    inStock: 'In Stock',
    remove: 'Remove',
    removing: 'Removing...',
    checkout: 'Checkout',
  },
};
