export const esCo = {
  general: {
    optional: 'opcional',
    notes: 'Notas',
    quantity: 'Cantidad',
    free: 'GRATIS',
    closed: 'Cerrado',
    apply: 'Aplicar',
    checkoutDisabled: 'El checkout está deshabilitado actualmente. Pedimos disculpas por las molestias.',
  },
  contact: {
    title: 'Contacto',
    description: '',
    email: 'Correo electrónico',
  },
  pickup: {
    title: 'Recogida en tienda',
    description:
      'Haremos todo lo posible para cumplir con la hora de recogida esperada. Las horas reales de recogida pueden variar.',
    location: 'Ubicación de recogida',
    date: 'Fecha de recogida',
    time: 'Hora preferida de recogida',
    selectStore: 'Selecciona una ubicación de tienda',
    selectDate: 'Selecciona una fecha',
    selectTime: 'Selecciona una hora de recogida',
    storeHours: 'Horarios de la tienda',
    seeDetails: 'Ver detalles',
    noTimeSlots: 'No hay horarios disponibles para la fecha seleccionada. Por favor selecciona otra fecha.',
    hoursDisplayed: 'Horarios mostrados en tu zona horaria local.',
    storeOperatesIn: 'La tienda opera en zona horaria {timezone}.',
    asap: 'LO MÁS PRONTO POSIBLE',
    hour: 'hora',
    hours: 'horas',
    minutes: 'minutos',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país.',
  },
  days: {
    sunday: 'Domingo',
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sábado',
  },
  delivery: {
    title: 'Entrega',
    method: 'Método de entrega',
    shipping: 'Envío',
    shipToAddress: 'Enviar a tu dirección',
    localPickup: 'Recogida en tienda',
    pickupFromStore: 'Recoger en ubicación de la tienda',
  },
  tips: {
    title: 'Agregar propina',
    noTip: 'Sin propina',
    customAmount: 'Monto personalizado',
    customTipAmount: 'Monto de propina personalizado',
    placeholder: '$0.00',
  },
  shipping: {
    title: 'Envío',
    description: 'Dirección de envío',
    method: 'Método de envío',
    noShippingMethodAddress: 'Ingresa tu dirección para ver los métodos de envío disponibles.',
    noShippingMethods: 'No se encontraron métodos de envío.',
    phone: 'Número de teléfono',
    country: 'País',
    selectCountry: 'Seleccionar país',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país',
    firstName: 'Nombre',
    lastName: 'Apellido',
    address1: 'Dirección',
    address2: 'Apartamento, oficina, etc.',
    city: 'Ciudad',
    region: 'Departamento/Estado',
    postalCode: 'Código postal',
    notesPlaceholder: 'Notas o instrucciones especiales',
    addressSuggestion: '¿Quisiste decir',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'No se proporcionó dirección de origen de envío.',
  },
  billing: {
    title: 'Facturación',
    description: 'Descripción de facturación',
  },
  payment: {
    title: 'Pago',
    description: 'Todos los pagos son seguros y encriptados.',
    billingAddress: {
      title: 'Dirección de facturación',
      description: 'Ingresa tu dirección de facturación.',
      useShippingAddress: 'Usar dirección de envío como dirección de facturación',
    },
    methods: {
      creditCard: 'Tarjeta de crédito o débito',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Pagos sin conexión',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
    },
    noMethodsAvailable: 'No hay métodos de pago disponibles',
    cardNumber: 'Número de tarjeta',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Fecha de vencimiento (MM / AA)',
    securityCode: 'Código de seguridad',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nombre en la tarjeta',
    payNow: 'Pagar ahora',
    standardShipping: 'Envío estándar',
    cardDetails: 'Detalles de la tarjeta',
    payWithApplePay: 'Pagar con Apple Pay',
    expirationDatePlaceholder: 'MM / AA',
    failedToInitializePayment: 'Error al inicializar el pago.',
    orderTotal: 'Total del pedido',
    subtotal: 'Subtotal',
    tax: 'Impuestos',
    shipping: 'Envío',
    discount: 'Cupón',
    processingPayment: 'Procesando pago...',
    completingOrder: 'Completando pedido...',
    completeOrder: 'Completar tu pedido',
    freePayment: 'Completa tu pedido gratuito',
  },
  phone: {
    placeholder: '(057) 300 123 4567',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país.',
  },
  discounts: {
    placeholder: 'Código de cupón',
    enterCode: 'Ingresa código de cupón',
    apply: 'Aplicar',
    alreadyApplied: 'Este código de cupón ya fue aplicado',
    failedToApply: 'Error al aplicar código de cupón',
    enterCodeValidation: 'Por favor ingresa un código de cupón',
  },
  totals: {
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    tip: 'Propina',
    estimatedTaxes: 'Impuestos estimados',
    totalDue: 'Total a pagar',
    orderSummary: 'Resumen del pedido',
    itemCount: 'artículos',
    noItems: 'Sin artículos',
  },
  lineItems: {
    note: 'Nota:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Dirección',
      suggestions: 'Sugerencias',
    },
    form: {
      useFormFieldError: 'useFormField debe usarse dentro de <FormField>',
    },
    pagination: {
      ariaLabel: 'paginación',
      previousPageAriaLabel: 'Ir a la página anterior',
      previous: 'Anterior',
      nextPageAriaLabel: 'Ir a la página siguiente',
      next: 'Siguiente',
      morePages: 'Más páginas',
    },
    sidebar: {
      useSidebarError: 'useSidebar debe usarse dentro de un SidebarProvider.',
      toggleSidebar: 'Alternar barra lateral',
    },
    accessibility: {
      payWithApplePay: 'Pagar con Apple Pay',
      applePayLogo: 'Logo de Apple Pay',
      close: 'Cerrar',
      additionalTipOptions: 'Opciones de propina adicionales',
      breadcrumb: 'ruta de navegación',
      more: 'Más',
      previousSlide: 'Diapositiva anterior',
      nextSlide: 'Siguiente diapositiva',
    },
  },
  errors: {
    failedToGetAccessToken: 'Error al obtener token de acceso',
    invalidEnvironment: 'Entorno inválido',
    noPublicAccessToken: 'No se proporcionó token de acceso público',
    noSessionToken: 'No se proporcionó token de sesión o cédula',
    errorCreatingSession: 'Error al crear sesión de checkout:',
    orderIdRequired: 'Se requiere cédula del pedido',
    errorTrackingEvent: 'Error al rastrear evento',
    errorInTrackingSubscriber: 'Error en suscriptor de rastreo',
    useTrackingProviderError: 'useTracking debe usarse dentro de un TrackingProvider',
    usePoyntCollectProviderError: 'usePoyntCollect debe usarse dentro de un PoyntCollectProvider',
    useSquareProviderError: 'useSquare debe usarse dentro de un SquareProvider',
    errorProcessingPayment: 'Error al procesar el pago',
    stripeConfigMissing: 'Falta configuración de Stripe. Por favor verifica tu configuración.',
    paymentSuccessful: 'Pago exitoso',
    paymentFailed: 'Error en el pago',
    paypalConfigMissing: 'Falta configuración de PayPal. Por favor verifica tu configuración.',
    stripeNotReady: 'Stripe no está listo',
    cardElementNotFound: 'CardElement no encontrado',
    errorProcessingCardPayment: 'Error al procesar pago con tarjeta.',
    errorProcessingExpressPayment: 'Error al procesar pago express.',
    failedToInitializePayment: 'Error al inicializar el pago.',
    invalidPhoneNumber: 'número de teléfono inválido',
  },
  validation: {
    phoneRequired: 'Se requiere número de teléfono',
    emailRequired: 'Ingresa un correo electrónico',
    emailInvalid: 'Ingresa un correo electrónico válido',
    phoneTooLong: 'Número de teléfono demasiado largo',
    invalidShippingAddress: 'Dirección de envío inválida',
    invalidBillingAddress: 'Dirección de facturación inválida',
    selectPaymentMethod: 'Selecciona un método de pago',
    enterValidBillingPhone: 'Ingresa un número de teléfono de facturación válido',
    enterValidShippingPhone: 'Ingresa un número de teléfono de envío válido',
    enterFirstName: 'Ingresa un nombre',
    enterLastName: 'Ingresa un apellido',
    enterAddress: 'Ingresa una dirección',
    enterCity: 'Ingresa una ciudad',
    enterZipCode: 'Ingresa un código postal',
    enterZipPostalCode: 'Ingresa un código postal',
    selectState: 'Selecciona un departamento/región',
    selectCountry: 'Selecciona un país',
    enterCountry: 'Ingresa un país',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Error del servidor',
    SESSION_NOT_FOUND: 'Sesión no encontrada',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Error al recuperar sesión de checkout',
    CHECKOUT_SESSION_NOT_FOUND: 'Sesión de checkout no encontrada',
    CHECKOUT_SESSION_FETCH_ERROR: 'Error general al obtener sesión de checkout',
    DRAFT_ORDER_NOT_FOUND: 'Pedido no encontrado',
    CHECKOUT_SESSION_CREATION_FAILED: 'Error al crear sesión de checkout',
    CREATED_SESSION_DATA_NOT_FOUND: 'Datos de sesión creada no encontrados',
    CHECKOUT_SESSION_CREATION_ERROR: 'Error general al crear sesión de checkout',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Error al actualizar sesión de checkout',
    UPDATED_SESSION_NOT_FOUND: 'Sesión actualizada no encontrada',
    CHECKOUT_SESSION_UPDATE_ERROR: 'Error general al actualizar sesión de checkout',
    ORDER_API_NOT_FOUND: 'Fuente de datos de API de pedidos no encontrada',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Error al recuperar pedido',
    DATA_SOURCES_NOT_FOUND: 'Fuentes de datos no encontradas',
    TRANSACTION_API_NOT_FOUND: 'Fuente de datos de API de transacciones no encontrada',
    TRANSACTION_PROCESSING_FAILED: 'Error al procesar transacción',
    TRANSACTION_CREATION_FAILED: 'Error al encontrar o crear transacción',
    ORDER_OPENING_FAILED: 'Error al abrir pedido',
    INVALID_FULFILLMENT_LOCATION: 'Ubicación de cumplimiento inválida',
    NO_VALID_PICKUP_LOCATION: 'No hay ubicación de recogida válida disponible',
    DRAFT_ORDER_FETCH_FAILED: 'Error al obtener pedido',
    LINE_ITEMS_FETCH_FAILED: 'Error al obtener elementos del pedido',
    CURRENT_ORDER_FETCH_FAILED: 'Error al obtener pedido actual',
    DRAFT_ORDER_UPDATE_FAILED: 'Error al actualizar pedido',
    DISCOUNT_APPLICATION_FAILED: 'Error al aplicar cupón',
    CONTEXT_UNAVAILABLE: 'Sesión o fuentes de datos no disponibles',
    SHIPPING_LINES_UPDATE_FAILED: 'Error al actualizar líneas de envío',
    ORDER_TOTALS_UPDATE_FAILED: 'Error al actualizar totales del pedido',
    ORDER_TOTAL_CALCULATION_FAILED: 'Error al calcular totales del pedido',
    SHIPPING_METHOD_APPLICATION_FAILED: 'Error al aplicar método de envío',
    SKU_FETCH_FAILED: 'Error al obtener SKUs',
    SHIPPING_RATES_CALCULATION_FAILED: 'Error al calcular tarifas de envío',
    SHIPPING_METHOD_NOT_FOUND: 'Método de envío no encontrado',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Error al eliminar método de envío',
    SHIPPING_ADDRESS_REQUIRED: 'Se requiere dirección de envío',
    INVENTORY_VALIDATION_ERROR: 'Error de validación de inventario',
    INSUFFICIENT_INVENTORY: 'Inventario insuficiente',
    INVALID_ORDER_STATUS: 'Estado de pedido inválido',
    TRANSACTION_CREATION_ERROR: 'Error de creación de transacción',
    TRANSACTION_PROCESSING_ERROR: 'Error de procesamiento de transacción',
    UNKNOWN_ERROR: 'Error desconocido',
    FULFILLMENT_CREATION_ERROR: 'Error de creación de cumplimiento',
    TAX_CALCULATION_ERROR: 'Error de cálculo de impuestos',
    ADDRESS_VERIFICATION_ERROR: 'Error de verificación de dirección',
    ADDRESS_MATCHES_ERROR: 'Error de coincidencias de dirección',
    SHIPPING_CONFLICT_ERROR: 'Error de conflicto de envío',
    SHIPPING_ERROR: 'Error general de envío',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Error de cálculo de ajuste de precio',
    ORDER_FETCH_ERROR: 'Error al obtener pedido',
    DRAFT_ORDER_UPDATE_ERROR: 'Error al actualizar pedido',
    DISCOUNT_APPLICATION_ERROR: 'Error de aplicación de cupón',
    DRAFT_ORDER_OPEN_ERROR: 'Error al abrir pedido',
    ORDER_UPDATE_ERROR: 'Error al actualizar pedido',
    CATALOG_FETCH_ERROR: 'Error al obtener catálogo',
    STORE_ID_NOT_FOUND: 'ID de tienda no encontrado',
    ORDER_NOT_DRAFT: 'El pedido no está en estado válido',
    NO_LINE_ITEMS: 'No se encontraron artículos',
    BAD_USER_INPUT: 'Entrada de usuario inválida',
    MISSING_SHIPPING_ADDRESS: 'Se requiere dirección de envío',
    MISSING_REQUIRED_FIELD: 'Falta campo obligatorio',
    CATALOG_API_ERROR: 'Error de servicio de catálogo',
    TAX_SERVICE_UNAVAILABLE: 'Servicio de impuestos no disponible',
    SHIPPING_SERVICE_UNAVAILABLE: 'Servicio de envío no disponible',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE: 'Servicio de ajustes de precios no disponible',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED: 'Error al calcular ajustes de precios',
    SERVICE_UNAVAILABLE: 'Servicio temporalmente no disponible',
    RATE_LIMITED: 'Demasiadas solicitudes, por favor inténtelo más tarde',
    TIMEOUT: 'Tiempo de espera agotado',
    INTERNAL_ERROR: 'Error interno del servidor',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Se requiere código postal de envío',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Se requiere código de país de envío',
    SHIPPING_METHOD_REQUIRED: 'Se requiere método de envío',
    SHIPPING_ADDRESS_VERIFICATION_FAILED: 'Falló la verificación de dirección de envío',
    BILLING_ADDRESS_VERIFICATION_FAILED: 'Falló la verificación de dirección de facturación',
    MISSING_SHIPPING_INFO: 'No se pudo aplicar la dirección o método de envío',
    DEPENDENCY_ERROR: 'No podemos procesar su pedido en este momento. Espere un momento e inténtelo de nuevo',
  },
};
