export const esEs = {
  general: {
    optional: 'opcional',
    notes: 'Notas',
    quantity: 'Cantidad',
    free: 'GRATIS',
    closed: 'Cerrado',
    apply: 'Aplicar',
    checkoutDisabled:
      'El checkout está deshabilitado actualmente. Pedimos disculpas por las molestias.',
  },
  contact: {
    title: 'Contacto',
    description: '',
    email: 'Correo electrónico',
  },
  pickup: {
    title: 'Recogida local',
    description:
      'Haremos todo lo posible para cumplir con su hora de recogida esperada. Los horarios reales de recogida pueden variar.',
    location: 'Ubicación de recogida',
    date: 'Fecha de recogida',
    time: 'Hora de recogida preferida',
    selectStore: 'Selecciona una ubicación de tienda',
    selectDate: 'Selecciona una fecha',
    selectTime: 'Selecciona una hora de recogida',
    storeHours: 'Horario de la tienda',
    seeDetails: 'Ver detalles',
    noTimeSlots:
      'No hay horarios disponibles para la fecha seleccionada. Por favor selecciona otra fecha.',
    hoursDisplayed: 'Horarios mostrados en tu zona horaria local.',
    storeOperatesIn: 'La tienda opera en la zona horaria {timezone}.',
    asap: 'Lo antes posible',
    hour: 'hora',
    hours: 'horas',
    minutes: 'minutos',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país.',
  },
  days: {
    sunday: 'Domingo',
    monday: 'Lunes',
    tuesday: 'Martes',
    wednesday: 'Miércoles',
    thursday: 'Jueves',
    friday: 'Viernes',
    saturday: 'Sábado',
  },
  delivery: {
    title: 'Entrega',
    method: 'Método de entrega',
    shipping: 'Envío',
    shipToAddress: 'Enviar a tu dirección',
    localPickup: 'Recogida local',
    pickupFromStore: 'Recoger de la ubicación de la tienda',
  },
  tips: {
    title: 'Añadir propina',
    noTip: 'Sin propina',
    customAmount: 'Cantidad personalizada',
    customTipAmount: 'Cantidad de propina personalizada',
    placeholder: '$0.00',
  },
  shipping: {
    title: 'Envío',
    description: 'Dirección de envío',
    method: 'Método de envío',
    noShippingMethodAddress:
      'Introduce tu dirección para ver los métodos de envío disponibles.',
    noShippingMethods: 'No se encontraron métodos de envío.',
    phone: 'Número de teléfono',
    country: 'País',
    selectCountry: 'Seleccionar país',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país',
    firstName: 'Nombre',
    lastName: 'Apellido',
    address1: 'Dirección',
    address2: 'Apartamento, suite, etc.',
    city: 'Ciudad',
    region: 'Estado/Provincia',
    postalCode: 'Código postal',
    notesPlaceholder: 'Notas o instrucciones especiales',
    addressSuggestion: '¿Querías decir',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'No se proporcionó dirección de origen de envío.',
  },
  billing: {
    title: 'Facturación',
    description: 'Descripción de facturación',
  },
  payment: {
    title: 'Pago',
    description: 'Todos los pagos son seguros y están encriptados.',
    billingAddress: {
      title: 'Dirección de facturación',
      description: 'Introduce tu dirección de facturación.',
      useShippingAddress:
        'Usar dirección de envío como dirección de facturación',
    },
    methods: {
      creditCard: 'Tarjeta de crédito o débito',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Pagos sin conexión',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
    },
    noMethodsAvailable: 'No hay métodos de pago disponibles',
    cardNumber: 'Número de tarjeta',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Fecha de vencimiento (MM / AA)',
    securityCode: 'Código de seguridad',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nombre en la tarjeta',
    payNow: 'Pagar ahora',
    standardShipping: 'Envío estándar',
    cardDetails: 'Detalles de la tarjeta',
    payWithApplePay: 'Pagar con Apple Pay',
    expirationDatePlaceholder: 'MM / AA',
    failedToInitializePayment: 'Error al inicializar el pago.',
    orderTotal: 'Total del pedido',
    subtotal: 'Subtotal',
    tax: 'Impuestos',
    shipping: 'Envío',
    discount: 'Cupón',
    processingPayment: 'Procesando pago...',
    completingOrder: 'Completando pedido...',
    completeOrder: 'Completar tu pedido',
    freePayment: 'Completa tu pedido gratuito',
  },
  phone: {
    placeholder: '(201) 555-1234',
    searchCountry: 'Buscar país...',
    noCountryFound: 'No se encontró el país.',
  },
  discounts: {
    placeholder: 'Código de cupón',
    enterCode: 'Introduce código de cupón',
    apply: 'Aplicar',
    alreadyApplied: 'Este código de cupón ya ha sido aplicado',
    failedToApply: 'Error al aplicar el código de cupón',
    enterCodeValidation: 'Por favor introduce un código de cupón',
  },
  totals: {
    subtotal: 'Subtotal',
    discount: 'Descuento',
    shipping: 'Envío',
    tip: 'Propina',
    estimatedTaxes: 'Impuestos estimados',
    totalDue: 'Total a pagar',
    orderSummary: 'Resumen del pedido',
    itemCount: 'artículos',
    noItems: 'Sin artículos',
  },
  lineItems: {
    note: 'Nota:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Dirección',
      suggestions: 'Sugerencias',
    },
    form: {
      useFormFieldError: 'useFormField debe usarse dentro de <FormField>',
    },
    pagination: {
      ariaLabel: 'paginación',
      previousPageAriaLabel: 'Ir a la página anterior',
      previous: 'Anterior',
      nextPageAriaLabel: 'Ir a la siguiente página',
      next: 'Siguiente',
      morePages: 'Más páginas',
    },
    sidebar: {
      useSidebarError: 'useSidebar debe usarse dentro de un SidebarProvider.',
      toggleSidebar: 'Alternar barra lateral',
    },
    accessibility: {
      payWithApplePay: 'Pagar con Apple Pay',
      applePayLogo: 'Logo de Apple Pay',
      close: 'Cerrar',
      additionalTipOptions: 'Opciones de propina adicionales',
      breadcrumb: 'ruta de navegación',
      more: 'Más',
      previousSlide: 'Diapositiva anterior',
      nextSlide: 'Siguiente diapositiva',
    },
  },
  errors: {
    failedToGetAccessToken: 'Error al obtener el token de acceso',
    invalidEnvironment: 'Entorno inválido',
    noPublicAccessToken: 'No se proporcionó token de acceso público',
    noSessionToken: 'No se proporcionó token o ID de sesión',
    errorCreatingSession: 'Error al crear la sesión de checkout:',
    orderIdRequired: 'Se requiere ID de pedido',
    errorTrackingEvent: 'Error al rastrear evento',
    errorInTrackingSubscriber: 'Error en el suscriptor de rastreo',
    useTrackingProviderError:
      'useTracking debe usarse dentro de un TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect debe usarse dentro de un PoyntCollectProvider',
    useSquareProviderError: 'useSquare debe usarse dentro de un SquareProvider',
    errorProcessingPayment: 'Error al procesar el pago',
    stripeConfigMissing:
      'Falta la configuración de Stripe. Por favor verifica tu configuración.',
    paymentSuccessful: 'Pago exitoso',
    paymentFailed: 'Pago fallido',
    paypalConfigMissing:
      'Falta la configuración de PayPal. Por favor verifica tu configuración.',
    stripeNotReady: 'Stripe no está listo',
    cardElementNotFound: 'Elemento de tarjeta no encontrado',
    errorProcessingCardPayment: 'Error al procesar el pago con tarjeta.',
    errorProcessingExpressPayment: 'Error al procesar el pago exprés.',
    failedToInitializePayment: 'Error al inicializar el pago.',
    invalidPhoneNumber: 'número de teléfono inválido',
  },
  validation: {
    phoneRequired: 'Se requiere número de teléfono',
    emailRequired: 'Introduce un correo electrónico',
    emailInvalid: 'Introduce un correo electrónico válido',
    phoneTooLong: 'Número de teléfono demasiado largo',
    invalidShippingAddress: 'Dirección de envío inválida',
    invalidBillingAddress: 'Dirección de facturación inválida',
    selectPaymentMethod: 'Selecciona un método de pago',
    enterValidBillingPhone:
      'Introduce un número de teléfono de facturación válido',
    enterValidShippingPhone: 'Introduce un número de teléfono de envío válido',
    enterFirstName: 'Introduce un nombre',
    enterLastName: 'Introduce un apellido',
    enterAddress: 'Introduce una dirección',
    enterCity: 'Introduce una ciudad',
    enterZipCode: 'Introduce un código postal',
    enterZipPostalCode: 'Introduce un código ZIP / postal',
    selectState: 'Selecciona un estado/provincia',
    selectCountry: 'Selecciona un país',
    enterCountry: 'Introduce un país',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Error del servidor',
    SESSION_NOT_FOUND: 'Sesión no encontrada',
    CHECKOUT_SESSION_RETRIEVAL_FAILED:
      'No se pudo recuperar la sesión de checkout',
    CHECKOUT_SESSION_NOT_FOUND: 'Sesión de checkout no encontrada',
    CHECKOUT_SESSION_FETCH_ERROR:
      'Error general al obtener la sesión de checkout',
    DRAFT_ORDER_NOT_FOUND: 'Pedido no encontrado',
    CHECKOUT_SESSION_CREATION_FAILED: 'No se pudo crear la sesión de checkout',
    CREATED_SESSION_DATA_NOT_FOUND: 'Datos de la sesión creada no encontrados',
    CHECKOUT_SESSION_CREATION_ERROR:
      'Error general al crear la sesión de checkout',
    CHECKOUT_SESSION_UPDATE_FAILED:
      'No se pudo actualizar la sesión de checkout',
    UPDATED_SESSION_NOT_FOUND: 'Sesión actualizada no encontrada',
    CHECKOUT_SESSION_UPDATE_ERROR:
      'Error general al actualizar la sesión de checkout',
    ORDER_API_NOT_FOUND: 'Fuente de datos de la API de pedidos no encontrada',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'No se pudo recuperar el pedido',
    DATA_SOURCES_NOT_FOUND: 'Fuentes de datos no encontradas',
    TRANSACTION_API_NOT_FOUND:
      'Fuente de datos de la API de transacciones no encontrada',
    TRANSACTION_PROCESSING_FAILED: 'No se pudo procesar la transacción',
    TRANSACTION_CREATION_FAILED: 'No se pudo encontrar o crear la transacción',
    ORDER_OPENING_FAILED: 'No se pudo abrir el pedido',
    INVALID_FULFILLMENT_LOCATION: 'Ubicación de cumplimiento inválida',
    NO_VALID_PICKUP_LOCATION: 'No hay ubicación de recogida válida disponible',
    DRAFT_ORDER_FETCH_FAILED: 'No se pudo obtener el pedido',
    LINE_ITEMS_FETCH_FAILED: 'No se pudieron obtener los artículos',
    CURRENT_ORDER_FETCH_FAILED: 'No se pudo obtener el pedido actual',
    DRAFT_ORDER_UPDATE_FAILED: 'No se pudo actualizar el pedido',
    DISCOUNT_APPLICATION_FAILED: 'No se pudo aplicar el cupón',
    CONTEXT_UNAVAILABLE: 'Sesión o fuentes de datos no disponibles',
    SHIPPING_LINES_UPDATE_FAILED: 'No se pudo actualizar las líneas de envío',
    ORDER_TOTALS_UPDATE_FAILED: 'No se pudo actualizar los totales del pedido',
    ORDER_TOTAL_CALCULATION_FAILED:
      'No se pudo calcular los totales del pedido',
    SHIPPING_METHOD_APPLICATION_FAILED: 'No se pudo aplicar el método de envío',
    SKU_FETCH_FAILED: 'No se pudieron obtener los SKUs',
    SHIPPING_RATES_CALCULATION_FAILED:
      'No se pudieron calcular las tarifas de envío',
    SHIPPING_METHOD_NOT_FOUND: 'Método de envío no encontrado',
    SHIPPING_METHOD_REMOVAL_FAILED: 'No se pudo eliminar el método de envío',
    SHIPPING_ADDRESS_REQUIRED: 'Se requiere dirección de envío',
    INVENTORY_VALIDATION_ERROR: 'Error de validación de inventario',
    INSUFFICIENT_INVENTORY: 'Inventario insuficiente',
    INVALID_ORDER_STATUS: 'Estado de pedido inválido',
    TRANSACTION_CREATION_ERROR: 'Error al crear la transacción',
    TRANSACTION_PROCESSING_ERROR: 'Error al procesar la transacción',
    UNKNOWN_ERROR: 'Error desconocido',
    FULFILLMENT_CREATION_ERROR: 'Error al crear el cumplimiento',
    TAX_CALCULATION_ERROR: 'Error al calcular los impuestos',
    ADDRESS_VERIFICATION_ERROR: 'Error al verificar la dirección',
    ADDRESS_MATCHES_ERROR: 'Error en la coincidencia de direcciones',
    SHIPPING_CONFLICT_ERROR: 'Error de conflicto de envío',
    SHIPPING_ERROR: 'Error general de envío',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Error al calcular el ajuste de precio',
    ORDER_FETCH_ERROR: 'Error al obtener el pedido',
    DRAFT_ORDER_UPDATE_ERROR: 'Error al actualizar el pedido',
    DISCOUNT_APPLICATION_ERROR: 'Error al aplicar el cupón',
    DRAFT_ORDER_OPEN_ERROR: 'Error al abrir el pedido',
    ORDER_UPDATE_ERROR: 'Error al actualizar el pedido',
    CATALOG_FETCH_ERROR: 'Error al obtener el catálogo',
    STORE_ID_NOT_FOUND: 'ID de tienda no encontrado',
    ORDER_NOT_DRAFT: 'El pedido no está en estado válido',
    NO_LINE_ITEMS: 'No se encontraron artículos',
    BAD_USER_INPUT: 'Entrada de usuario inválida',
    MISSING_SHIPPING_ADDRESS: 'Se requiere dirección de envío',
    MISSING_REQUIRED_FIELD: 'Falta un campo requerido',
    CATALOG_API_ERROR: 'Error del servicio de catálogo',
    TAX_SERVICE_UNAVAILABLE: 'Servicio de impuestos no disponible',
    SHIPPING_SERVICE_UNAVAILABLE: 'Servicio de envío no disponible',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Servicio de ajustes de precio no disponible',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'No se pudieron calcular los ajustes de precio',
    SERVICE_UNAVAILABLE: 'Servicio temporalmente no disponible',
    RATE_LIMITED: 'Demasiadas solicitudes, intente nuevamente más tarde',
    TIMEOUT: 'Tiempo de espera agotado',
    INTERNAL_ERROR: 'Error interno del servidor',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Se requiere código postal de envío',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Se requiere código de país de envío',
    SHIPPING_METHOD_REQUIRED: 'Se requiere método de envío',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      'Falló la verificación de dirección de envío',
    BILLING_ADDRESS_VERIFICATION_FAILED:
      'Falló la verificación de dirección de facturación',
    MISSING_SHIPPING_INFO: 'No se pudo aplicar la dirección o método de envío',
    DEPENDENCY_ERROR:
      'No podemos procesar su pedido en este momento. Espere un momento e inténtelo de nuevo',
  },
  storefront: {
    product: 'Producto',
    sale: 'OFERTA',
    noImage: 'Sin imagen',
    noImageAvailable: 'Sin imagen disponible',
    selectOptions: 'Seleccionar opciones',
    adding: 'Añadiendo...',
    addToCart: 'Añadir al carrito',
    shoppingCart: 'Carrito de compras',
    failedToLoadCart: 'Error al cargar el carrito:',
    retry: 'Reintentar',
    yourCartIsEmpty: 'Tu carrito está vacío',
    addItemsToGetStarted: 'Añade artículos para comenzar',
    errorLoadingProducts: 'Error al cargar productos:',
    errorLoadingProduct: 'Error al cargar producto:',
    productNotFound: 'Producto no encontrado',
    loadingVariantDetails: 'Cargando detalles de la variante...',
    combinationNotAvailable:
      'Esta combinación no está disponible. Por favor seleccione opciones diferentes.',
    variantsMatch:
      'variantes coinciden con tu selección. Selecciona más atributos para reducir las opciones.',
    quantity: 'Cantidad',
    addingToCart: 'Añadiendo al carrito...',
    outOfStock: 'Agotado',
    productType: 'Tipo de producto:',
    productId: 'ID del producto:',
    selectedSku: 'SKU seleccionado:',
    stockStatus: 'Estado del stock:',
    lowStock: 'Stock bajo',
    inStock: 'En stock',
  },
};
