export const frFr = {
  general: {
    optional: 'optionnel',
    notes: 'Notes',
    quantity: 'Quantité',
    free: 'GRATUIT',
    closed: 'Fermé',
    apply: 'Appliquer',
    checkoutDisabled:
      'Le paiement est actuellement désactivé. Nous nous excusons pour la gêne occasionnée.',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Propulsé par',
  },
  contact: {
    title: 'Contact',
    description: '',
    email: 'Email',
  },
  pickup: {
    title: 'Retrait en magasin',
    description:
      'Tous les efforts seront faits pour respecter votre heure de retrait prévue. Les heures de retrait réelles peuvent varier.',
    location: 'Lieu de retrait',
    date: 'Date de retrait',
    time: 'Heure de retrait préférée',
    selectStore: 'Sélectionner un magasin',
    selectDate: 'Sélectionner une date',
    selectTime: 'Sélectionner une heure de retrait',
    storeHours: "Heures d'ouverture",
    seeDetails: 'Voir les détails',
    noTimeSlots:
      'Aucun créneau horaire disponible pour la date sélectionnée. Veuillez sélectionner une autre date.',
    hoursDisplayed: 'Heures affichées dans votre fuseau horaire local.',
    storeOperatesIn: 'Le magasin fonctionne dans le fuseau horaire {timezone}.',
    asap: 'ASAP',
    hour: 'heure',
    hours: 'heures',
    minutes: 'minutes',
    searchCountry: 'Rechercher un pays...',
    noCountryFound: 'Aucun pays trouvé.',
  },
  days: {
    sunday: 'Dimanche',
    monday: 'Lundi',
    tuesday: 'Mardi',
    wednesday: 'Mercredi',
    thursday: 'Jeudi',
    friday: 'Vendredi',
    saturday: 'Samedi',
  },
  delivery: {
    title: 'Livraison',
    method: 'Méthode de livraison',
    shipping: 'Expédition',
    shipToAddress: 'Livrer à votre adresse',
    localPickup: 'Retrait en magasin',
    pickupFromStore: 'Retirer en magasin',
  },
  tips: {
    title: 'Ajouter un pourboire',
    noTip: 'Aucun pourboire',
    customAmount: 'Montant personnalisé',
    customTipAmount: 'Montant du pourboire personnalisé',
    placeholder: '0,00 €',
  },
  shipping: {
    title: 'Expédition',
    description: 'Adresse de livraison',
    method: "Méthode d'expédition",
    noShippingMethodAddress:
      'Entrez votre adresse pour voir les méthodes de livraison disponibles.',
    noShippingMethods: "Aucune méthode d'expédition trouvée.",
    phone: 'Numéro de téléphone',
    country: 'Pays',
    selectCountry: 'Sélectionner un pays',
    searchCountry: 'Rechercher un pays...',
    noCountryFound: 'Aucun pays trouvé',
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    address1: 'Adresse',
    address2: 'Appartement, suite, etc.',
    city: 'Ville',
    region: 'État/Province',
    postalCode: 'Code postal',
    notesPlaceholder: 'Notes ou instructions spéciales',
    addressSuggestion: 'Vouliez-vous dire',
    addressSuggestionEnd: ' ?',
    noShippingOriginAddress: "Aucune adresse d'origine d'expédition fournie.",
  },
  billing: {
    title: 'Facturation',
    description: 'Description de la facturation',
  },
  payment: {
    title: 'Paiement',
    description: 'Tous les paiements sont sécurisés et chiffrés.',
    billingAddress: {
      title: 'Adresse de facturation',
      description: 'Entrez votre adresse de facturation.',
      useShippingAddress:
        "Utiliser l'adresse de livraison comme adresse de facturation",
    },
    methods: {
      creditCard: 'Carte de crédit ou de débit',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Paiements hors ligne',
      mercadopago: 'Mercado Pago',
      ccavenue: 'Payer avec CCAvenue',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      mercadopago:
        'Utilisez le formulaire MercadoPago ci-dessous pour finaliser votre achat en toute sécurité.',
      ccavenue: '',
    },
    noMethodsAvailable: 'Aucune méthode de paiement disponible',
    cardNumber: 'Numéro de carte',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: "Date d'expiration (MM / AA)",
    securityCode: 'Code de sécurité',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nom sur la carte',
    payNow: 'Payer maintenant',
    standardShipping: 'Livraison standard',
    cardDetails: 'Détails de la carte',
    payWithApplePay: 'Payer avec Apple Pay',
    expirationDatePlaceholder: 'MM / AA',
    failedToInitializePayment: "Échec de l'initialisation du paiement.",
    orderTotal: 'Total de la commande',
    subtotal: 'Sous-total',
    tax: 'Taxe',
    shipping: 'Expédition',
    discount: 'Coupon',
    processingPayment: 'Traitement du paiement...',
    completingOrder: 'Finalisation de la commande...',
    completeOrder: 'Terminer votre commande',
    freePayment: 'Terminez votre commande gratuite',
  },
  phone: {
    placeholder: '01 23 45 67 89',
    searchCountry: 'Rechercher un pays...',
    noCountryFound: 'Aucun pays trouvé.',
  },
  discounts: {
    placeholder: 'Code coupon',
    enterCode: 'Entrer le code coupon',
    apply: 'Appliquer',
    alreadyApplied: 'Ce code coupon a déjà été appliqué',
    failedToApply: "Échec de l'application du code coupon",
    enterCodeValidation: 'Veuillez entrer un code coupon',
  },
  totals: {
    subtotal: 'Sous-total',
    discount: 'Remise',
    shipping: 'Expédition',
    tip: 'Pourboire',
    estimatedTaxes: 'Taxes estimées',
    totalDue: 'Total à payer',
    orderSummary: 'Récapitulatif de la commande',
    itemCount: 'articles',
    noItems: 'Aucun article',
  },
  lineItems: {
    note: 'Note :',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Adresse',
      suggestions: 'Suggestions',
    },
    form: {
      useFormFieldError: 'useFormField doit être utilisé dans <FormField>',
    },
    pagination: {
      ariaLabel: 'pagination',
      previousPageAriaLabel: 'Aller à la page précédente',
      previous: 'Précédent',
      nextPageAriaLabel: 'Aller à la page suivante',
      next: 'Suivant',
      morePages: 'Plus de pages',
    },
    sidebar: {
      useSidebarError: 'useSidebar doit être utilisé dans un SidebarProvider.',
      toggleSidebar: 'Basculer la barre latérale',
    },
    accessibility: {
      payWithApplePay: 'Payer avec Apple Pay',
      applePayLogo: 'Logo Apple Pay',
      close: 'Fermer',
      additionalTipOptions: 'Options de pourboire supplémentaires',
      breadcrumb: "fil d'ariane",
      more: 'Plus',
      previousSlide: 'Diapositive précédente',
      nextSlide: 'Diapositive suivante',
    },
  },
  errors: {
    failedToGetAccessToken: "Échec de l'obtention du jeton d'accès",
    invalidEnvironment: 'Environnement invalide',
    noPublicAccessToken: "Aucun jeton d'accès public fourni",
    noSessionToken: 'Aucun jeton de session ou ID fourni',
    errorCreatingSession:
      'Erreur lors de la création de la session de commande :',
    orderIdRequired: "L'ID de commande est requis",
    errorTrackingEvent: "Erreur lors du suivi de l'événement",
    errorInTrackingSubscriber: "Erreur dans l'abonné de suivi",
    useTrackingProviderError:
      'useTracking doit être utilisé dans un TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect doit être utilisé dans un PoyntCollectProvider',
    useSquareProviderError:
      'useSquare doit être utilisé dans un SquareProvider',
    errorProcessingPayment: 'Erreur lors du traitement du paiement',
    stripeConfigMissing:
      'La configuration Stripe est manquante. Veuillez vérifier votre configuration.',
    paymentSuccessful: 'Paiement réussi',
    paymentFailed: 'Échec du paiement',
    paypalConfigMissing:
      'La configuration PayPal est manquante. Veuillez vérifier votre configuration.',
    stripeNotReady: "Stripe n'est pas prêt",
    cardElementNotFound: 'Élément de carte non trouvé',
    errorProcessingCardPayment:
      'Erreur lors du traitement du paiement par carte.',
    errorProcessingExpressPayment:
      'Erreur lors du traitement du paiement express.',
    failedToInitializePayment: "Échec de l'initialisation du paiement.",
    invalidPhoneNumber: 'numéro de téléphone invalide',
  },
  validation: {
    phoneRequired: 'Le numéro de téléphone est requis',
    emailRequired: 'Entrez un email',
    emailInvalid: 'Entrez un email valide',
    phoneTooLong: 'Numéro de téléphone trop long',
    invalidShippingAddress: 'Adresse de livraison invalide',
    invalidBillingAddress: 'Adresse de facturation invalide',
    selectPaymentMethod: 'Sélectionnez une méthode de paiement',
    enterValidBillingPhone:
      'Entrez un numéro de téléphone de facturation valide',
    enterValidShippingPhone:
      'Entrez un numéro de téléphone de livraison valide',
    enterFirstName: 'Entrez un prénom',
    enterLastName: 'Entrez un nom de famille',
    enterAddress: 'Entrez une adresse',
    enterCity: 'Entrez une ville',
    enterZipCode: 'Entrez un code postal',
    enterZipPostalCode: 'Entrez un code ZIP / postal',
    selectState: 'Sélectionnez un état/province',
    selectCountry: 'Sélectionnez un pays',
    enterCountry: 'Entrez un pays',
    invalidCardNumber: 'Numéro de carte invalide',
    invalidExpiry: "Date d'expiration invalide",
    invalidCvv: 'Code de sécurité invalide',
    paymentSubmissionFailed:
      'Échec de la soumission du paiement. Veuillez réessayer.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Erreur du serveur',
    SESSION_NOT_FOUND: 'Session non trouvée',
    CHECKOUT_SESSION_RETRIEVAL_FAILED:
      'Échec de la récupération de la session de paiement',
    CHECKOUT_SESSION_NOT_FOUND: 'Session de paiement non trouvée',
    CHECKOUT_SESSION_FETCH_ERROR:
      'Erreur générale lors de la récupération de la session de paiement',
    DRAFT_ORDER_NOT_FOUND: 'Commande non trouvée',
    CHECKOUT_SESSION_CREATION_FAILED:
      'Échec de la création de la session de paiement',
    CREATED_SESSION_DATA_NOT_FOUND: 'Données de session créées non trouvées',
    CHECKOUT_SESSION_CREATION_ERROR:
      'Erreur générale lors de la création de la session de paiement',
    CHECKOUT_SESSION_UPDATE_FAILED:
      'Échec de la mise à jour de la session de paiement',
    UPDATED_SESSION_NOT_FOUND: 'Session mise à jour non trouvée',
    CHECKOUT_SESSION_UPDATE_ERROR:
      'Erreur générale lors de la mise à jour de la session de paiement',
    ORDER_API_NOT_FOUND: "Source de données de l'API de commande non trouvée",
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Échec de la récupération de la commande',
    DATA_SOURCES_NOT_FOUND: 'Sources de données non trouvées',
    TRANSACTION_API_NOT_FOUND:
      "Source de données de l'API de transaction non trouvée",
    TRANSACTION_PROCESSING_FAILED: 'Échec du traitement de la transaction',
    TRANSACTION_CREATION_FAILED:
      'Échec de la recherche ou de la création de la transaction',
    ORDER_OPENING_FAILED: "Échec de l'ouverture de la commande",
    INVALID_FULFILLMENT_LOCATION: "Lieu d'exécution invalide",
    NO_VALID_PICKUP_LOCATION: 'Aucun lieu de retrait valide disponible',
    DRAFT_ORDER_FETCH_FAILED: 'Échec de la récupération de la commande',
    LINE_ITEMS_FETCH_FAILED: 'Échec de la récupération des articles',
    CURRENT_ORDER_FETCH_FAILED:
      'Échec de la récupération de la commande actuelle',
    DRAFT_ORDER_UPDATE_FAILED: 'Échec de la mise à jour de la commande',
    DISCOUNT_APPLICATION_FAILED: "Échec de l'application du coupon",
    CONTEXT_UNAVAILABLE: 'Session ou sources de données non disponibles',
    SHIPPING_LINES_UPDATE_FAILED:
      "Échec de la mise à jour des lignes d'expédition",
    ORDER_TOTALS_UPDATE_FAILED:
      'Échec de la mise à jour des totaux de la commande',
    ORDER_TOTAL_CALCULATION_FAILED: 'Échec du calcul des totaux de la commande',
    SHIPPING_METHOD_APPLICATION_FAILED:
      "Échec de l'application de la méthode d'expédition",
    SKU_FETCH_FAILED: 'Échec de la récupération des SKU',
    SHIPPING_RATES_CALCULATION_FAILED:
      "Échec du calcul des tarifs d'expédition",
    SHIPPING_METHOD_NOT_FOUND: "Méthode d'expédition non trouvée",
    SHIPPING_METHOD_REMOVAL_FAILED:
      "Échec de la suppression de la méthode d'expédition",
    SHIPPING_ADDRESS_REQUIRED: 'Adresse de livraison requise',
    INVENTORY_VALIDATION_ERROR: 'Erreur de validation des stocks',
    INSUFFICIENT_INVENTORY: 'Stock insuffisant',
    INVALID_ORDER_STATUS: 'Statut de commande invalide',
    TRANSACTION_CREATION_ERROR: 'Erreur lors de la création de la transaction',
    TRANSACTION_PROCESSING_ERROR: 'Erreur lors du traitement de la transaction',
    UNKNOWN_ERROR: 'Erreur inconnue',
    FULFILLMENT_CREATION_ERROR: "Erreur lors de la création de l'exécution",
    TAX_CALCULATION_ERROR: 'Erreur lors du calcul des taxes',
    ADDRESS_VERIFICATION_ERROR: "Erreur de vérification de l'adresse",
    ADDRESS_MATCHES_ERROR: "Erreur de correspondance d'adresse",
    SHIPPING_CONFLICT_ERROR: "Conflit d'expédition",
    SHIPPING_ERROR: "Erreur générale d'expédition",
    PRICE_ADJUSTMENT_CALCULATION_ERROR:
      "Erreur lors du calcul de l'ajustement de prix",
    ORDER_FETCH_ERROR: 'Erreur lors de la récupération de la commande',
    DRAFT_ORDER_UPDATE_ERROR: 'Erreur lors de la mise à jour de la commande',
    DISCOUNT_APPLICATION_ERROR: "Erreur lors de l'application du coupon",
    DRAFT_ORDER_OPEN_ERROR: "Erreur lors de l'ouverture de la commande",
    ORDER_UPDATE_ERROR: 'Erreur lors de la mise à jour de la commande',
    CATALOG_FETCH_ERROR: 'Erreur lors de la récupération du catalogue',
    STORE_ID_NOT_FOUND: 'ID de magasin introuvable',
    ORDER_NOT_DRAFT: "La commande n'est pas en statut valide",
    NO_LINE_ITEMS: 'Aucun article trouvé',
    BAD_USER_INPUT: 'Saisie utilisateur invalide',
    MISSING_SHIPPING_ADDRESS: 'Adresse de livraison requise',
    MISSING_REQUIRED_FIELD: 'Champ requis manquant',
    CATALOG_API_ERROR: 'Erreur du service catalogue',
    TAX_SERVICE_UNAVAILABLE: 'Service de taxes indisponible',
    SHIPPING_SERVICE_UNAVAILABLE: 'Service de livraison indisponible',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      "Service d'ajustements de prix indisponible",
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'Échec du calcul des ajustements de prix',
    SERVICE_UNAVAILABLE: 'Service temporairement indisponible',
    RATE_LIMITED: 'Trop de requêtes, veuillez réessayer plus tard',
    TIMEOUT: "Délai d'attente dépassé",
    INTERNAL_ERROR: 'Erreur interne du serveur',
    SHIPPING_POSTAL_CODE_REQUIRED: "Le code postal d'expédition est requis",
    SHIPPING_COUNTRY_CODE_REQUIRED: "Le code de pays d'expédition est requis",
    SHIPPING_METHOD_REQUIRED: "La méthode d'expédition est requise",
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      "La vérification de l'adresse d'expédition a échoué",
    BILLING_ADDRESS_VERIFICATION_FAILED:
      "La vérification de l'adresse de facturation a échoué",
    MISSING_SHIPPING_INFO:
      "L'adresse ou la méthode de livraison n'a pas pu être appliquée",
    DEPENDENCY_ERROR:
      'Nous ne pouvons pas traiter votre commande actuellement. Veuillez patienter un moment et réessayer',
  },
  storefront: {
    product: 'Produit',
    sale: 'SOLDE',
    noImage: "Pas d'image",
    noImageAvailable: 'Aucune image disponible',
    selectOptions: 'Sélectionner les options',
    adding: 'Ajout en cours...',
    addToCart: 'Ajouter au panier',
    shoppingCart: 'Panier',
    failedToLoadCart: 'Échec du chargement du panier:',
    retry: 'Réessayer',
    yourCartIsEmpty: 'Votre panier est vide',
    addItemsToGetStarted: 'Ajoutez des articles pour commencer',
    errorLoadingProducts: 'Erreur lors du chargement des produits:',
    errorLoadingProduct: 'Erreur lors du chargement du produit:',
    productNotFound: 'Produit non trouvé',
    loadingVariantDetails: 'Chargement des détails de la variante...',
    combinationNotAvailable:
      "Cette combinaison n'est pas disponible. Veuillez sélectionner d'autres options.",
    variantsMatch:
      "variantes correspondent à votre sélection. Sélectionnez plus d'attributs pour affiner.",
    quantity: 'Quantité',
    addingToCart: 'Ajout au panier...',
    outOfStock: 'Rupture de stock',
    viewDetails: 'Voir les détails',
    productType: 'Type de produit:',
    productId: 'ID du produit:',
    selectedSku: 'SKU sélectionné:',
    stockStatus: 'État du stock:',
    lowStock: 'Stock faible',
    inStock: 'En stock',
    remove: 'Supprimer',
    removing: 'Suppression...',
    checkout: 'Commander',
    itemsPerPage: 'Articles par page :',
    search: 'Rechercher',
    searchPlaceholder: 'Rechercher des produits...',
  },
};
