export const idId = {
  general: {
    optional: 'opsional',
    notes: 'Catatan',
    quantity: 'Kuantitas',
    free: 'GRATIS',
    closed: 'Tutup',
    apply: 'Terapkan',
    checkoutDisabled:
      'Checkout saat ini dinonaktifkan. Kami mohon maaf atas ketidaknyamanannya.',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Dipersembahkan oleh',
  },
  contact: {
    title: 'Kontak',
    description: '',
    email: 'Email',
  },
  pickup: {
    title: 'Ambil di Toko',
    description:
      'Segala upaya akan dilakukan untuk memenuhi waktu pengambilan yang Anda harapkan. Waktu pengambilan aktual dapat bervariasi.',
    location: 'Lokasi Pengambilan',
    date: 'Tanggal Pengambilan',
    time: 'Waktu Pengambilan Pilihan',
    selectStore: 'Pilih lokasi toko',
    selectDate: 'Pilih tanggal',
    selectTime: 'Pilih waktu pengambilan',
    storeHours: 'Jam Toko',
    seeDetails: 'Lihat detail',
    noTimeSlots:
      'Tidak ada slot waktu tersedia untuk tanggal yang dipilih. Silakan pilih tanggal lain.',
    hoursDisplayed: 'Jam ditampilkan dalam zona waktu lokal Anda.',
    storeOperatesIn: 'Toko beroperasi dalam zona waktu {timezone}.',
    asap: 'SESEGERA MUNGKIN',
    hour: 'jam',
    hours: 'jam',
    minutes: 'menit',
    searchCountry: 'Cari negara...',
    noCountryFound: 'Negara tidak ditemukan.',
  },
  days: {
    sunday: 'Minggu',
    monday: 'Senin',
    tuesday: 'Selasa',
    wednesday: 'Rabu',
    thursday: 'Kamis',
    friday: 'Jumat',
    saturday: 'Sabtu',
  },
  delivery: {
    title: 'Pengiriman',
    method: 'Metode pengiriman',
    shipping: 'Pengiriman',
    shipToAddress: 'Kirim ke alamat Anda',
    localPickup: 'Ambil di Toko',
    pickupFromStore: 'Ambil dari lokasi toko',
  },
  tips: {
    title: 'Tambahkan tip',
    noTip: 'Tanpa Tip',
    customAmount: 'Jumlah Kustom',
    customTipAmount: 'Jumlah Tip Kustom',
    placeholder: 'Rp0',
  },
  shipping: {
    title: 'Pengiriman',
    description: 'Alamat pengiriman',
    method: 'Metode pengiriman',
    noShippingMethodAddress:
      'Masukkan alamat Anda untuk melihat metode pengiriman yang tersedia.',
    noShippingMethods: 'Tidak ada metode pengiriman ditemukan.',
    phone: 'Nomor Telepon',
    country: 'Negara',
    selectCountry: 'Pilih negara',
    searchCountry: 'Cari negara...',
    noCountryFound: 'Negara tidak ditemukan',
    firstName: 'Nama Depan',
    lastName: 'Nama Belakang',
    address1: 'Alamat',
    address2: 'Apartemen, suite, dll.',
    city: 'Kota',
    region: 'Provinsi',
    postalCode: 'Kode Pos',
    notesPlaceholder: 'Catatan atau instruksi khusus',
    addressSuggestion: 'Apakah maksud Anda',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Alamat asal pengiriman tidak disediakan.',
  },
  billing: {
    title: 'Penagihan',
    description: 'Deskripsi penagihan',
  },
  payment: {
    title: 'Pembayaran',
    description: 'Semua pembayaran aman dan terenkripsi.',
    billingAddress: {
      title: 'Alamat Penagihan',
      description: 'Masukkan alamat penagihan Anda.',
      useShippingAddress: 'Gunakan alamat pengiriman sebagai alamat penagihan',
    },
    methods: {
      creditCard: 'Kartu Kredit atau Debit',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Pembayaran offline',
      ach: 'Rekening Bank',
      mercadopago: 'Mercado Pago',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      ach: '',
      mercadopago:
        'Gunakan formulir MercadoPago di bawah untuk menyelesaikan pembelian Anda dengan aman.',
    },
    noMethodsAvailable: 'Tidak ada metode pembayaran tersedia',
    cardNumber: 'Nomor kartu',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Tanggal kedaluwarsa (BB / TT)',
    securityCode: 'Kode keamanan',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nama di kartu',
    payNow: 'Bayar sekarang',
    standardShipping: 'Pengiriman Standar',
    cardDetails: 'Detail kartu',
    payWithApplePay: 'Bayar dengan Apple Pay',
    expirationDatePlaceholder: 'BB / TT',
    failedToInitializePayment: 'Gagal menginisialisasi pembayaran.',
    orderTotal: 'Total Pesanan',
    subtotal: 'Subtotal',
    tax: 'Pajak',
    shipping: 'Pengiriman',
    discount: 'Kupon',
    processingPayment: 'Memproses pembayaran...',
    completingOrder: 'Menyelesaikan pesanan...',
    completeOrder: 'Selesaikan pesanan Anda',
    freePayment: 'Selesaikan pesanan gratis Anda',
  },
  phone: {
    placeholder: '(021) 123-4567',
    searchCountry: 'Cari negara...',
    noCountryFound: 'Negara tidak ditemukan.',
  },
  discounts: {
    placeholder: 'Kode kupon',
    enterCode: 'Masukkan kode kupon',
    apply: 'Terapkan',
    alreadyApplied: 'Kode kupon ini sudah diterapkan',
    failedToApply: 'Gagal menerapkan kode kupon',
    enterCodeValidation: 'Silakan masukkan kode kupon',
  },
  totals: {
    subtotal: 'Subtotal',
    discount: 'Diskon',
    shipping: 'Pengiriman',
    tip: 'Tip',
    estimatedTaxes: 'Perkiraan pajak',
    totalDue: 'Total Pembayaran',
    orderSummary: 'Ringkasan Pesanan',
    itemCount: 'item',
    noItems: 'Tidak ada item',
  },
  lineItems: {
    note: 'Catatan:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Alamat',
      suggestions: 'Saran',
    },
    form: {
      useFormFieldError: 'useFormField harus digunakan dalam <FormField>',
    },
    pagination: {
      ariaLabel: 'paginasi',
      previousPageAriaLabel: 'Ke halaman sebelumnya',
      previous: 'Sebelumnya',
      nextPageAriaLabel: 'Ke halaman berikutnya',
      next: 'Berikutnya',
      morePages: 'Halaman lainnya',
    },
    sidebar: {
      useSidebarError: 'useSidebar harus digunakan dalam SidebarProvider.',
      toggleSidebar: 'Toggle Sidebar',
    },
    accessibility: {
      payWithApplePay: 'Bayar dengan Apple Pay',
      applePayLogo: 'Logo Apple Pay',
      close: 'Tutup',
      additionalTipOptions: 'Opsi tip tambahan',
      breadcrumb: 'navigasi breadcrumb',
      more: 'Lainnya',
      previousSlide: 'Slide sebelumnya',
      nextSlide: 'Slide berikutnya',
    },
  },
  errors: {
    failedToGetAccessToken: 'Gagal mendapatkan token akses',
    invalidEnvironment: 'Lingkungan tidak valid',
    noPublicAccessToken: 'Token akses publik tidak disediakan',
    noSessionToken: 'Token sesi atau ID tidak disediakan',
    errorCreatingSession: 'Error membuat sesi checkout:',
    orderIdRequired: 'ID pesanan diperlukan',
    errorTrackingEvent: 'Error melacak event',
    errorInTrackingSubscriber: 'Error dalam tracking subscriber',
    useTrackingProviderError:
      'useTracking harus digunakan dalam TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect harus digunakan dalam PoyntCollectProvider',
    useSquareProviderError: 'useSquare harus digunakan dalam SquareProvider',
    errorProcessingPayment: 'Error memproses pembayaran',
    stripeConfigMissing:
      'Konfigurasi Stripe tidak ada. Silakan periksa pengaturan Anda.',
    paymentSuccessful: 'Pembayaran berhasil',
    paymentFailed: 'Pembayaran gagal',
    paypalConfigMissing:
      'Konfigurasi PayPal tidak ada. Silakan periksa pengaturan Anda.',
    stripeNotReady: 'Stripe tidak siap',
    cardElementNotFound: 'CardElement tidak ditemukan',
    errorProcessingCardPayment: 'Error memproses pembayaran kartu.',
    errorProcessingExpressPayment: 'Error memproses pembayaran express.',
    failedToInitializePayment: 'Gagal menginisialisasi pembayaran.',
    invalidPhoneNumber: 'nomor telepon tidak valid',
  },
  validation: {
    phoneRequired: 'Nomor telepon diperlukan',
    emailRequired: 'Masukkan email',
    emailInvalid: 'Masukkan email yang valid',
    phoneTooLong: 'Nomor telepon terlalu panjang',
    invalidShippingAddress: 'Alamat pengiriman tidak valid',
    invalidBillingAddress: 'Alamat penagihan tidak valid',
    selectPaymentMethod: 'Pilih metode pembayaran',
    enterValidBillingPhone: 'Masukkan nomor telepon penagihan yang valid',
    enterValidShippingPhone: 'Masukkan nomor telepon pengiriman yang valid',
    enterFirstName: 'Masukkan nama depan',
    enterLastName: 'Masukkan nama belakang',
    enterAddress: 'Masukkan alamat',
    enterCity: 'Masukkan kota',
    enterZipCode: 'Masukkan kode pos',
    enterZipPostalCode: 'Masukkan kode pos',
    selectState: 'Pilih provinsi',
    selectCountry: 'Pilih negara',
    enterCountry: 'Masukkan negara',
    invalidCardNumber: 'Nomor kartu tidak valid',
    invalidExpiry: 'Tanggal kedaluwarsa tidak valid',
    invalidCvv: 'Kode keamanan tidak valid',
    paymentSubmissionFailed: 'Pengiriman pembayaran gagal. Silakan coba lagi.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Error server',
    SESSION_NOT_FOUND: 'Sesi tidak ditemukan',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Gagal mengambil sesi checkout',
    CHECKOUT_SESSION_NOT_FOUND: 'Sesi checkout tidak ditemukan',
    CHECKOUT_SESSION_FETCH_ERROR: 'Error umum mengambil sesi checkout',
    DRAFT_ORDER_NOT_FOUND: 'Pesanan tidak ditemukan',
    CHECKOUT_SESSION_CREATION_FAILED: 'Gagal membuat sesi checkout',
    CREATED_SESSION_DATA_NOT_FOUND: 'Data sesi yang dibuat tidak ditemukan',
    CHECKOUT_SESSION_CREATION_ERROR: 'Error umum pembuatan sesi checkout',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Gagal memperbarui sesi checkout',
    UPDATED_SESSION_NOT_FOUND: 'Sesi yang diperbarui tidak ditemukan',
    CHECKOUT_SESSION_UPDATE_ERROR: 'Error umum pembaruan sesi checkout',
    ORDER_API_NOT_FOUND: 'Sumber data API pesanan tidak ditemukan',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Gagal mengambil pesanan',
    DATA_SOURCES_NOT_FOUND: 'Sumber data tidak ditemukan',
    TRANSACTION_API_NOT_FOUND: 'Sumber data API transaksi tidak ditemukan',
    TRANSACTION_PROCESSING_FAILED: 'Gagal memproses transaksi',
    TRANSACTION_CREATION_FAILED: 'Gagal menemukan atau membuat transaksi',
    ORDER_OPENING_FAILED: 'Gagal membuka pesanan',
    INVALID_FULFILLMENT_LOCATION: 'Lokasi pemenuhan tidak valid',
    NO_VALID_PICKUP_LOCATION:
      'Tidak ada lokasi pengambilan yang valid tersedia',
    DRAFT_ORDER_FETCH_FAILED: 'Gagal mengambil pesanan',
    LINE_ITEMS_FETCH_FAILED: 'Gagal mengambil item pesanan',
    CURRENT_ORDER_FETCH_FAILED: 'Gagal mengambil pesanan saat ini',
    DRAFT_ORDER_UPDATE_FAILED: 'Gagal memperbarui pesanan',
    DISCOUNT_APPLICATION_FAILED: 'Gagal menerapkan kupon',
    CONTEXT_UNAVAILABLE: 'Sesi atau sumber data tidak tersedia',
    SHIPPING_LINES_UPDATE_FAILED: 'Gagal memperbarui jalur pengiriman',
    ORDER_TOTALS_UPDATE_FAILED: 'Gagal memperbarui total pesanan',
    ORDER_TOTAL_CALCULATION_FAILED: 'Gagal menghitung total pesanan',
    SHIPPING_METHOD_APPLICATION_FAILED: 'Gagal menerapkan metode pengiriman',
    SKU_FETCH_FAILED: 'Gagal mengambil SKU',
    SHIPPING_RATES_CALCULATION_FAILED: 'Gagal menghitung tarif pengiriman',
    SHIPPING_METHOD_NOT_FOUND: 'Metode pengiriman tidak ditemukan',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Gagal menghapus metode pengiriman',
    SHIPPING_ADDRESS_REQUIRED: 'Alamat pengiriman diperlukan',
    INVENTORY_VALIDATION_ERROR: 'Error validasi inventori',
    INSUFFICIENT_INVENTORY: 'Inventori tidak mencukupi',
    INVALID_ORDER_STATUS: 'Status pesanan tidak valid',
    TRANSACTION_CREATION_ERROR: 'Error pembuatan transaksi',
    TRANSACTION_PROCESSING_ERROR: 'Error pemrosesan transaksi',
    UNKNOWN_ERROR: 'Error tidak diketahui',
    FULFILLMENT_CREATION_ERROR: 'Error pembuatan pemenuhan',
    TAX_CALCULATION_ERROR: 'Error perhitungan pajak',
    ADDRESS_VERIFICATION_ERROR: 'Error verifikasi alamat',
    ADDRESS_MATCHES_ERROR: 'Error pencocokan alamat',
    SHIPPING_CONFLICT_ERROR: 'Error konflik pengiriman',
    SHIPPING_ERROR: 'Error pengiriman umum',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Error perhitungan penyesuaian harga',
    ORDER_FETCH_ERROR: 'Error mengambil pesanan',
    DRAFT_ORDER_UPDATE_ERROR: 'Error pembaruan pesanan',
    DISCOUNT_APPLICATION_ERROR: 'Error penerapan kupon',
    DRAFT_ORDER_OPEN_ERROR: 'Error membuka pesanan',
    ORDER_UPDATE_ERROR: 'Error pembaruan pesanan',
    CATALOG_FETCH_ERROR: 'Error mengambil katalog',
    STORE_ID_NOT_FOUND: 'ID toko tidak ditemukan',
    ORDER_NOT_DRAFT: 'Pesanan tidak dalam status valid',
    NO_LINE_ITEMS: 'Tidak ada item yang ditemukan',
    BAD_USER_INPUT: 'Input pengguna tidak valid',
    MISSING_SHIPPING_ADDRESS: 'Alamat pengiriman diperlukan',
    MISSING_REQUIRED_FIELD: 'Field wajib tidak ada',
    CATALOG_API_ERROR: 'Error layanan katalog',
    TAX_SERVICE_UNAVAILABLE: 'Layanan pajak tidak tersedia',
    SHIPPING_SERVICE_UNAVAILABLE: 'Layanan pengiriman tidak tersedia',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Layanan penyesuaian harga tidak tersedia',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED: 'Gagal menghitung penyesuaian harga',
    SERVICE_UNAVAILABLE: 'Layanan sementara tidak tersedia',
    RATE_LIMITED: 'Terlalu banyak permintaan, silakan coba lagi nanti',
    TIMEOUT: 'Waktu permintaan habis',
    INTERNAL_ERROR: 'Error internal server',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Kode pos pengiriman diperlukan',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Kode negara pengiriman diperlukan',
    SHIPPING_METHOD_REQUIRED: 'Metode pengiriman diperlukan',
    SHIPPING_ADDRESS_VERIFICATION_FAILED: 'Verifikasi alamat pengiriman gagal',
    BILLING_ADDRESS_VERIFICATION_FAILED: 'Verifikasi alamat penagihan gagal',
    MISSING_SHIPPING_INFO: 'Alamat atau metode pengiriman gagal diterapkan',
    DEPENDENCY_ERROR:
      'Kami tidak dapat memproses pesanan Anda saat ini. Silakan tunggu sebentar dan coba lagi',
    AUTHORIZATION_FAILED: 'Gagal mengotorisasi pembayaran',
  },
  storefront: {
    product: 'Produk',
    sale: 'OBRAL',
    noImage: 'Tidak ada gambar',
    noImageAvailable: 'Tidak ada gambar tersedia',
    selectOptions: 'Pilih opsi',
    adding: 'Menambahkan...',
    addToCart: 'Tambahkan ke keranjang',
    shoppingCart: 'Keranjang belanja',
    failedToLoadCart: 'Gagal memuat keranjang:',
    retry: 'Coba lagi',
    yourCartIsEmpty: 'Keranjang Anda kosong',
    addItemsToGetStarted: 'Tambahkan item untuk memulai',
    errorLoadingProducts: 'Error memuat produk:',
    errorLoadingProduct: 'Error memuat produk:',
    productNotFound: 'Produk tidak ditemukan',
    loadingVariantDetails: 'Memuat detail varian...',
    combinationNotAvailable:
      'Kombinasi ini tidak tersedia. Silakan pilih opsi yang berbeda.',
    variantsMatch:
      'varian cocok dengan pilihan Anda. Pilih lebih banyak atribut untuk mempersempit.',
    quantity: 'Jumlah',
    addingToCart: 'Menambahkan ke keranjang...',
    outOfStock: 'Stok habis',
    viewDetails: 'Lihat Detail',
    productType: 'Jenis Produk:',
    productId: 'ID Produk:',
    selectedSku: 'SKU yang dipilih:',
    stockStatus: 'Status Stok:',
    lowStock: 'Stok rendah',
    inStock: 'Tersedia',
    remove: 'Hapus',
    removing: 'Menghapus...',
    checkout: 'Checkout',
    itemsPerPage: 'Item per halaman:',
    search: 'Cari',
    searchPlaceholder: 'Cari produk...',
  },
};
