export const itIt = {
  general: {
    optional: 'opzionale',
    notes: 'Note',
    quantity: 'Quantità',
    free: 'GRATUITO',
    closed: 'Chiuso',
    apply: 'Applica',
    checkoutDisabled:
      "Il checkout è attualmente disabilitato. Ci scusiamo per l'inconveniente.",
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Offerto da',
  },
  contact: {
    title: 'Contatto',
    description: '',
    email: 'Email',
  },
  pickup: {
    title: 'Ritiro in Negozio',
    description:
      "Faremo ogni sforzo per rispettare l'orario di ritiro previsto. Gli orari di ritiro effettivi possono variare.",
    location: 'Punto di Ritiro',
    date: 'Data di Ritiro',
    time: 'Orario di Ritiro Preferito',
    selectStore: 'Seleziona un punto vendita',
    selectDate: 'Seleziona una data',
    selectTime: 'Seleziona un orario di ritiro',
    storeHours: 'Orari del Negozio',
    seeDetails: 'Vedi dettagli',
    noTimeSlots:
      "Nessuna fascia oraria disponibile per la data selezionata. Seleziona un'altra data.",
    hoursDisplayed: 'Orari visualizzati nel tuo fuso orario locale.',
    storeOperatesIn: 'Il negozio opera nel fuso orario {timezone}.',
    asap: 'IL PRIMA POSSIBILE',
    hour: 'ora',
    hours: 'ore',
    minutes: 'minuti',
    searchCountry: 'Cerca paese...',
    noCountryFound: 'Nessun paese trovato.',
  },
  days: {
    sunday: 'Domenica',
    monday: 'Lunedì',
    tuesday: 'Martedì',
    wednesday: 'Mercoledì',
    thursday: 'Giovedì',
    friday: 'Venerdì',
    saturday: 'Sabato',
  },
  delivery: {
    title: 'Consegna',
    method: 'Metodo di consegna',
    shipping: 'Spedizione',
    shipToAddress: 'Spedisci al tuo indirizzo',
    localPickup: 'Ritiro in Negozio',
    pickupFromStore: 'Ritira dal punto vendita',
  },
  tips: {
    title: 'Aggiungi una mancia',
    noTip: 'Nessuna Mancia',
    customAmount: 'Importo Personalizzato',
    customTipAmount: 'Importo Mancia Personalizzato',
    placeholder: '€0,00',
  },
  shipping: {
    title: 'Spedizione',
    description: 'Indirizzo di spedizione',
    method: 'Metodo di spedizione',
    noShippingMethodAddress:
      'Inserisci il tuo indirizzo per vedere i metodi di spedizione disponibili.',
    noShippingMethods: 'Nessun metodo di spedizione trovato.',
    phone: 'Numero di Telefono',
    country: 'Paese',
    selectCountry: 'Seleziona paese',
    searchCountry: 'Cerca paese...',
    noCountryFound: 'Nessun paese trovato',
    firstName: 'Nome',
    lastName: 'Cognome',
    address1: 'Indirizzo',
    address2: 'Appartamento, scala, ecc.',
    city: 'Città',
    region: 'Regione/Provincia',
    postalCode: 'Codice Postale',
    notesPlaceholder: 'Note o istruzioni speciali',
    addressSuggestion: 'Intendevi',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Nessun indirizzo di origine spedizione fornito.',
  },
  billing: {
    title: 'Fatturazione',
    description: 'Descrizione fatturazione',
  },
  payment: {
    title: 'Pagamento',
    description: 'Tutti i pagamenti sono sicuri e crittografati.',
    billingAddress: {
      title: 'Indirizzo di Fatturazione',
      description: 'Inserisci il tuo indirizzo di fatturazione.',
      useShippingAddress:
        "Usa l'indirizzo di spedizione come indirizzo di fatturazione",
    },
    methods: {
      creditCard: 'Carta di Credito o Debito',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Pagamenti offline',
      ach: 'Conto Bancario',
      mercadopago: 'Mercado Pago',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      ach: '',
      mercadopago:
        'Usa il modulo MercadoPago qui sotto per completare l’acquisto in modo sicuro.',
    },
    noMethodsAvailable: 'Nessun metodo di pagamento disponibile',
    cardNumber: 'Numero della carta',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Data di scadenza (MM / AA)',
    securityCode: 'Codice di sicurezza',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nome sulla carta',
    payNow: 'Paga ora',
    standardShipping: 'Spedizione Standard',
    cardDetails: 'Dettagli della carta',
    payWithApplePay: 'Paga con Apple Pay',
    expirationDatePlaceholder: 'MM / AA',
    failedToInitializePayment: "Errore nell'inizializzazione del pagamento.",
    orderTotal: 'Totale Ordine',
    subtotal: 'Subtotale',
    tax: 'Tasse',
    shipping: 'Spedizione',
    discount: 'Buono',
    processingPayment: 'Elaborazione pagamento...',
    completingOrder: "Completamento dell'ordine...",
    completeOrder: 'Completa il tuo ordine',
    freePayment: 'Completa il tuo ordine gratuito',
  },
  phone: {
    placeholder: '(02) 1234-5678',
    searchCountry: 'Cerca paese...',
    noCountryFound: 'Nessun paese trovato.',
  },
  discounts: {
    placeholder: 'Codice buono',
    enterCode: 'Inserisci codice buono',
    apply: 'Applica',
    alreadyApplied: 'Questo codice buono è già stato applicato',
    failedToApply: "Errore nell'applicazione del codice buono",
    enterCodeValidation: 'Inserisci un codice buono',
  },
  totals: {
    subtotal: 'Subtotale',
    discount: 'Sconto',
    shipping: 'Spedizione',
    tip: 'Mancia',
    estimatedTaxes: 'Tasse stimate',
    totalDue: 'Totale Dovuto',
    orderSummary: 'Riepilogo Ordine',
    itemCount: 'articoli',
    noItems: 'Nessun articolo',
  },
  lineItems: {
    note: 'Nota:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Indirizzo',
      suggestions: 'Suggerimenti',
    },
    form: {
      useFormFieldError:
        "useFormField deve essere usato all'interno di <FormField>",
    },
    pagination: {
      ariaLabel: 'paginazione',
      previousPageAriaLabel: 'Vai alla pagina precedente',
      previous: 'Precedente',
      nextPageAriaLabel: 'Vai alla pagina successiva',
      next: 'Successivo',
      morePages: 'Altre pagine',
    },
    sidebar: {
      useSidebarError:
        "useSidebar deve essere usato all'interno di un SidebarProvider.",
      toggleSidebar: 'Attiva/Disattiva Barra Laterale',
    },
    accessibility: {
      payWithApplePay: 'Paga con Apple Pay',
      applePayLogo: 'Logo Apple Pay',
      close: 'Chiudi',
      additionalTipOptions: 'Opzioni di mancia aggiuntive',
      breadcrumb: 'percorso di navigazione',
      more: 'Altro',
      previousSlide: 'Diapositiva precedente',
      nextSlide: 'Diapositiva successiva',
    },
  },
  errors: {
    failedToGetAccessToken: 'Errore nel recupero del token di accesso',
    invalidEnvironment: 'Ambiente non valido',
    noPublicAccessToken: 'Nessun token di accesso pubblico fornito',
    noSessionToken: 'Nessun token di sessione o ID fornito',
    errorCreatingSession: 'Errore nella creazione della sessione di checkout:',
    orderIdRequired: 'ID ordine richiesto',
    errorTrackingEvent: "Errore nel tracciamento dell'evento",
    errorInTrackingSubscriber: 'Errore nel sottoscrittore di tracciamento',
    useTrackingProviderError:
      "useTracking deve essere usato all'interno di un TrackingProvider",
    usePoyntCollectProviderError:
      "usePoyntCollect deve essere usato all'interno di un PoyntCollectProvider",
    useSquareProviderError:
      "useSquare deve essere usato all'interno di un SquareProvider",
    errorProcessingPayment: "Errore nell'elaborazione del pagamento",
    stripeConfigMissing:
      'Configurazione Stripe mancante. Controlla la tua configurazione.',
    paymentSuccessful: 'Pagamento riuscito',
    paymentFailed: 'Pagamento fallito',
    paypalConfigMissing:
      'Configurazione PayPal mancante. Controlla la tua configurazione.',
    stripeNotReady: 'Stripe non pronto',
    cardElementNotFound: 'CardElement non trovato',
    errorProcessingCardPayment:
      "Errore nell'elaborazione del pagamento con carta.",
    errorProcessingExpressPayment:
      "Errore nell'elaborazione del pagamento express.",
    failedToInitializePayment: "Errore nell'inizializzazione del pagamento.",
    invalidPhoneNumber: 'numero di telefono non valido',
  },
  validation: {
    phoneRequired: 'Numero di telefono richiesto',
    emailRequired: "Inserisci un'email",
    emailInvalid: "Inserisci un'email valida",
    phoneTooLong: 'Numero di telefono troppo lungo',
    invalidShippingAddress: 'Indirizzo di spedizione non valido',
    invalidBillingAddress: 'Indirizzo di fatturazione non valido',
    selectPaymentMethod: 'Seleziona un metodo di pagamento',
    enterValidBillingPhone:
      'Inserisci un numero di telefono di fatturazione valido',
    enterValidShippingPhone:
      'Inserisci un numero di telefono di spedizione valido',
    enterFirstName: 'Inserisci un nome',
    enterLastName: 'Inserisci un cognome',
    enterAddress: 'Inserisci un indirizzo',
    enterCity: 'Inserisci una città',
    enterZipCode: 'Inserisci un codice postale',
    enterZipPostalCode: 'Inserisci un codice postale',
    selectState: 'Seleziona una regione/provincia',
    selectCountry: 'Seleziona un paese',
    enterCountry: 'Inserisci un paese',
    invalidCardNumber: 'Numero di carta non valido',
    invalidExpiry: 'Data di scadenza non valida',
    invalidCvv: 'Codice di sicurezza non valido',
    paymentSubmissionFailed: 'Invio del pagamento non riuscito. Riprova.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Errore del server',
    SESSION_NOT_FOUND: 'Sessione non trovata',
    CHECKOUT_SESSION_RETRIEVAL_FAILED:
      'Errore nel recupero della sessione di checkout',
    CHECKOUT_SESSION_NOT_FOUND: 'Sessione di checkout non trovata',
    CHECKOUT_SESSION_FETCH_ERROR:
      'Errore generale nel recupero della sessione di checkout',
    DRAFT_ORDER_NOT_FOUND: 'Ordine non trovato',
    CHECKOUT_SESSION_CREATION_FAILED:
      'Errore nella creazione della sessione di checkout',
    CREATED_SESSION_DATA_NOT_FOUND: 'Dati della sessione creata non trovati',
    CHECKOUT_SESSION_CREATION_ERROR:
      'Errore generale nella creazione della sessione di checkout',
    CHECKOUT_SESSION_UPDATE_FAILED:
      "Errore nell'aggiornamento della sessione di checkout",
    UPDATED_SESSION_NOT_FOUND: 'Sessione aggiornata non trovata',
    CHECKOUT_SESSION_UPDATE_ERROR:
      "Errore generale nell'aggiornamento della sessione di checkout",
    ORDER_API_NOT_FOUND: 'Fonte dati API ordini non trovata',
    DRAFT_ORDER_RETRIEVAL_FAILED: "Errore nel recupero dell'ordine",
    DATA_SOURCES_NOT_FOUND: 'Fonti dati non trovate',
    TRANSACTION_API_NOT_FOUND: 'Fonte dati API transazioni non trovata',
    TRANSACTION_PROCESSING_FAILED: "Errore nell'elaborazione della transazione",
    TRANSACTION_CREATION_FAILED:
      'Errore nella ricerca o creazione della transazione',
    ORDER_OPENING_FAILED: "Errore nell'apertura dell'ordine",
    INVALID_FULFILLMENT_LOCATION: 'Posizione di evasione non valida',
    NO_VALID_PICKUP_LOCATION: 'Nessuna posizione di ritiro valida disponibile',
    DRAFT_ORDER_FETCH_FAILED: "Errore nel recupero dell'ordine",
    LINE_ITEMS_FETCH_FAILED: 'Errore nel recupero degli articoli',
    CURRENT_ORDER_FETCH_FAILED: "Errore nel recupero dell'ordine corrente",
    DRAFT_ORDER_UPDATE_FAILED: "Errore nell'aggiornamento dell'ordine",
    DISCOUNT_APPLICATION_FAILED: "Errore nell'applicazione del buono",
    CONTEXT_UNAVAILABLE: 'Sessione o fonti dati non disponibili',
    SHIPPING_LINES_UPDATE_FAILED:
      "Errore nell'aggiornamento delle linee di spedizione",
    ORDER_TOTALS_UPDATE_FAILED:
      "Errore nell'aggiornamento dei totali dell'ordine",
    ORDER_TOTAL_CALCULATION_FAILED: "Errore nel calcolo dei totali dell'ordine",
    SHIPPING_METHOD_APPLICATION_FAILED:
      "Errore nell'applicazione del metodo di spedizione",
    SKU_FETCH_FAILED: 'Errore nel recupero degli SKU',
    SHIPPING_RATES_CALCULATION_FAILED:
      'Errore nel calcolo delle tariffe di spedizione',
    SHIPPING_METHOD_NOT_FOUND: 'Metodo di spedizione non trovato',
    SHIPPING_METHOD_REMOVAL_FAILED:
      'Errore nella rimozione del metodo di spedizione',
    SHIPPING_ADDRESS_REQUIRED: 'Indirizzo di spedizione richiesto',
    INVENTORY_VALIDATION_ERROR: 'Errore di validazione inventario',
    INSUFFICIENT_INVENTORY: 'Inventario insufficiente',
    INVALID_ORDER_STATUS: 'Stato ordine non valido',
    TRANSACTION_CREATION_ERROR: 'Errore nella creazione della transazione',
    TRANSACTION_PROCESSING_ERROR: "Errore nell'elaborazione della transazione",
    UNKNOWN_ERROR: 'Errore sconosciuto',
    FULFILLMENT_CREATION_ERROR: "Errore nella creazione dell'evasione",
    TAX_CALCULATION_ERROR: 'Errore nel calcolo delle tasse',
    ADDRESS_VERIFICATION_ERROR: "Errore nella verifica dell'indirizzo",
    ADDRESS_MATCHES_ERROR: "Errore nelle corrispondenze dell'indirizzo",
    SHIPPING_CONFLICT_ERROR: 'Errore di conflitto nella spedizione',
    SHIPPING_ERROR: 'Errore generale di spedizione',
    PRICE_ADJUSTMENT_CALCULATION_ERROR:
      "Errore nel calcolo dell'aggiustamento prezzo",
    ORDER_FETCH_ERROR: "Errore nel recupero dell'ordine",
    DRAFT_ORDER_UPDATE_ERROR: "Errore nell'aggiornamento dell'ordine",
    DISCOUNT_APPLICATION_ERROR: "Errore nell'applicazione del buono",
    DRAFT_ORDER_OPEN_ERROR: "Errore nell'apertura dell'ordine",
    ORDER_UPDATE_ERROR: "Errore nell'aggiornamento dell'ordine",
    CATALOG_FETCH_ERROR: 'Errore nel recupero del catalogo',
    STORE_ID_NOT_FOUND: 'ID negozio non trovato',
    ORDER_NOT_DRAFT: "L'ordine non è in stato valido",
    NO_LINE_ITEMS: 'Nessun articolo trovato',
    BAD_USER_INPUT: 'Input utente non valido',
    MISSING_SHIPPING_ADDRESS: 'Indirizzo di spedizione richiesto',
    MISSING_REQUIRED_FIELD: 'Campo obbligatorio mancante',
    CATALOG_API_ERROR: 'Errore del servizio catalogo',
    TAX_SERVICE_UNAVAILABLE: 'Servizio tasse non disponibile',
    SHIPPING_SERVICE_UNAVAILABLE: 'Servizio di spedizione non disponibile',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Servizio di aggiustamento prezzi non disponibile',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'Errore nel calcolo degli aggiustamenti prezzi',
    SERVICE_UNAVAILABLE: 'Servizio temporaneamente non disponibile',
    RATE_LIMITED: 'Troppe richieste, riprovare più tardi',
    TIMEOUT: 'Timeout della richiesta',
    INTERNAL_ERROR: 'Errore interno del server',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Codice postale di spedizione obbligatorio',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Codice paese di spedizione obbligatorio',
    SHIPPING_METHOD_REQUIRED: 'Metodo di spedizione obbligatorio',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      'Verifica indirizzo di spedizione fallita',
    BILLING_ADDRESS_VERIFICATION_FAILED:
      'Verifica indirizzo di fatturazione fallita',
    MISSING_SHIPPING_INFO:
      "Impossibile applicare l'indirizzo o il metodo di spedizione",
    DEPENDENCY_ERROR:
      'Non riusciamo a elaborare il tuo ordine in questo momento. Aspetta un momento e riprova',
    AUTHORIZATION_FAILED: "Errore nell'autorizzazione del pagamento",
  },
  storefront: {
    product: 'Prodotto',
    sale: 'SALDO',
    noImage: 'Nessuna immagine',
    noImageAvailable: 'Nessuna immagine disponibile',
    selectOptions: 'Seleziona opzioni',
    adding: 'Aggiunta in corso...',
    addToCart: 'Aggiungi al carrello',
    shoppingCart: 'Carrello',
    failedToLoadCart: 'Caricamento carrello non riuscito:',
    retry: 'Riprova',
    yourCartIsEmpty: 'Il tuo carrello è vuoto',
    addItemsToGetStarted: 'Aggiungi articoli per iniziare',
    errorLoadingProducts: 'Errore nel caricamento dei prodotti:',
    errorLoadingProduct: 'Errore nel caricamento del prodotto:',
    productNotFound: 'Prodotto non trovato',
    loadingVariantDetails: 'Caricamento dei dettagli della variante...',
    combinationNotAvailable:
      'Questa combinazione non è disponibile. Si prega di selezionare opzioni diverse.',
    variantsMatch:
      'varianti corrispondono alla tua selezione. Seleziona più attributi per restringere.',
    quantity: 'Quantità',
    addingToCart: 'Aggiunta al carrello...',
    outOfStock: 'Esaurito',
    viewDetails: 'Vedi dettagli',
    productType: 'Tipo di prodotto:',
    productId: 'ID prodotto:',
    selectedSku: 'SKU selezionato:',
    stockStatus: 'Stato delle scorte:',
    lowStock: 'Scorte limitate',
    inStock: 'Disponibile',
    remove: 'Rimuovi',
    removing: 'Rimozione...',
    checkout: 'Acquista',
    itemsPerPage: 'Articoli per pagina:',
    search: 'Cerca',
    searchPlaceholder: 'Cerca prodotti...',
  },
};
