export const ptBr = {
  general: {
    optional: 'opcional',
    notes: 'Observações',
    quantity: 'Quantidade',
    free: 'GRÁTIS',
    closed: 'Fechado',
    apply: 'Aplicar',
    checkoutDisabled:
      'O checkout está temporariamente indisponível. Pedimos desculpas pelo inconveniente.',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Desenvolvido por',
  },
  contact: {
    title: 'Contato',
    description: '',
    email: 'E-mail',
  },
  pickup: {
    title: 'Retirada no Local',
    description:
      'Faremos todos os esforços para atender o horário de retirada esperado. Os horários reais de retirada podem variar.',
    location: 'Local de Retirada',
    date: 'Data de Retirada',
    time: 'Horário Preferido de Retirada',
    selectStore: 'Selecione uma loja',
    selectDate: 'Selecione uma data',
    selectTime: 'Selecione um horário de retirada',
    storeHours: 'Horário de Funcionamento',
    seeDetails: 'Ver detalhes',
    noTimeSlots:
      'Nenhum horário disponível para a data selecionada. Por favor, selecione outra data.',
    hoursDisplayed: 'Horários exibidos no seu fuso horário local.',
    storeOperatesIn: 'A loja funciona no fuso horário {timezone}.',
    asap: 'O MAIS RÁPIDO POSSÍVEL',
    hour: 'hora',
    hours: 'horas',
    minutes: 'minutos',
    searchCountry: 'Buscar país...',
    noCountryFound: 'Nenhum país encontrado.',
  },
  days: {
    sunday: 'Domingo',
    monday: 'Segunda-feira',
    tuesday: 'Terça-feira',
    wednesday: 'Quarta-feira',
    thursday: 'Quinta-feira',
    friday: 'Sexta-feira',
    saturday: 'Sábado',
  },
  delivery: {
    title: 'Entrega',
    method: 'Método de entrega',
    shipping: 'Envio',
    shipToAddress: 'Enviar para seu endereço',
    localPickup: 'Retirada no Local',
    pickupFromStore: 'Retirar na loja',
  },
  tips: {
    title: 'Adicionar gorjeta',
    noTip: 'Sem Gorjeta',
    customAmount: 'Valor Personalizado',
    customTipAmount: 'Valor da Gorjeta Personalizada',
    placeholder: 'R$ 0,00',
  },
  shipping: {
    title: 'Envio',
    description: 'Endereço de entrega',
    method: 'Método de envio',
    noShippingMethodAddress:
      'Digite seu endereço para ver os métodos de envio disponíveis.',
    noShippingMethods: 'Nenhum método de envio encontrado.',
    phone: 'Número de Telefone',
    country: 'País',
    selectCountry: 'Selecionar país',
    searchCountry: 'Buscar país...',
    noCountryFound: 'Nenhum país encontrado',
    firstName: 'Nome',
    lastName: 'Sobrenome',
    address1: 'Endereço',
    address2: 'Complemento (opcional)',
    city: 'Cidade',
    region: 'Estado',
    postalCode: 'CEP',
    notesPlaceholder: 'Observações ou instruções especiais',
    addressSuggestion: 'Você quis dizer',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Endereço de origem de envio não fornecido.',
  },
  billing: {
    title: 'Cobrança',
    description: 'Descrição da cobrança',
  },
  payment: {
    title: 'Pagamento',
    description: 'Todos os pagamentos são seguros e criptografados.',
    billingAddress: {
      title: 'Endereço de Cobrança',
      description: 'Digite seu endereço de cobrança.',
      useShippingAddress: 'Usar endereço de entrega como endereço de cobrança',
    },
    methods: {
      creditCard: 'Cartão de Crédito ou Débito',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Pagamentos offline',
      ach: 'Conta Bancária',
      mercadopago: 'Mercado Pago',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      ach: '',
      mercadopago:
        'Use o formulário do MercadoPago abaixo para concluir sua compra com segurança.',
    },
    noMethodsAvailable: 'Nenhum método de pagamento disponível',
    cardNumber: 'Número do cartão',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Data de validade (MM / AA)',
    securityCode: 'Código de segurança',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Nome no cartão',
    payNow: 'Pagar agora',
    standardShipping: 'Envio Padrão',
    cardDetails: 'Dados do cartão',
    payWithApplePay: 'Pagar com Apple Pay',
    expirationDatePlaceholder: 'MM / AA',
    failedToInitializePayment: 'Falha ao inicializar pagamento.',
    orderTotal: 'Total do Pedido',
    subtotal: 'Subtotal',
    tax: 'Impostos',
    shipping: 'Envio',
    discount: 'Cupom',
    processingPayment: 'Processando pagamento...',
    completingOrder: 'Concluindo pedido...',
    completeOrder: 'Concluir seu pedido',
    freePayment: 'Complete seu pedido gratuito',
  },
  phone: {
    placeholder: '(11) 99999-9999',
    searchCountry: 'Buscar país...',
    noCountryFound: 'Nenhum país encontrado.',
  },
  discounts: {
    placeholder: 'Código de cupom',
    enterCode: 'Digite o código de cupom',
    apply: 'Aplicar',
    alreadyApplied: 'Este código de cupom já foi aplicado',
    failedToApply: 'Falha ao aplicar código de cupom',
    enterCodeValidation: 'Por favor, digite um código de cupom',
  },
  totals: {
    subtotal: 'Subtotal',
    discount: 'Desconto',
    shipping: 'Envio',
    tip: 'Gorjeta',
    estimatedTaxes: 'Impostos estimados',
    totalDue: 'Total a Pagar',
    orderSummary: 'Resumo do Pedido',
    itemCount: 'itens',
    noItems: 'Nenhum item',
  },
  lineItems: {
    note: 'Observação:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Endereço',
      suggestions: 'Sugestões',
    },
    form: {
      useFormFieldError: 'useFormField deve ser usado dentro de <FormField>',
    },
    pagination: {
      ariaLabel: 'paginação',
      previousPageAriaLabel: 'Ir para página anterior',
      previous: 'Anterior',
      nextPageAriaLabel: 'Ir para próxima página',
      next: 'Próximo',
      morePages: 'Mais páginas',
    },
    sidebar: {
      useSidebarError:
        'useSidebar deve ser usado dentro de um SidebarProvider.',
      toggleSidebar: 'Alternar Barra Lateral',
    },
    accessibility: {
      payWithApplePay: 'Pagar com Apple Pay',
      applePayLogo: 'Logo do Apple Pay',
      close: 'Fechar',
      additionalTipOptions: 'Opções de gorjeta adicionais',
      breadcrumb: 'navegação estrutural',
      more: 'Mais',
      previousSlide: 'Slide anterior',
      nextSlide: 'Próximo slide',
    },
  },
  errors: {
    failedToGetAccessToken: 'Falha ao obter token de acesso',
    invalidEnvironment: 'Ambiente inválido',
    noPublicAccessToken: 'Nenhum token de acesso público fornecido',
    noSessionToken: 'Nenhum token de sessão ou ID fornecido',
    errorCreatingSession: 'Erro ao criar sessão de checkout:',
    orderIdRequired: 'ID do pedido é obrigatório',
    errorTrackingEvent: 'Erro ao rastrear evento',
    errorInTrackingSubscriber: 'Erro no assinante de rastreamento',
    useTrackingProviderError:
      'useTracking deve ser usado dentro de um TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect deve ser usado dentro de um PoyntCollectProvider',
    useSquareProviderError:
      'useSquare deve ser usado dentro de um SquareProvider',
    errorProcessingPayment: 'Erro ao processar pagamento',
    stripeConfigMissing:
      'Configuração do Stripe está faltando. Por favor, verifique sua configuração.',
    paymentSuccessful: 'Pagamento realizado com sucesso',
    paymentFailed: 'Falha no pagamento',
    paypalConfigMissing:
      'Configuração do PayPal está faltando. Por favor, verifique sua configuração.',
    stripeNotReady: 'Stripe não está pronto',
    cardElementNotFound: 'CardElement não encontrado',
    errorProcessingCardPayment: 'Erro ao processar pagamento com cartão.',
    errorProcessingExpressPayment: 'Erro ao processar pagamento expresso.',
    failedToInitializePayment: 'Falha ao inicializar pagamento.',
    invalidPhoneNumber: 'número de telefone inválido',
  },
  validation: {
    phoneRequired: 'Número de telefone é obrigatório',
    emailRequired: 'Digite um e-mail',
    emailInvalid: 'Digite um e-mail válido',
    phoneTooLong: 'Número de telefone muito longo',
    invalidShippingAddress: 'Endereço de entrega inválido',
    invalidBillingAddress: 'Endereço de cobrança inválido',
    selectPaymentMethod: 'Selecione um método de pagamento',
    enterValidBillingPhone: 'Digite um número de telefone de cobrança válido',
    enterValidShippingPhone: 'Digite um número de telefone de entrega válido',
    enterFirstName: 'Digite o nome',
    enterLastName: 'Digite o sobrenome',
    enterAddress: 'Digite um endereço',
    enterCity: 'Digite uma cidade',
    enterZipCode: 'Digite um CEP',
    enterZipPostalCode: 'Digite um CEP',
    selectState: 'Selecione um estado/província',
    selectCountry: 'Selecione um país',
    enterCountry: 'Digite um país',
    invalidCardNumber: 'Número de cartão inválido',
    invalidExpiry: 'Data de validade inválida',
    invalidCvv: 'Código de segurança inválido',
    paymentSubmissionFailed:
      'Falha no envio do pagamento. Por favor, tente novamente.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Erro no servidor',
    SESSION_NOT_FOUND: 'Sessão não encontrada',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Falha ao recuperar sessão de checkout',
    CHECKOUT_SESSION_NOT_FOUND: 'Sessão de checkout não encontrada',
    CHECKOUT_SESSION_FETCH_ERROR: 'Erro geral ao buscar sessão de checkout',
    DRAFT_ORDER_NOT_FOUND: 'Pedido não encontrado',
    CHECKOUT_SESSION_CREATION_FAILED: 'Falha ao criar sessão de checkout',
    CREATED_SESSION_DATA_NOT_FOUND: 'Dados da sessão criada não encontrados',
    CHECKOUT_SESSION_CREATION_ERROR: 'Erro geral ao criar sessão de checkout',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Falha ao atualizar sessão de checkout',
    UPDATED_SESSION_NOT_FOUND: 'Sessão atualizada não encontrada',
    CHECKOUT_SESSION_UPDATE_ERROR: 'Erro geral ao atualizar sessão de checkout',
    ORDER_API_NOT_FOUND: 'Fonte de dados da API de pedidos não encontrada',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Falha ao recuperar pedido',
    DATA_SOURCES_NOT_FOUND: 'Fontes de dados não encontradas',
    TRANSACTION_API_NOT_FOUND:
      'Fonte de dados da API de transação não encontrada',
    TRANSACTION_PROCESSING_FAILED: 'Falha ao processar transação',
    TRANSACTION_CREATION_FAILED: 'Falha ao encontrar ou criar transação',
    ORDER_OPENING_FAILED: 'Falha ao abrir pedido',
    INVALID_FULFILLMENT_LOCATION: 'Local de atendimento inválido',
    NO_VALID_PICKUP_LOCATION: 'Nenhum local de retirada válido disponível',
    DRAFT_ORDER_FETCH_FAILED: 'Falha ao buscar pedido',
    LINE_ITEMS_FETCH_FAILED: 'Falha ao buscar itens de linha',
    CURRENT_ORDER_FETCH_FAILED: 'Falha ao buscar pedido atual',
    DRAFT_ORDER_UPDATE_FAILED: 'Falha ao atualizar pedido',
    DISCOUNT_APPLICATION_FAILED: 'Falha ao aplicar cupom',
    CONTEXT_UNAVAILABLE: 'Sessão ou fontes de dados não disponíveis',
    SHIPPING_LINES_UPDATE_FAILED: 'Falha ao atualizar linhas de envio',
    ORDER_TOTALS_UPDATE_FAILED: 'Falha ao atualizar totais do pedido',
    ORDER_TOTAL_CALCULATION_FAILED: 'Falha ao calcular totais do pedido',
    SHIPPING_METHOD_APPLICATION_FAILED: 'Falha ao aplicar método de envio',
    SKU_FETCH_FAILED: 'Falha ao buscar SKUs',
    SHIPPING_RATES_CALCULATION_FAILED: 'Falha ao calcular taxas de envio',
    SHIPPING_METHOD_NOT_FOUND: 'Método de envio não encontrado',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Falha ao remover método de envio',
    SHIPPING_ADDRESS_REQUIRED: 'Endereço de envio obrigatório',
    INVENTORY_VALIDATION_ERROR: 'Erro de validação de estoque',
    INSUFFICIENT_INVENTORY: 'Estoque insuficiente',
    INVALID_ORDER_STATUS: 'Status do pedido inválido',
    TRANSACTION_CREATION_ERROR: 'Erro na criação da transação',
    TRANSACTION_PROCESSING_ERROR: 'Erro no processamento da transação',
    UNKNOWN_ERROR: 'Erro desconhecido',
    FULFILLMENT_CREATION_ERROR: 'Erro na criação do atendimento',
    TAX_CALCULATION_ERROR: 'Erro no cálculo de impostos',
    ADDRESS_VERIFICATION_ERROR: 'Erro na verificação de endereço',
    ADDRESS_MATCHES_ERROR: 'Erro na correspondência de endereços',
    SHIPPING_CONFLICT_ERROR: 'Erro de conflito de envio',
    SHIPPING_ERROR: 'Erro geral de envio',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Erro no cálculo de ajuste de preço',
    ORDER_FETCH_ERROR: 'Erro ao buscar pedido',
    DRAFT_ORDER_UPDATE_ERROR: 'Erro ao atualizar pedido',
    DISCOUNT_APPLICATION_ERROR: 'Erro na aplicação de cupom',
    DRAFT_ORDER_OPEN_ERROR: 'Erro ao abrir pedido',
    ORDER_UPDATE_ERROR: 'Erro ao atualizar pedido',
    CATALOG_FETCH_ERROR: 'Erro ao buscar catálogo',
    STORE_ID_NOT_FOUND: 'ID da loja não encontrado',
    ORDER_NOT_DRAFT: 'O pedido não está em status válido',
    NO_LINE_ITEMS: 'Nenhum item encontrado',
    BAD_USER_INPUT: 'Entrada de usuário inválida',
    MISSING_SHIPPING_ADDRESS: 'Endereço de entrega obrigatório',
    MISSING_REQUIRED_FIELD: 'Campo obrigatório ausente',
    CATALOG_API_ERROR: 'Erro do serviço de catálogo',
    TAX_SERVICE_UNAVAILABLE: 'Serviço de impostos indisponível',
    SHIPPING_SERVICE_UNAVAILABLE: 'Serviço de envio indisponível',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Serviço de ajustes de preço indisponível',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      'Falha no cálculo de ajustes de preço',
    SERVICE_UNAVAILABLE: 'Serviço temporariamente indisponível',
    RATE_LIMITED: 'Muitas solicitações, tente novamente mais tarde',
    TIMEOUT: 'Tempo limite da solicitação esgotado',
    INTERNAL_ERROR: 'Erro interno do servidor',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Código postal de envio é obrigatório',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Código do país de envio é obrigatório',
    SHIPPING_METHOD_REQUIRED: 'Método de envio é obrigatório',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      'Falha na verificação do endereço de envio',
    BILLING_ADDRESS_VERIFICATION_FAILED:
      'Falha na verificação do endereço de cobrança',
    MISSING_SHIPPING_INFO: 'Falha ao aplicar endereço ou método de entrega',
    DEPENDENCY_ERROR:
      'Não conseguimos processar seu pedido no momento. Aguarde um momento e tente novamente',
    AUTHORIZATION_FAILED: 'Falha ao autorizar pagamento',
  },
  storefront: {
    product: 'Produto',
    sale: 'PROMOÇÃO',
    noImage: 'Sem imagem',
    noImageAvailable: 'Nenhuma imagem disponível',
    selectOptions: 'Selecionar opções',
    adding: 'Adicionando...',
    addToCart: 'Adicionar ao carrinho',
    shoppingCart: 'Carrinho de compras',
    failedToLoadCart: 'Falha ao carregar carrinho:',
    retry: 'Tentar novamente',
    yourCartIsEmpty: 'Seu carrinho está vazio',
    addItemsToGetStarted: 'Adicione itens para começar',
    errorLoadingProducts: 'Erro ao carregar produtos:',
    errorLoadingProduct: 'Erro ao carregar produto:',
    productNotFound: 'Produto não encontrado',
    loadingVariantDetails: 'Carregando detalhes da variante...',
    combinationNotAvailable:
      'Esta combinação não está disponível. Por favor, selecione opções diferentes.',
    variantsMatch:
      'variantes correspondem à sua seleção. Selecione mais atributos para refinar.',
    quantity: 'Quantidade',
    addingToCart: 'Adicionando ao carrinho...',
    outOfStock: 'Fora de estoque',
    viewDetails: 'Ver detalhes',
    productType: 'Tipo de produto:',
    productId: 'ID do produto:',
    selectedSku: 'SKU selecionado:',
    stockStatus: 'Status do estoque:',
    lowStock: 'Estoque baixo',
    inStock: 'Em estoque',
    remove: 'Remover',
    removing: 'Removendo...',
    checkout: 'Finalizar compra',
    itemsPerPage: 'Itens por página:',
    search: 'Pesquisar',
    searchPlaceholder: 'Pesquisar produtos...',
  },
};
