export const qaPs = {
  general: {
    optional: '[óþťîöñâl]',
    notes: '[Ñöťéš]',
    quantity: '[Qüâñťîťÿ]',
    free: '[FRËË]',
    closed: '[Çlöšéd]',
    apply: '[Âþþlÿ]',
    checkoutDisabled:
      '[Çhéçkøüť îš çürrëñťlÿ dîšâblëd. Wé âþöløgîžé før ťhé îñçöñvéñîéñçé ând áppreciate your patience.]',
    godaddyCheckout: '[GôDâddÿ Çhéçkøüť]',
    poweredBy: '[Pöwéréd bÿ]',
  },
  contact: {
    title: '[Çöñťâçť]',
    description: '',
    email: '[Émâîl Âddrëšš]',
  },
  pickup: {
    title: '[Löçâl Þîçküþ Šërvîçë]',
    description:
      '[Âll éffôrťš wîll bé mâdé ťö mëëť ÿöür ëxþëçťëd þîçküþ ťîmé. Âçťüâl þîçküþ ťîmëš mâÿ vârÿ dëþëñdîñg öñ çîrçümšťâñçëš.]',
    location: '[Þîçküþ Löçâťîöñ Âddrëšš]',
    date: '[Þîçküþ Dâťé]',
    time: '[Þrëfërrëd Þîçküþ Ťîmé]',
    selectStore: '[Šëlëçť â šťörë löçâťîöñ frôm ťhé lîšť]',
    selectDate: '[Šëlëçť â dâťé frôm çâlëñdâr]',
    selectTime: '[Šëlëçť â þîçküþ ťîmé šlöť]',
    storeHours: '[Šťörë Hôürš Îñförmâťîöñ]',
    seeDetails: '[Šëë mörë dëťâîlš]',
    noTimeSlots:
      '[Ñö âvâîlâblë ťîmé šlöťš fôr ťhé šëlëçťëd dâťé. Þlëâšé šëlëçť âñöťhër dâťé ôr çöñšîdër öťhër öþťîöñš.]',
    hoursDisplayed: '[Hôürš dîšþlâÿëd îñ ÿöür löçâl ťîmëžöñë fôr çöñvëñîëñçë.]',
    storeOperatesIn: '[Šťörë öþërâťëš îñ {timezone} ťîmëžöñë förmâť.]',
    asap: '[ÂŠÂ̈P]',
    hour: '[hôür]',
    hours: '[hôürš]',
    minutes: '[mîñüťëš]',
    searchCountry: '[Šëârçh çöüñťrÿ bÿ ñâmë...]',
    noCountryFound: '[Ñö çöüñťrÿ föüñd îñ šëârçh.]',
  },
  days: {
    sunday: '[Šüñdâÿ]',
    monday: '[Möñdâÿ]',
    tuesday: '[Ťüëšdâÿ]',
    wednesday: '[Wëdñëšdâÿ]',
    thursday: '[Ťhürškâÿ]',
    friday: '[Frîdâÿ]',
    saturday: '[Šâťürdâÿ]',
  },
  delivery: {
    title: '[Délîvërÿ Mëťhödš]',
    method: '[Délîvërÿ mëťhöd šëlëçťîöñ]',
    shipping: '[Šhîþþîñg Öþťîöñš]',
    shipToAddress: '[Šhîþ ťö ÿöür šþëçîfîëd âddrëšš]',
    localPickup: '[Löçâl Þîçküþ Šërvîçë]',
    pickupFromStore: '[Þîçk üþ frôm šťörë löçâťîöñ]',
  },
  tips: {
    title: '[Âdd â ťîþ fôr šërvîçë]',
    noTip: '[Ñö Ťîþ Âddëd]',
    customAmount: '[Çüšťöm Âmöüñť Ëñťrÿ]',
    customTipAmount: '[Çüšťöm Ťîþ Âmöüñť Vâlüë]',
    placeholder: '[$0.00]',
  },
  shipping: {
    title: '[Šhîþþîñg Îñförmâťîöñ]',
    description: '[Šhîþþîñg âddrëšš dëťâîlš]',
    method: '[Šhîþþîñg mëťhöd šëlëçťîöñ]',
    noShippingMethodAddress:
      '[Ëñťër ÿöür âddrëšš ťö šëë âvâîlâblë šhîþþîñg mëťhödš fôr ÿöür löçâťîöñ.]',
    noShippingMethods: '[Ñö šhîþþîñg mëťhödš föüñd fôr ţhîš löçâţîöñ.]',
    phone: '[Þhöñë Ñümkër Îñförmâťîöñ]',
    country: '[Çöüñţrÿ Šëlëçťîöñ]',
    selectCountry: '[Šëlëçť çöüñţrÿ frôm lîšť]',
    searchCountry: '[Šëârçh çöüñţrÿ bÿ ñâmë...]',
    noCountryFound: '[Ñö çöüñţrÿ föüñd îñ šëârçh]',
    firstName: '[Fîršť Ñâmë Îñþüť]',
    lastName: '[Lâšť Ñâmë Îñþüť]',
    address1: '[Âddrëšš Lîñë Önë]',
    address2: '[Âþârţmëñť, šüîţë, ëţç. (öþţîöñâl îñþüť)]',
    city: '[Çîţÿ Ñâmë]',
    region: '[Šţâţë/Þrövîñçë Šëlëçţîöñ]',
    postalCode: '[Þöšţâl Çödë Îñþüť]',
    notesPlaceholder: '[Ñöţëš ör šþëçîâl îñšţrüçţîöñš fôr délîvërÿ]',
    addressSuggestion: '[Dîd ÿöü mëâñ ţhîš âddrëšš]',
    addressSuggestionEnd: '[?]',
    noShippingOriginAddress:
      '[Ñö šhîþþîñg örîgîñ âddrëšš þrövîdëd bÿ mërçhâñť.]',
  },
  billing: {
    title: '[Bîllîñg Îñförmâţîöñ]',
    description: '[Bîllîñg îñförmâţîöñ dëšçrîþţîöñ]',
  },
  payment: {
    title: '[Þâÿmëñţ Îñförmâţîöñ]',
    description: '[Âll þâÿmëñţš ârë šëçürë ând ëñçrÿþţëd för ÿöür šâfëţÿ.]',
    billingAddress: {
      title: '[Bîllîñg Âddrëšš Îñförmâţîöñ]',
      description: '[Ëñţër ÿöür bîllîñg âddrëšš dëţâîlš.]',
      useShippingAddress: '[Üšë šhîþþîñg âddrëšš âš bîllîñg âddrëšš]',
    },
    methods: {
      creditCard: '[Çrëdîţ ör Dëbîţ Çârd Þâÿmëñţ]',
      paypal: '[ÞâÿÞâl Þâÿmëñţ Šërvîçë]',
      applePay: '[Âþþlë Þâÿ Þâÿmëñţ]',
      googlePay: '[Göögië Þâÿ Þâÿmëñţ]',
      paze: '[Þâžë Þâÿmëñţ Šërvîçë]',
      offline: '[Öfflîñë þâÿmëñţ mëţhödš]',
      mercadopago: 'Mercado Pago',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      mercadopago:
        '[Üšë ţhë MërçâðöÞâgö förm këlöw ţö çömþlëţë ÿöür þürçhâšë šëçürëlÿ.]',
    },
    noMethodsAvailable: '[Ñö þâÿmëñţ mëţhödš âvâîlâblë âţ ţhîš ţîmë]',
    cardNumber: '[Çârd ñümkër îñþüţ fîëld]',
    cardNumberPlaceholder: '[1234 1234 1234 1234]',
    expirationDate: '[Ëxþîrâţîöñ dâţë (MM / ÿÿ förmâţ)]',
    securityCode: '[Šëçürîţÿ çödë vërîfîçâţîöñ]',
    cvvPlaceholder: '[ÇVV]',
    nameOnCard: '[Ñâmë öñ çârd âš šhöwñ]',
    payNow: '[Þâÿ Ñöw Büţţöñ]',
    standardShipping: '[Šţâñdârd Šhîþþîñg Öþţîöñ]',
    cardDetails: '[Çârd dëţâîlš îñförmâţîöñ]',
    payWithApplePay: '[Þâÿ wîţh Âþþlë Þâÿ šërvîçë]',
    expirationDatePlaceholder: '[MM / ÿÿ]',
    failedToInitializePayment: '[Fâîlëd ţö îñîţîâlîžë þâÿmëñţ þröçëšš.]',
    orderTotal: '[Tötâl Ördër Âmöüñţ]',
    subtotal: '[Šübţöţâl Âmöüñţ]',
    tax: '[Ţâx Çâlçülâţîöñ]',
    shipping: '[Šhîþþîñg Çöšţš]',
    discount: '[Çöüþöñ Âmöüñţ]',
    processingPayment: '[Þröçëššîñg þâÿmëñţ îñförmâţîöñ...]',
    completingOrder: '[Completing order...]',
    completeOrder: '[Çömþlëţë ÿöür ördër]',
    freePayment: '[Complete your free order]',
  },
  phone: {
    placeholder: '[(201) 555-1234]',
    searchCountry: '[Šëârçh çöüñţrÿ bÿ ñâmë...]',
    noCountryFound: '[Ñö çöüñţrÿ föüñd îñ šëârçh rëšülţš.]',
  },
  discounts: {
    placeholder: '[Çöüþöñ çödë îñþüţ]',
    enterCode: '[Ëñţër çöüþöñ çödë hërë]',
    apply: '[Âþþlÿ Çödë]',
    alreadyApplied: '[Ţhîš çöüþöñ çödë hâš âlrëâdÿ bëëñ âþþlîëd ţö ţhîš ördër]',
    failedToApply: '[Fâîlëd ţö âþþlÿ çöüþöñ çödë ţö ţhîš ördër]',
    enterCodeValidation: '[Þlëâšë ëñţër â vâlîd çöüþöñ çödë]',
  },
  totals: {
    subtotal: '[Šübţöţâl Çâlçülâţîöñ]',
    discount: '[Dîšçöüñţ]',
    shipping: '[Šhîþþîñg Çöšţš]',
    tip: '[Ţîþ Âmöüñţ]',
    estimatedTaxes: '[Ëšţîmâţëd ţâxëš çâlçülâţîöñ]',
    totalDue: '[Tötâl Âmöüñţ Düë]',
    orderSummary: '[Ördër Šümmârÿ Dëţâîlš]',
    itemCount: '[îţëmš îñ çârţ]',
    noItems: '[Ñö îţëmš îñ çârţ]',
  },
  lineItems: {
    note: '[Ñöţë îñförmâţîöñ:]',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: '[Âddrëšš šëârçh îñþüţ]',
      suggestions: '[Äüţöçömþlëţë šüggëšţîöñš]',
    },
    form: {
      useFormFieldError:
        '[üšëFörmFîëld šhöüld bë üšëd wîţhîñ <FörmFîëld> çömþöñëñţ]',
    },
    pagination: {
      ariaLabel: '[þâgîñâţîöñ ñâvîgâţîöñ]',
      previousPageAriaLabel: '[Gö ţö þrëvîöüš þâgë îñ lîšţ]',
      previous: '[Þrëvîöüš Þâgë]',
      nextPageAriaLabel: '[Gö ţö ñëxţ þâgë îñ lîšţ]',
      next: '[Ñëxţ Þâgë]',
      morePages: '[Mörë þâgëš âvâîlâblë]',
    },
    sidebar: {
      useSidebarError:
        '[üšëŠîdëbâr müšţ bë üšëd wîţhîñ â ŠîdëbârÞrövîdër çömþöñëñţ.]',
      toggleSidebar: '[Tögglë Šîdëbâr Vîšîbîlîţÿ]',
    },
    accessibility: {
      payWithApplePay: '[Þâÿ wîţh Âþþlë Þâÿ šërvîçë]',
      applePayLogo: '[Âþþlë Þâÿ Löğö Îmâgë]',
      close: '[Çlöšë Büţţöñ]',
      additionalTipOptions: '[Âddîţîöñâl ţîþ öþţîöñš šëlëçţîöñ]',
      breadcrumb: '[brëâdçrümb ñâvîgâţîöñ]',
      more: '[Mörë îţëmš]',
      previousSlide: '[Þrëvîöüš šlîdë]',
      nextSlide: '[Ñëxţ šlîdë]',
    },
  },
  errors: {
    failedToGetAccessToken: '[Fâîlëd ţö gëţ âççëšš ţökëñ frôm šërvër]',
    invalidEnvironment: '[Îñvâlîd ëñvîröñmëñţ çönfîgürâţîöñ]',
    noPublicAccessToken: '[Ñö þüblîç âççëšš ţökëñ þrövîdëd bÿ âþþlîçâţîöñ]',
    noSessionToken: '[Ñö šëššîöñ ţökëñ ör ÎD þrövîdëd fôr âüţhëñţîçâţîöñ]',
    errorCreatingSession: '[Ërrör çrëâţîñg çhëçköüţ šëššîöñ:]',
    orderIdRequired: '[Ördër ÎD îš rëqüîrëd fôr þröçëššîñg]',
    errorTrackingEvent: '[Ërrör ţrâçkîñg ëvëñţ îñ âñâlÿţîçš]',
    errorInTrackingSubscriber: '[Ërrör îñ ţrâçkîñg šübšçrîbër šÿšţëm]',
    useTrackingProviderError:
      '[üšëŢrâçkîñg müšţ bë üšëd wîţhîñ â ŢrâçkîñgÞrövîdër çömþöñëñţ]',
    usePoyntCollectProviderError:
      '[üšëÞöÿñţÇöllëçţ müšţ bë üšëd wîţhîñ â ÞöÿñţÇöllëçţÞrövîdër çömþöñëñţ]',
    useSquareProviderError:
      '[üšëŠqüârë müšţ bë üšëd wîţhîñ â ŠqüârëÞrövîdër çömþöñëñţ]',
    errorProcessingPayment: '[Ërrör þröçëššîñg þâÿmëñţ îñförmâţîöñ]',
    stripeConfigMissing:
      '[Šţrîþë çönfîgürâţîöñ îš mîššîñg. Þlëâšë çhëçk ÿöür šëţüþ.]',
    paymentSuccessful: '[Þâÿmëñţ þröçëššëd šüççëššfüllÿ]',
    paymentFailed: '[Þâÿmëñţ þröçëššîñg fâîlëd]',
    paypalConfigMissing:
      '[ÞâÿÞâl çönfîgürâţîöñ îš mîššîñg. Þlëâšë çhëçk ÿöür šëţüþ.]',
    stripeNotReady: '[Šţrîþë šërvîçë ñöţ rëâdÿ fôr þröçëššîñg]',
    cardElementNotFound: '[ÇârdËlëmëñţ çömþöñëñţ ñöţ föüñd îñ DÖM]',
    errorProcessingCardPayment: '[Ërrör þröçëššîñg çârd þâÿmëñţ îñförmâţîöñ.]',
    errorProcessingExpressPayment: '[Ërrör þröçëššîñg ëxþrëšš þâÿmëñţ mëţhöd.]',
    failedToInitializePayment: '[Fâîlëd ţö îñîţîâlîžë þâÿmëñţ šÿšţëm.]',
    invalidPhoneNumber: '[îñvâlîd þhöñë ñümkër förmâţ]',
  },
  validation: {
    phoneRequired: '[Þhöñë ñümkër îš rëqüîrëd fôr ţhîš ördër]',
    emailRequired: '[Ëñţër âñ ëmâîl âddrëšš fôr çöñţâçţ]',
    emailInvalid: '[Ëñţër â vâlîd ëmâîl âddrëšš förmâţ]',
    phoneTooLong: '[Þhöñë ñümkër îš ţöö löñg fôr vâlîdâţîöñ]',
    invalidShippingAddress: '[Îñvâlîd šhîþþîñg âddrëšš îñförmâţîöñ]',
    invalidBillingAddress: '[Îñvâlîd bîllîñg âddrëšš îñförmâţîöñ]',
    selectPaymentMethod: '[Šëlëçţ â þâÿmëñţ mëţhöd ţö çöñţîñüë]',
    enterValidBillingPhone: '[Ëñţër â vâlîd bîllîñg þhöñë ñümkër]',
    enterValidShippingPhone: '[Ëñţër â vâlîd šhîþþîñg þhöñë ñümkër]',
    enterFirstName: '[Ëñţër â fîršţ ñâmë fôr îdëñţîfîçâţîöñ]',
    enterLastName: '[Ëñţër â lâšţ ñâmë fôr îdëñţîfîçâţîöñ]',
    enterAddress: '[Ëñţër âñ âddrëšš fôr délîvërÿ]',
    enterCity: '[Ëñţër â çîţÿ ñâmë fôr löçâţîöñ]',
    enterZipCode: '[Ëñţër â ŽÎÞ çödë fôr vërîfîçâţîöñ]',
    enterZipPostalCode: '[Ëñţër â ŽÎÞ / þöšţâl çödë fôr vërîfîçâţîöñ]',
    selectState: '[Šëlëçţ â šţâţë/þrövîñçë frôm ţhë âvâîlâblë öþţîöñš]',
    selectCountry: '[Šëlëçţ â çöüñţrÿ frôm ţhë âvâîlâblë öþţîöñš]',
    enterCountry: '[Ëñţër â çöüñţrÿ ñâmë fôr löçâţîöñ]',
    invalidCardNumber: '[Invalid card number ℓσяєм]',
    invalidExpiry: '[Invalid expiration date ℓσяєм ιρѕυм]',
    invalidCvv: '[Invalid security code ℓσяєм]',
    paymentSubmissionFailed:
      '[Payment submission failed. Please try again. ℓσяєм ιρѕυм ∂σℓσя]',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: '[Šërvër ërrör öççürrëd]',
    SESSION_NOT_FOUND: '[Šëššîöñ ñöţ föüñd îñ šÿšţëm]',
    CHECKOUT_SESSION_RETRIEVAL_FAILED:
      '[Fâîlëd ţö rëţrîëvë çhëçköüţ šëššîöñ dâţâ]',
    CHECKOUT_SESSION_NOT_FOUND: '[Çhëçköüţ šëššîöñ ñöţ föüñd îñ šÿšţëm]',
    CHECKOUT_SESSION_FETCH_ERROR:
      '[Gëñërâl çhëçköüţ šëššîöñ fëţçh ërrör öççürrëd]',
    DRAFT_ORDER_NOT_FOUND: '[Ördër ñöţ föüñd îñ šÿšţëm]',
    CHECKOUT_SESSION_CREATION_FAILED: '[Fâîlëd ţö çrëâţë çhëçköüţ šëššîöñ]',
    CREATED_SESSION_DATA_NOT_FOUND: '[Çrëâţëd šëššîöñ dâţâ ñöţ föüñd]',
    CHECKOUT_SESSION_CREATION_ERROR:
      '[Gëñërâl çhëçköüţ šëššîöñ çrëâţîöñ ërrör]',
    CHECKOUT_SESSION_UPDATE_FAILED: '[Fâîlëd ţö üþdâţë çhëçköüţ šëššîöñ]',
    UPDATED_SESSION_NOT_FOUND: '[Üþdâţëd šëššîöñ ñöţ föüñd]',
    CHECKOUT_SESSION_UPDATE_ERROR: '[Gëñërâl çhëçköüţ šëššîöñ üþdâţë ërrör]',
    ORDER_API_NOT_FOUND: '[Ördër ÂÞÎ dâţâ šöürçë ñöţ föüñd]',
    DRAFT_ORDER_RETRIEVAL_FAILED: '[Fâîlëd ţö rëţrîëvë ördër]',
    DATA_SOURCES_NOT_FOUND: '[Dâţâ šöürçëš ñöţ föüñd îñ šÿšţëm]',
    TRANSACTION_API_NOT_FOUND: '[Ţrâñšâçţîöñ ÂÞÎ dâţâ šöürçë ñöţ föüñd]',
    TRANSACTION_PROCESSING_FAILED: '[Fâîlëd ţö þröçëšš ţrâñšâçţîöñ]',
    TRANSACTION_CREATION_FAILED: '[Fâîlëd ţö fîñd ör çrëâţë ţrâñšâçţîöñ]',
    ORDER_OPENING_FAILED: '[Fâîlëd ţö öþëñ ördër fôr þröçëššîñg]',
    INVALID_FULFILLMENT_LOCATION: '[Îñvâlîd füllfîllmëñţ löçâţîöñ šþëçîfîëd]',
    NO_VALID_PICKUP_LOCATION: '[Ñö vâlîd þîçküþ löçâţîöñ âvâîlâblë]',
    DRAFT_ORDER_FETCH_FAILED: '[Fâîlëd ţö fëţçh ördër dâţâ]',
    LINE_ITEMS_FETCH_FAILED: '[Fâîlëd ţö fëţçh lîñë îţëmš îñförmâţîöñ]',
    CURRENT_ORDER_FETCH_FAILED: '[Fâîlëd ţö fëţçh çürrëñţ ördër]',
    DRAFT_ORDER_UPDATE_FAILED: '[Fâîlëd ţö üþdâţë ördër îñförmâţîöñ]',
    DISCOUNT_APPLICATION_FAILED: '[Fâîlëd ţö âþþlÿ çöüþöñ ţö ördër]',
    CONTEXT_UNAVAILABLE: '[Šëššîöñ ör dâţâ šöürçëš ñöţ âvâîlâblë]',
    SHIPPING_LINES_UPDATE_FAILED: '[Fâîlëd ţö üþdâţë šhîþþîñg lîñëš]',
    ORDER_TOTALS_UPDATE_FAILED: '[Fâîlëd ţö üþdâţë ördër ţöţâlš]',
    ORDER_TOTAL_CALCULATION_FAILED: '[Fâîlëd ţö çâlçülâţë ördër ţöţâlš]',
    SHIPPING_METHOD_APPLICATION_FAILED: '[Fâîlëd ţö âþþlÿ šhîþþîñg mëţhöd]',
    SKU_FETCH_FAILED: '[Fâîlëd ţö fëţçh ŠKÜ îñförmâţîöñ]',
    SHIPPING_RATES_CALCULATION_FAILED: '[Fâîlëd ţö çâlçülâţë šhîþþîñg râţëš]',
    SHIPPING_METHOD_NOT_FOUND: '[Šhîþþîñg mëţhöd ñöţ föüñd îñ šÿšţëm]',
    SHIPPING_METHOD_REMOVAL_FAILED: '[Fâîlëd ţö rëmövë šhîþþîñg mëţhöd]',
    SHIPPING_ADDRESS_REQUIRED: '[Šhîþþîñg âddrëšš îš rëqüîrëd fôr þröçëššîñg]',
    INVENTORY_VALIDATION_ERROR: '[Îñvëñţörÿ vâlîdâţîöñ ërrör öççürrëd]',
    INSUFFICIENT_INVENTORY: '[Îñšüffîçîëñţ îñvëñţörÿ âvâîlâblë]',
    INVALID_ORDER_STATUS: '[Îñvâlîd ördër šţâţüš föü þröçëššîñg]',
    TRANSACTION_CREATION_ERROR: '[Ţrâñšâçţîöñ çrëâţîöñ ërrör öççürrëd]',
    TRANSACTION_PROCESSING_ERROR: '[Ţrâñšâçţîöñ þröçëššîñg ërrör öççürrëd]',
    UNKNOWN_ERROR: '[Üñknöwñ ërrör öççürrëd îñ šÿšţëm]',
    FULFILLMENT_CREATION_ERROR: '[Füllfîllmëñţ çrëâţîöñ ërrör öççürrëd]',
    TAX_CALCULATION_ERROR: '[Ţâx çâlçülâţîöñ ërrör öççürrëd]',
    ADDRESS_VERIFICATION_ERROR: '[Âddrëšš vërîfîçâţîöñ ërrör öççürrëd]',
    ADDRESS_MATCHES_ERROR: '[Âddrëšš mâţçhëš ërrör öççürrëd]',
    SHIPPING_CONFLICT_ERROR: '[Šhîþþîñg çönflîçţ ërrör öççürrëd]',
    SHIPPING_ERROR: '[Gëñërâl šhîþþîñg ërrör öççürrëd]',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: '[Þrîçë âdjüšţmëñţ çâlçülâţîöñ ërrör]',
    ORDER_FETCH_ERROR: '[Ördër fëţçh ërrör öççürrëd]',
    DRAFT_ORDER_UPDATE_ERROR: '[Ördër üþdâţë ërrör öççürrëd]',
    DISCOUNT_APPLICATION_ERROR: '[Çöüþöñ âþþlîçâţîöñ ërrör öççürrëd]',
    DRAFT_ORDER_OPEN_ERROR: '[Ördër öþëñ ërrör öççürrëd]',
    ORDER_UPDATE_ERROR: '[Ördër üþdâţë ërrör öççürrëd]',
    CATALOG_FETCH_ERROR: '[Çâţâlög fëţçh ërrör öççürrëd]',
    STORE_ID_NOT_FOUND: '[Šţörë ÎD ñöţ föüñd îñ šÿšţëm]',
    ORDER_NOT_DRAFT: '[Ördër îš ñöţ îñ vâlîd šţâţüš]',
    NO_LINE_ITEMS: '[Ñö lîñë îţëmš föüñd îñ ördër]',
    BAD_USER_INPUT: '[Bâd üšër îñþüţ þrövîdëd]',
    MISSING_SHIPPING_ADDRESS: '[Šhîþþîñg âddrëšš îš rëqüîrëd]',
    MISSING_REQUIRED_FIELD: '[Rëqüîrëd fîëld îš mîššîñg]',
    CATALOG_API_ERROR: '[Çâţâlög šërvîçë ërrör öççürrëd]',
    TAX_SERVICE_UNAVAILABLE: '[Ţâx šërvîçë îš üñâvâîlâblë]',
    SHIPPING_SERVICE_UNAVAILABLE: '[Šhîþþîñg šërvîçë îš üñâvâîlâblë]',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      '[Þrîçë âdjüšţmëñţš šërvîçë îš üñâvâîlâblë]',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED:
      '[Fâîlëd ţö çâlçülâţë þrîçë âdjüšţmëñţš]',
    SERVICE_UNAVAILABLE: '[Šërvîçë îš ţëmþörârîlÿ üñâvâîlâblë]',
    RATE_LIMITED: '[Ţöö mâñÿ rëqüëšţš, þlëâšë ţrÿ âgâîñ lâţër]',
    TIMEOUT: '[Rëqüëšţ ţîmëd öüţ]',
    INTERNAL_ERROR: '[Îñţërñâl šërvër ërrör öççürrëd]',
    SHIPPING_POSTAL_CODE_REQUIRED: '[Šhîþþîñg þöšţâl çödë îš rëqüîrëd]',
    SHIPPING_COUNTRY_CODE_REQUIRED: '[Šhîþþîñg çöüñţrÿ çödë îš rëqüîrëd]',
    SHIPPING_METHOD_REQUIRED: '[Šhîþþîñg mëţhöd îš rëqüîrëd]',
    SHIPPING_ADDRESS_VERIFICATION_FAILED:
      '[Šhîþþîñg âddrëšš vërîfîçâţîöñ fâîlëd]',
    BILLING_ADDRESS_VERIFICATION_FAILED:
      '[Bîllîñg âddrëšš vërîfîçâţîöñ fâîlëd]',
    MISSING_SHIPPING_INFO: '[Šĥîţţîñg âddrëšš ör mëţĥöd fâîlëd ţö âţţļÿ]',
    DEPENDENCY_ERROR:
      'موږ اوس ستاسو امر پروسس نشو کولی. مهرباني وکړئ یو شېبه انتظار وکړئ او بیا هڅه وکړئ',
  },
  storefront: {
    product: '[Product]',
    sale: '[SALE]',
    noImage: '[No image]',
    noImageAvailable: '[No image available]',
    selectOptions: '[Select Options]',
    adding: '[Adding...]',
    addToCart: '[Add to Cart]',
    shoppingCart: '[Shopping Cart]',
    failedToLoadCart: '[Failed to load cart:]',
    retry: '[Retry]',
    yourCartIsEmpty: '[Your cart is empty]',
    addItemsToGetStarted: '[Add items to get started]',
    errorLoadingProducts: '[Error loading products:]',
    errorLoadingProduct: '[Error loading product:]',
    productNotFound: '[Product not found]',
    loadingVariantDetails: '[Loading variant details...]',
    combinationNotAvailable:
      '[This combination is not available. Please select different options.]',
    variantsMatch:
      '[variants match your selection. Select more attributes to narrow down.]',
    quantity: '[Quantity]',
    addingToCart: '[Adding to Cart...]',
    outOfStock: '[Out of Stock]',
    viewDetails: '[View Details]',
    productType: '[Product Type:]',
    productId: '[Product ID:]',
    selectedSku: '[Selected SKU:]',
    stockStatus: '[Stock Status:]',
    lowStock: '[Low Stock]',
    inStock: '[In Stock]',
    remove: '[Remove]',
    removing: '[Removing...]',
    checkout: '[Checkout]',
    itemsPerPage: '[Items per page:]',
    search: '[Search]',
    searchPlaceholder: '[Search products...]',
  },
};
