export const trTr = {
  general: {
    optional: 'isteğe bağlı',
    notes: 'Notlar',
    quantity: 'Miktar',
    free: 'ÜCRETSİZ',
    closed: 'Kapalı',
    apply: 'Uygula',
    checkoutDisabled:
      'Ödeme işlemi şu anda devre dışı. Yaşanan rahatsızlık için özür dileriz.',
  },
  contact: {
    title: 'İletişim',
    description: '',
    email: 'E-posta',
  },
  pickup: {
    title: 'Mağazadan Teslim Alma',
    description:
      'Belirlediğiniz teslim alma saatini karşılamak için her türlü çaba gösterilecektir. Gerçek teslim alma saatleri değişebilir.',
    location: 'Teslim Alma Yeri',
    date: 'Teslim Alma Tarihi',
    time: 'Tercih Edilen Teslim Alma Saati',
    selectStore: 'Bir mağaza konumu seçin',
    selectDate: 'Bir tarih seçin',
    selectTime: 'Bir teslim alma saati seçin',
    storeHours: 'Mağaza Saatleri',
    seeDetails: 'Detayları görüntüle',
    noTimeSlots:
      'Seçilen tarih için uygun zaman dilimi bulunmamaktadır. Lütfen başka bir tarih seçin.',
    hoursDisplayed: 'Saatler yerel saat diliminizde gösterilmektedir.',
    storeOperatesIn: 'Mağaza {timezone} saat diliminde çalışmaktadır.',
    asap: 'EN KISA SÜREDE',
    hour: 'saat',
    hours: 'saat',
    minutes: 'dakika',
    searchCountry: 'Ülke ara...',
    noCountryFound: 'Ülke bulunamadı.',
  },
  days: {
    sunday: 'Pazar',
    monday: 'Pazartesi',
    tuesday: 'Salı',
    wednesday: 'Çarşamba',
    thursday: 'Perşembe',
    friday: 'Cuma',
    saturday: 'Cumartesi',
  },
  delivery: {
    title: 'Teslimat',
    method: 'Teslimat yöntemi',
    shipping: 'Kargo',
    shipToAddress: 'Adresinize kargo gönderin',
    localPickup: 'Mağazadan Teslim Alma',
    pickupFromStore: 'Mağaza konumundan teslim alın',
  },
  tips: {
    title: 'Bahşiş ekleyin',
    noTip: 'Bahşiş Yok',
    customAmount: 'Özel Tutar',
    customTipAmount: 'Özel Bahşiş Tutarı',
    placeholder: '₺0,00',
  },
  shipping: {
    title: 'Kargo',
    description: 'Kargo adresi',
    method: 'Kargo yöntemi',
    noShippingMethodAddress:
      'Mevcut kargo yöntemlerini görmek için adresinizi girin.',
    noShippingMethods: 'Kargo yöntemi bulunamadı.',
    phone: 'Telefon Numarası',
    country: 'Ülke',
    selectCountry: 'Ülke seçin',
    searchCountry: 'Ülke ara...',
    noCountryFound: 'Ülke bulunamadı',
    firstName: 'Ad',
    lastName: 'Soyad',
    address1: 'Adres',
    address2: 'Daire, apartman vb. (isteğe bağlı)',
    city: 'Şehir',
    region: 'İl/Bölge',
    postalCode: 'Posta Kodu',
    notesPlaceholder: 'Notlar veya özel talimatlar',
    addressSuggestion: 'Şunu mu demek istediniz',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Kargo çıkış adresi sağlanmamış.',
  },
  billing: {
    title: 'Faturalama',
    description: 'Faturalama açıklaması',
  },
  payment: {
    title: 'Ödeme',
    description: 'Tüm ödemeler güvenli ve şifrelidir.',
    billingAddress: {
      title: 'Fatura Adresi',
      description: 'Fatura adresinizi girin.',
      useShippingAddress: 'Kargo adresini fatura adresi olarak kullan',
    },
    methods: {
      creditCard: 'Kredi veya Banka Kartı',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Çevrimdışı ödemeler',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
    },
    noMethodsAvailable: 'Kullanılabilir ödeme yöntemi yok',
    cardNumber: 'Kart numarası',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Son kullanma tarihi (AA / YY)',
    securityCode: 'Güvenlik kodu',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Kart üzerindeki isim',
    payNow: 'Şimdi öde',
    standardShipping: 'Standart Kargo',
    cardDetails: 'Kart detayları',
    payWithApplePay: 'Apple Pay ile öde',
    expirationDatePlaceholder: 'AA / YY',
    failedToInitializePayment: 'Ödeme başlatılamadı.',
    orderTotal: 'Sipariş Toplamı',
    subtotal: 'Ara Toplam',
    tax: 'Vergi',
    shipping: 'Kargo',
    discount: 'Kupon',
    processingPayment: 'Ödeme işleniyor...',
    completingOrder: 'Sipariş tamamlanıyor...',
    completeOrder: 'Siparişinizi tamamlayın',
    freePayment: 'Ücretsiz siparişinizi tamamlayın',
  },
  phone: {
    placeholder: '(212) 555-1234',
    searchCountry: 'Ülke ara...',
    noCountryFound: 'Ülke bulunamadı.',
  },
  discounts: {
    placeholder: 'Kupon kodu',
    enterCode: 'Kupon kodu girin',
    apply: 'Uygula',
    alreadyApplied: 'Bu kupon kodu zaten uygulanmış',
    failedToApply: 'Kupon kodu uygulanamadı',
    enterCodeValidation: 'Lütfen bir kupon kodu girin',
  },
  totals: {
    subtotal: 'Ara Toplam',
    discount: 'İndirim',
    shipping: 'Kargo',
    tip: 'Bahşiş',
    estimatedTaxes: 'Tahmini vergiler',
    totalDue: 'Ödenecek Toplam',
    orderSummary: 'Sipariş Özeti',
    itemCount: 'ürün',
    noItems: 'Ürün yok',
  },
  lineItems: {
    note: 'Not:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Adres',
      suggestions: 'Öneriler',
    },
    form: {
      useFormFieldError: 'useFormField <FormField> içinde kullanılmalıdır',
    },
    pagination: {
      ariaLabel: 'sayfalama',
      previousPageAriaLabel: 'Önceki sayfaya git',
      previous: 'Önceki',
      nextPageAriaLabel: 'Sonraki sayfaya git',
      next: 'Sonraki',
      morePages: 'Daha fazla sayfa',
    },
    sidebar: {
      useSidebarError: 'useSidebar bir SidebarProvider içinde kullanılmalıdır.',
      toggleSidebar: 'Kenar Çubuğunu Aç/Kapat',
    },
    accessibility: {
      payWithApplePay: 'Apple Pay ile öde',
      applePayLogo: 'Apple Pay Logosu',
      close: 'Kapat',
      additionalTipOptions: 'Ek bahşiş seçenekleri',
      breadcrumb: 'içerik haritası',
      more: 'Daha fazla',
      previousSlide: 'Önceki slayt',
      nextSlide: 'Sonraki slayt',
    },
  },
  errors: {
    failedToGetAccessToken: 'Erişim belirteci alınamadı',
    invalidEnvironment: 'Geçersiz ortam',
    noPublicAccessToken: 'Genel erişim belirteci sağlanmamış',
    noSessionToken: 'Oturum belirteci veya kimliği sağlanmamış',
    errorCreatingSession: 'Ödeme oturumu oluşturma hatası:',
    orderIdRequired: 'Sipariş kimliği gerekli',
    errorTrackingEvent: 'Olay izleme hatası',
    errorInTrackingSubscriber: 'İzleme abonesi hatası',
    useTrackingProviderError:
      'useTracking bir TrackingProvider içinde kullanılmalıdır',
    usePoyntCollectProviderError:
      'usePoyntCollect bir PoyntCollectProvider içinde kullanılmalıdır',
    useSquareProviderError:
      'useSquare bir SquareProvider içinde kullanılmalıdır',
    errorProcessingPayment: 'Ödeme işleme hatası',
    stripeConfigMissing:
      'Stripe yapılandırması eksik. Lütfen kurulumunuzu kontrol edin.',
    paymentSuccessful: 'Ödeme başarılı',
    paymentFailed: 'Ödeme başarısız',
    paypalConfigMissing:
      'PayPal yapılandırması eksik. Lütfen kurulumunuzu kontrol edin.',
    stripeNotReady: 'Stripe hazır değil',
    cardElementNotFound: 'CardElement bulunamadı',
    errorProcessingCardPayment: 'Kart ödemesi işleme hatası.',
    errorProcessingExpressPayment: 'Hızlı ödeme işleme hatası.',
    failedToInitializePayment: 'Ödeme başlatılamadı.',
    invalidPhoneNumber: 'geçersiz telefon numarası',
  },
  validation: {
    phoneRequired: 'Telefon numarası gerekli',
    emailRequired: 'E-posta girin',
    emailInvalid: 'Geçerli bir e-posta girin',
    phoneTooLong: 'Telefon numarası çok uzun',
    invalidShippingAddress: 'Geçersiz kargo adresi',
    invalidBillingAddress: 'Geçersiz fatura adresi',
    selectPaymentMethod: 'Bir ödeme yöntemi seçin',
    enterValidBillingPhone: 'Geçerli bir fatura telefon numarası girin',
    enterValidShippingPhone: 'Geçerli bir kargo telefon numarası girin',
    enterFirstName: 'Bir ad girin',
    enterLastName: 'Bir soyad girin',
    enterAddress: 'Bir adres girin',
    enterCity: 'Bir şehir girin',
    enterZipCode: 'Bir posta kodu girin',
    enterZipPostalCode: 'Bir posta kodu girin',
    selectState: 'Bir il/eyalet seçin',
    selectCountry: 'Bir ülke seçin',
    enterCountry: 'Bir ülke girin',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Sunucu hatası',
    SESSION_NOT_FOUND: 'Oturum bulunamadı',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Ödeme oturumu alınamadı',
    CHECKOUT_SESSION_NOT_FOUND: 'Ödeme oturumu bulunamadı',
    CHECKOUT_SESSION_FETCH_ERROR: 'Genel ödeme oturumu alma hatası',
    DRAFT_ORDER_NOT_FOUND: 'Sipariş bulunamadı',
    CHECKOUT_SESSION_CREATION_FAILED: 'Ödeme oturumu oluşturulamadı',
    CREATED_SESSION_DATA_NOT_FOUND: 'Oluşturulan oturum verisi bulunamadı',
    CHECKOUT_SESSION_CREATION_ERROR: 'Genel ödeme oturumu oluşturma hatası',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Ödeme oturumu güncellenemedi',
    UPDATED_SESSION_NOT_FOUND: 'Güncellenmiş oturum bulunamadı',
    CHECKOUT_SESSION_UPDATE_ERROR: 'Genel ödeme oturumu güncelleme hatası',
    ORDER_API_NOT_FOUND: 'Sipariş API veri kaynağı bulunamadı',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Sipariş alınamadı',
    DATA_SOURCES_NOT_FOUND: 'Veri kaynakları bulunamadı',
    TRANSACTION_API_NOT_FOUND: 'İşlem API veri kaynağı bulunamadı',
    TRANSACTION_PROCESSING_FAILED: 'İşlem işlenemedi',
    TRANSACTION_CREATION_FAILED: 'İşlem bulunamadı veya oluşturulamadı',
    ORDER_OPENING_FAILED: 'Sipariş açılamadı',
    INVALID_FULFILLMENT_LOCATION: 'Geçersiz karşılama konumu',
    NO_VALID_PICKUP_LOCATION: 'Geçerli teslim alma konumu mevcut değil',
    DRAFT_ORDER_FETCH_FAILED: 'Sipariş alınamadı',
    LINE_ITEMS_FETCH_FAILED: 'Satır öğeleri alınamadı',
    CURRENT_ORDER_FETCH_FAILED: 'Mevcut sipariş alınamadı',
    DRAFT_ORDER_UPDATE_FAILED: 'Sipariş güncellenemedi',
    DISCOUNT_APPLICATION_FAILED: 'Kupon uygulanamadı',
    CONTEXT_UNAVAILABLE: 'Oturum veya veri kaynakları mevcut değil',
    SHIPPING_LINES_UPDATE_FAILED: 'Kargo satırları güncellenemedi',
    ORDER_TOTALS_UPDATE_FAILED: 'Sipariş toplamları güncellenemedi',
    ORDER_TOTAL_CALCULATION_FAILED: 'Sipariş toplamları hesaplanamadı',
    SHIPPING_METHOD_APPLICATION_FAILED: 'Kargo yöntemi uygulanamadı',
    SKU_FETCH_FAILED: "SKU'lar alınamadı",
    SHIPPING_RATES_CALCULATION_FAILED: 'Kargo ücretleri hesaplanamadı',
    SHIPPING_METHOD_NOT_FOUND: 'Kargo yöntemi bulunamadı',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Kargo yöntemi kaldırılamadı',
    SHIPPING_ADDRESS_REQUIRED: 'Kargo adresi gerekli',
    INVENTORY_VALIDATION_ERROR: 'Envanter doğrulama hatası',
    INSUFFICIENT_INVENTORY: 'Yetersiz envanter',
    INVALID_ORDER_STATUS: 'Geçersiz sipariş durumu',
    TRANSACTION_CREATION_ERROR: 'İşlem oluşturma hatası',
    TRANSACTION_PROCESSING_ERROR: 'İşlem işleme hatası',
    UNKNOWN_ERROR: 'Bilinmeyen hata',
    FULFILLMENT_CREATION_ERROR: 'Karşılama oluşturma hatası',
    TAX_CALCULATION_ERROR: 'Vergi hesaplama hatası',
    ADDRESS_VERIFICATION_ERROR: 'Adres doğrulama hatası',
    ADDRESS_MATCHES_ERROR: 'Adres eşleşme hatası',
    SHIPPING_CONFLICT_ERROR: 'Kargo çakışma hatası',
    SHIPPING_ERROR: 'Genel kargo hatası',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Fiyat ayarlama hesaplama hatası',
    ORDER_FETCH_ERROR: 'Sipariş alma hatası',
    DRAFT_ORDER_UPDATE_ERROR: 'Sipariş güncelleme hatası',
    DISCOUNT_APPLICATION_ERROR: 'Kupon uygulama hatası',
    DRAFT_ORDER_OPEN_ERROR: 'Sipariş açma hatası',
    ORDER_UPDATE_ERROR: 'Sipariş güncelleme hatası',
    CATALOG_FETCH_ERROR: 'Katalog alma hatası',
    STORE_ID_NOT_FOUND: "Mağaza ID'si bulunamadı",
    ORDER_NOT_DRAFT: 'Sipariş geçerli durumunda değil',
    NO_LINE_ITEMS: 'Hiç ürün bulunamadı',
    BAD_USER_INPUT: 'Geçersiz kullanıcı girişi',
    MISSING_SHIPPING_ADDRESS: 'Teslimat adresi gerekli',
    MISSING_REQUIRED_FIELD: 'Zorunlu alan eksik',
    CATALOG_API_ERROR: 'Katalog servisi hatası',
    TAX_SERVICE_UNAVAILABLE: 'Vergi servisi kullanılamıyor',
    SHIPPING_SERVICE_UNAVAILABLE: 'Kargo servisi kullanılamıyor',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Fiyat ayarlama servisi kullanılamıyor',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED: 'Fiyat ayarlamaları hesaplanamadı',
    SERVICE_UNAVAILABLE: 'Servis geçici olarak kullanılamıyor',
    RATE_LIMITED: 'Çok fazla istek, lütfen daha sonra tekrar deneyin',
    TIMEOUT: 'İstek zaman aşımına uğradı',
    INTERNAL_ERROR: 'Sunucu içi hatası',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Kargo posta kodu gerekli',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Kargo ülke kodu gerekli',
    SHIPPING_METHOD_REQUIRED: 'Kargo yöntemi gerekli',
    SHIPPING_ADDRESS_VERIFICATION_FAILED: 'Kargo adresi doğrulaması başarısız',
    BILLING_ADDRESS_VERIFICATION_FAILED: 'Fatura adresi doğrulaması başarısız',
    MISSING_SHIPPING_INFO: 'Kargo adresi veya yöntemi uygulanamadı',
    DEPENDENCY_ERROR:
      'Şu anda siparişinizi işleme alamıyoruz. Lütfen bir dakika bekleyin ve tekrar deneyin',
  },
};
