export const viVn = {
  general: {
    optional: 'tùy chọn',
    notes: 'Ghi chú',
    quantity: 'Số lượng',
    free: 'MIỄN PHÍ',
    closed: 'Đóng cửa',
    apply: 'Áp dụng',
    checkoutDisabled:
      'Thanh toán hiện tại đang bị vô hiệu hóa. Chúng tôi xin lỗi vì sự bất tiện này.',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: 'Được cung cấp bởi',
  },
  contact: {
    title: 'Liên hệ',
    description: '',
    email: 'Email',
  },
  pickup: {
    title: 'Nhận hàng tại cửa hàng',
    description:
      'Chúng tôi sẽ cố gắng hết sức để đáp ứng thời gian nhận hàng mong muốn của bạn. Thời gian nhận hàng thực tế có thể thay đổi.',
    location: 'Địa điểm nhận hàng',
    date: 'Ngày nhận hàng',
    time: 'Thời gian nhận hàng ưa thích',
    selectStore: 'Chọn một địa điểm cửa hàng',
    selectDate: 'Chọn ngày',
    selectTime: 'Chọn thời gian nhận hàng',
    storeHours: 'Giờ mở cửa',
    seeDetails: 'Xem chi tiết',
    noTimeSlots:
      'Không có khung thời gian nào trong ngày đã chọn. Vui lòng chọn ngày khác.',
    hoursDisplayed: 'Giờ hiển thị theo múi giờ địa phương của bạn.',
    storeOperatesIn: 'Cửa hàng hoạt động trong múi giờ {timezone}.',
    asap: 'CÀNG SỚM CÀNG TỐT',
    hour: 'giờ',
    hours: 'giờ',
    minutes: 'phút',
    searchCountry: 'Tìm kiếm quốc gia...',
    noCountryFound: 'Không tìm thấy quốc gia.',
  },
  days: {
    sunday: 'Chủ nhật',
    monday: 'Thứ hai',
    tuesday: 'Thứ ba',
    wednesday: 'Thứ tư',
    thursday: 'Thứ năm',
    friday: 'Thứ sáu',
    saturday: 'Thứ bảy',
  },
  delivery: {
    title: 'Giao hàng',
    method: 'Phương thức giao hàng',
    shipping: 'Vận chuyển',
    shipToAddress: 'Giao đến địa chỉ của bạn',
    localPickup: 'Nhận hàng tại cửa hàng',
    pickupFromStore: 'Nhận tại địa điểm cửa hàng',
  },
  tips: {
    title: 'Thêm tiền tip',
    noTip: 'Không tip',
    customAmount: 'Số tiền tùy chỉnh',
    customTipAmount: 'Số tiền tip tùy chỉnh',
    placeholder: '0₫',
  },
  shipping: {
    title: 'Vận chuyển',
    description: 'Địa chỉ giao hàng',
    method: 'Phương thức vận chuyển',
    noShippingMethodAddress:
      'Nhập địa chỉ của bạn để xem các phương thức vận chuyển có sẵn.',
    noShippingMethods: 'Không tìm thấy phương thức vận chuyển nào.',
    phone: 'Số điện thoại',
    country: 'Quốc gia',
    selectCountry: 'Chọn quốc gia',
    searchCountry: 'Tìm kiếm quốc gia...',
    noCountryFound: 'Không tìm thấy quốc gia',
    firstName: 'Tên',
    lastName: 'Họ',
    address1: 'Địa chỉ',
    address2: 'Căn hộ, tầng, v.v. (tùy chọn)',
    city: 'Thành phố',
    region: 'Tỉnh/Thành phố',
    postalCode: 'Mã bưu điện',
    notesPlaceholder: 'Ghi chú hoặc hướng dẫn đặc biệt',
    addressSuggestion: 'Ý bạn có phải là',
    addressSuggestionEnd: '?',
    noShippingOriginAddress: 'Không có địa chỉ gốc vận chuyển được cung cấp.',
  },
  billing: {
    title: 'Thanh toán',
    description: 'Mô tả thanh toán',
  },
  payment: {
    title: 'Thanh toán',
    description: 'Tất cả thanh toán đều được bảo mật và mã hóa.',
    billingAddress: {
      title: 'Địa chỉ thanh toán',
      description: 'Nhập địa chỉ thanh toán của bạn.',
      useShippingAddress: 'Sử dụng địa chỉ giao hàng làm địa chỉ thanh toán',
    },
    methods: {
      creditCard: 'Thẻ tín dụng hoặc thẻ ghi nợ',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: 'Thanh toán ngoại tuyến',
      ach: 'Tài khoản ngân hàng',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
      ach: '',
    },
    noMethodsAvailable: 'Không có phương thức thanh toán nào',
    cardNumber: 'Số thẻ',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: 'Ngày hết hạn (MM / YY)',
    securityCode: 'Mã bảo mật',
    cvvPlaceholder: 'CVV',
    nameOnCard: 'Tên trên thẻ',
    payNow: 'Thanh toán ngay',
    standardShipping: 'Vận chuyển tiêu chuẩn',
    cardDetails: 'Chi tiết thẻ',
    payWithApplePay: 'Thanh toán bằng Apple Pay',
    expirationDatePlaceholder: 'MM / YY',
    failedToInitializePayment: 'Không thể khởi tạo thanh toán.',
    orderTotal: 'Tổng đơn hàng',
    subtotal: 'Tạm tính',
    tax: 'Thuế',
    shipping: 'Vận chuyển',
    discount: 'Phiếu giảm giá',
    processingPayment: 'Đang xử lý thanh toán...',
    completingOrder: 'Đang hoàn tất đơn hàng...',
    completeOrder: 'Hoàn tất đơn hàng của bạn',
    freePayment: 'Hoàn tất đơn hàng miễn phí của bạn',
  },
  phone: {
    placeholder: '(84) 123-456-789',
    searchCountry: 'Tìm kiếm quốc gia...',
    noCountryFound: 'Không tìm thấy quốc gia.',
  },
  discounts: {
    placeholder: 'Mã phiếu giảm giá',
    enterCode: 'Nhập mã phiếu giảm giá',
    apply: 'Áp dụng',
    alreadyApplied: 'Mã phiếu giảm giá này đã được áp dụng',
    failedToApply: 'Không thể áp dụng mã phiếu giảm giá',
    enterCodeValidation: 'Vui lòng nhập mã phiếu giảm giá',
  },
  totals: {
    subtotal: 'Tạm tính',
    discount: 'Giảm giá',
    shipping: 'Vận chuyển',
    tip: 'Tip',
    estimatedTaxes: 'Thuế ước tính',
    totalDue: 'Tổng cộng',
    orderSummary: 'Tóm tắt đơn hàng',
    itemCount: 'sản phẩm',
    noItems: 'Không có sản phẩm',
  },
  lineItems: {
    note: 'Ghi chú:',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: 'Địa chỉ',
      suggestions: 'Gợi ý',
    },
    form: {
      useFormFieldError: 'useFormField phải được sử dụng trong <FormField>',
    },
    pagination: {
      ariaLabel: 'phân trang',
      previousPageAriaLabel: 'Đi đến trang trước',
      previous: 'Trước',
      nextPageAriaLabel: 'Đi đến trang tiếp theo',
      next: 'Tiếp theo',
      morePages: 'Thêm trang',
    },
    sidebar: {
      useSidebarError: 'useSidebar phải được sử dụng trong SidebarProvider.',
      toggleSidebar: 'Bật/Tắt thanh bên',
    },
    accessibility: {
      payWithApplePay: 'Thanh toán bằng Apple Pay',
      applePayLogo: 'Logo Apple Pay',
      close: 'Đóng',
      additionalTipOptions: 'Tùy chọn tiền boa bổ sung',
      breadcrumb: 'điều hướng breadcrumb',
      more: 'Thêm',
      previousSlide: 'Trang trước',
      nextSlide: 'Trang tiếp theo',
    },
  },
  errors: {
    failedToGetAccessToken: 'Không thể lấy mã truy cập',
    invalidEnvironment: 'Môi trường không hợp lệ',
    noPublicAccessToken: 'Không có mã truy cập công khai được cung cấp',
    noSessionToken: 'Không có mã phiên hoặc ID được cung cấp',
    errorCreatingSession: 'Lỗi tạo phiên thanh toán:',
    orderIdRequired: 'ID đơn hàng là bắt buộc',
    errorTrackingEvent: 'Lỗi theo dõi sự kiện',
    errorInTrackingSubscriber: 'Lỗi trong người đăng ký theo dõi',
    useTrackingProviderError:
      'useTracking phải được sử dụng trong TrackingProvider',
    usePoyntCollectProviderError:
      'usePoyntCollect phải được sử dụng trong PoyntCollectProvider',
    useSquareProviderError: 'useSquare phải được sử dụng trong SquareProvider',
    errorProcessingPayment: 'Lỗi xử lý thanh toán',
    stripeConfigMissing:
      'Cấu hình Stripe bị thiếu. Vui lòng kiểm tra thiết lập của bạn.',
    paymentSuccessful: 'Thanh toán thành công',
    paymentFailed: 'Thanh toán thất bại',
    paypalConfigMissing:
      'Cấu hình PayPal bị thiếu. Vui lòng kiểm tra thiết lập của bạn.',
    stripeNotReady: 'Stripe chưa sẵn sàng',
    cardElementNotFound: 'Không tìm thấy CardElement',
    errorProcessingCardPayment: 'Lỗi xử lý thanh toán thẻ.',
    errorProcessingExpressPayment: 'Lỗi xử lý thanh toán nhanh.',
    failedToInitializePayment: 'Không thể khởi tạo thanh toán.',
    invalidPhoneNumber: 'số điện thoại không hợp lệ',
  },
  validation: {
    phoneRequired: 'Số điện thoại là bắt buộc',
    emailRequired: 'Nhập email',
    emailInvalid: 'Nhập email hợp lệ',
    phoneTooLong: 'Số điện thoại quá dài',
    invalidShippingAddress: 'Địa chỉ giao hàng không hợp lệ',
    invalidBillingAddress: 'Địa chỉ thanh toán không hợp lệ',
    selectPaymentMethod: 'Chọn phương thức thanh toán',
    enterValidBillingPhone: 'Nhập số điện thoại thanh toán hợp lệ',
    enterValidShippingPhone: 'Nhập số điện thoại giao hàng hợp lệ',
    enterFirstName: 'Nhập tên',
    enterLastName: 'Nhập họ',
    enterAddress: 'Nhập địa chỉ',
    enterCity: 'Nhập thành phố',
    enterZipCode: 'Nhập mã ZIP',
    enterZipPostalCode: 'Nhập mã ZIP / bưu điện',
    selectState: 'Chọn tỉnh/thành phố',
    selectCountry: 'Chọn quốc gia',
    enterCountry: 'Nhập quốc gia',
    invalidCardNumber: 'Số thẻ không hợp lệ',
    invalidExpiry: 'Ngày hết hạn không hợp lệ',
    invalidCvv: 'Mã bảo mật không hợp lệ',
    paymentSubmissionFailed: 'Gửi thanh toán thất bại. Vui lòng thử lại.',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: 'Lỗi máy chủ',
    SESSION_NOT_FOUND: 'Không tìm thấy phiên',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: 'Không thể truy xuất phiên thanh toán',
    CHECKOUT_SESSION_NOT_FOUND: 'Không tìm thấy phiên thanh toán',
    CHECKOUT_SESSION_FETCH_ERROR: 'Lỗi truy xuất phiên thanh toán chung',
    DRAFT_ORDER_NOT_FOUND: 'Không tìm thấy đơn hàng',
    CHECKOUT_SESSION_CREATION_FAILED: 'Không thể tạo phiên thanh toán',
    CREATED_SESSION_DATA_NOT_FOUND: 'Không tìm thấy dữ liệu phiên đã tạo',
    CHECKOUT_SESSION_CREATION_ERROR: 'Lỗi tạo phiên thanh toán chung',
    CHECKOUT_SESSION_UPDATE_FAILED: 'Không thể cập nhật phiên thanh toán',
    UPDATED_SESSION_NOT_FOUND: 'Không tìm thấy phiên đã cập nhật',
    CHECKOUT_SESSION_UPDATE_ERROR: 'Lỗi cập nhật phiên thanh toán chung',
    ORDER_API_NOT_FOUND: 'Không tìm thấy nguồn dữ liệu API đơn hàng',
    DRAFT_ORDER_RETRIEVAL_FAILED: 'Không thể truy xuất đơn hàng',
    DATA_SOURCES_NOT_FOUND: 'Không tìm thấy nguồn dữ liệu',
    TRANSACTION_API_NOT_FOUND: 'Không tìm thấy nguồn dữ liệu API giao dịch',
    TRANSACTION_PROCESSING_FAILED: 'Không thể xử lý giao dịch',
    TRANSACTION_CREATION_FAILED: 'Không thể tìm hoặc tạo giao dịch',
    ORDER_OPENING_FAILED: 'Không thể mở đơn hàng',
    INVALID_FULFILLMENT_LOCATION: 'Địa điểm thực hiện không hợp lệ',
    NO_VALID_PICKUP_LOCATION: 'Không có địa điểm nhận hàng hợp lệ',
    DRAFT_ORDER_FETCH_FAILED: 'Không thể tải đơn hàng',
    LINE_ITEMS_FETCH_FAILED: 'Không thể tải các mặt hàng',
    CURRENT_ORDER_FETCH_FAILED: 'Không thể tải đơn hàng hiện tại',
    DRAFT_ORDER_UPDATE_FAILED: 'Không thể cập nhật đơn hàng',
    DISCOUNT_APPLICATION_FAILED: 'Không thể áp dụng phiếu giảm giá',
    CONTEXT_UNAVAILABLE: 'Phiên hoặc nguồn dữ liệu không có sẵn',
    SHIPPING_LINES_UPDATE_FAILED: 'Không thể cập nhật dòng vận chuyển',
    ORDER_TOTALS_UPDATE_FAILED: 'Không thể cập nhật tổng đơn hàng',
    ORDER_TOTAL_CALCULATION_FAILED: 'Không thể tính tổng đơn hàng',
    SHIPPING_METHOD_APPLICATION_FAILED:
      'Không thể áp dụng phương thức vận chuyển',
    SKU_FETCH_FAILED: 'Không thể tải SKU',
    SHIPPING_RATES_CALCULATION_FAILED: 'Không thể tính phí vận chuyển',
    SHIPPING_METHOD_NOT_FOUND: 'Không tìm thấy phương thức vận chuyển',
    SHIPPING_METHOD_REMOVAL_FAILED: 'Không thể xóa phương thức vận chuyển',
    SHIPPING_ADDRESS_REQUIRED: 'Cần có địa chỉ giao hàng',
    INVENTORY_VALIDATION_ERROR: 'Lỗi xác thực hàng tồn kho',
    INSUFFICIENT_INVENTORY: 'Hàng tồn kho không đủ',
    INVALID_ORDER_STATUS: 'Trạng thái đơn hàng không hợp lệ',
    TRANSACTION_CREATION_ERROR: 'Lỗi tạo giao dịch',
    TRANSACTION_PROCESSING_ERROR: 'Lỗi xử lý giao dịch',
    UNKNOWN_ERROR: 'Lỗi không xác định',
    FULFILLMENT_CREATION_ERROR: 'Lỗi tạo thực hiện',
    TAX_CALCULATION_ERROR: 'Lỗi tính thuế',
    ADDRESS_VERIFICATION_ERROR: 'Lỗi xác minh địa chỉ',
    ADDRESS_MATCHES_ERROR: 'Lỗi khớp địa chỉ',
    SHIPPING_CONFLICT_ERROR: 'Lỗi xung đột vận chuyển',
    SHIPPING_ERROR: 'Lỗi vận chuyển chung',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: 'Lỗi tính điều chỉnh giá',
    ORDER_FETCH_ERROR: 'Lỗi tải đơn hàng',
    DRAFT_ORDER_UPDATE_ERROR: 'Lỗi cập nhật đơn hàng',
    DISCOUNT_APPLICATION_ERROR: 'Lỗi áp dụng phiếu giảm giá',
    DRAFT_ORDER_OPEN_ERROR: 'Lỗi mở đơn hàng',
    ORDER_UPDATE_ERROR: 'Lỗi cập nhật đơn hàng',
    CATALOG_FETCH_ERROR: 'Lỗi tải danh mục',
    STORE_ID_NOT_FOUND: 'Không tìm thấy ID cửa hàng',
    ORDER_NOT_DRAFT: 'Đơn hàng không ở trạng thái hợp lệ',
    NO_LINE_ITEMS: 'Không tìm thấy sản phẩm nào',
    BAD_USER_INPUT: 'Dữ liệu đầu vào không hợp lệ',
    MISSING_SHIPPING_ADDRESS: 'Địa chỉ giao hàng là bắt buộc',
    MISSING_REQUIRED_FIELD: 'Thiếu trường bắt buộc',
    CATALOG_API_ERROR: 'Lỗi dịch vụ danh mục',
    TAX_SERVICE_UNAVAILABLE: 'Dịch vụ thuế không khả dụng',
    SHIPPING_SERVICE_UNAVAILABLE: 'Dịch vụ vận chuyển không khả dụng',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE:
      'Dịch vụ điều chỉnh giá không khả dụng',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED: 'Không thể tính toán điều chỉnh giá',
    SERVICE_UNAVAILABLE: 'Dịch vụ tạm thời không khả dụng',
    RATE_LIMITED: 'Quá nhiều yêu cầu, vui lòng thử lại sau',
    TIMEOUT: 'Yêu cầu hết thời gian chờ',
    INTERNAL_ERROR: 'Lỗi máy chủ nội bộ',
    SHIPPING_POSTAL_CODE_REQUIRED: 'Mã bưu điện giao hàng là bắt buộc',
    SHIPPING_COUNTRY_CODE_REQUIRED: 'Mã quốc gia giao hàng là bắt buộc',
    SHIPPING_METHOD_REQUIRED: 'Phương thức giao hàng là bắt buộc',
    SHIPPING_ADDRESS_VERIFICATION_FAILED: 'Xác minh địa chỉ giao hàng thất bại',
    BILLING_ADDRESS_VERIFICATION_FAILED: 'Xác minh địa chỉ thanh toán thất bại',
    MISSING_SHIPPING_INFO:
      'Địa chỉ hoặc phương thức giao hàng không thể áp dụng',
    DEPENDENCY_ERROR:
      'Chúng tôi không thể xử lý đơn hàng của bạn ngay bây giờ. Vui lòng đợi một chút và thử lại',
  },
  storefront: {
    product: 'Sản phẩm',
    sale: 'GIẢM GIÁ',
    noImage: 'Không có hình ảnh',
    noImageAvailable: 'Không có hình ảnh',
    selectOptions: 'Chọn tùy chọn',
    adding: 'Đang thêm...',
    addToCart: 'Thêm vào giỏ hàng',
    shoppingCart: 'Giỏ hàng',
    failedToLoadCart: 'Không tải được giỏ hàng:',
    retry: 'Thử lại',
    yourCartIsEmpty: 'Giỏ hàng của bạn trống',
    addItemsToGetStarted: 'Thêm sản phẩm để bắt đầu',
    errorLoadingProducts: 'Lỗi tải sản phẩm:',
    errorLoadingProduct: 'Lỗi tải sản phẩm:',
    productNotFound: 'Không tìm thấy sản phẩm',
    loadingVariantDetails: 'Đang tải chi tiết biến thể...',
    combinationNotAvailable:
      'Sự kết hợp này không có sẵn. Vui lòng chọn tùy chọn khác.',
    variantsMatch:
      'biến thể phù hợp với lựa chọn của bạn. Chọn thêm thuộc tính để thu hẹp.',
    quantity: 'Số lượng',
    addingToCart: 'Đang thêm vào giỏ hàng...',
    outOfStock: 'Hết hàng',
    viewDetails: 'Xem chi tiết',
    productType: 'Loại sản phẩm:',
    productId: 'ID sản phẩm:',
    selectedSku: 'SKU đã chọn:',
    stockStatus: 'Trạng thái kho:',
    lowStock: 'Sắp hết hàng',
    inStock: 'Còn hàng',
    remove: 'Xóa',
    removing: 'Đang xóa...',
    checkout: 'Thanh toán',
    itemsPerPage: 'Mục trên mỗi trang:',
    search: 'Tìm kiếm',
    searchPlaceholder: 'Tìm kiếm sản phẩm...',
  },
};
