export const zhCn = {
  general: {
    optional: '可选',
    notes: '备注',
    quantity: '数量',
    free: '免费',
    closed: '已关闭',
    apply: '应用',
    checkoutDisabled: '结账功能暂时不可用。为此造成的不便，我们深表歉意。',
    godaddyCheckout: 'GoDaddy Checkout',
    poweredBy: '技术支持',
  },
  contact: {
    title: '联系方式',
    description: '',
    email: '邮箱',
  },
  pickup: {
    title: '到店自提',
    description: '我们将尽力满足您期望的取货时间。实际取货时间可能有所变化。',
    location: '取货地点',
    date: '取货日期',
    time: '首选取货时间',
    selectStore: '选择门店位置',
    selectDate: '选择日期',
    selectTime: '选择取货时间',
    storeHours: '营业时间',
    seeDetails: '查看详情',
    noTimeSlots: '所选日期没有可用的时间段。请选择其他日期。',
    hoursDisplayed: '显示时间为您所在的时区。',
    storeOperatesIn: '门店营业时区为 {timezone}。',
    asap: '尽快',
    hour: '小时',
    hours: '小时',
    minutes: '分钟',
    searchCountry: '搜索国家...',
    noCountryFound: '未找到国家。',
  },
  days: {
    sunday: '星期日',
    monday: '星期一',
    tuesday: '星期二',
    wednesday: '星期三',
    thursday: '星期四',
    friday: '星期五',
    saturday: '星期六',
  },
  delivery: {
    title: '配送',
    method: '配送方式',
    shipping: '快递配送',
    shipToAddress: '配送到您的地址',
    localPickup: '到店自提',
    pickupFromStore: '到门店取货',
  },
  tips: {
    title: '添加小费',
    noTip: '无小费',
    customAmount: '自定义金额',
    customTipAmount: '自定义小费金额',
    placeholder: '¥0.00',
  },
  shipping: {
    title: '配送',
    description: '配送地址',
    method: '配送方式',
    noShippingMethodAddress: '请输入您的地址以查看可用的配送方式。',
    noShippingMethods: '未找到配送方式。',
    phone: '手机号码',
    country: '国家',
    selectCountry: '选择国家',
    searchCountry: '搜索国家...',
    noCountryFound: '未找到国家',
    firstName: '名',
    lastName: '姓',
    address1: '地址',
    address2: '公寓、套房等（可选）',
    city: '城市',
    region: '省/自治区/直辖市',
    postalCode: '邮政编码',
    notesPlaceholder: '备注或特殊说明',
    addressSuggestion: '您是否指的是',
    addressSuggestionEnd: '？',
    noShippingOriginAddress: '未提供配送起始地址。',
  },
  billing: {
    title: '账单',
    description: '账单说明',
  },
  payment: {
    title: '付款',
    description: '所有付款均经过安全加密。',
    billingAddress: {
      title: '账单地址',
      description: '请输入您的账单地址。',
      useShippingAddress: '使用配送地址作为账单地址',
    },
    methods: {
      creditCard: '信用卡或储蓄卡',
      paypal: 'PayPal',
      applePay: 'Apple Pay',
      googlePay: 'Google Pay',
      paze: 'Paze',
      offline: '线下付款',
    },
    descriptions: {
      creditCard: '',
      paypal: '',
      applePay: '',
      googlePay: '',
      paze: '',
      offline: '',
    },
    noMethodsAvailable: '暂无可用的付款方式',
    cardNumber: '卡号',
    cardNumberPlaceholder: '1234 1234 1234 1234',
    expirationDate: '有效期（MM / YY）',
    securityCode: '安全码',
    cvvPlaceholder: 'CVV',
    nameOnCard: '持卡人姓名',
    payNow: '立即付款',
    standardShipping: '标准配送',
    cardDetails: '卡片详情',
    payWithApplePay: '使用 Apple Pay 付款',
    expirationDatePlaceholder: 'MM / YY',
    failedToInitializePayment: '付款初始化失败。',
    orderTotal: '订单总计',
    subtotal: '小计',
    tax: '税费',
    shipping: '配送费',
    discount: '优惠券',
    processingPayment: '正在处理付款...',
    completingOrder: '正在完成订单...',
    completeOrder: '完成您的订单',
    freePayment: '完成您的免费订单',
  },
  phone: {
    placeholder: '13012345678',
    searchCountry: '搜索国家...',
    noCountryFound: '未找到国家。',
  },
  discounts: {
    placeholder: '优惠券代码',
    enterCode: '输入优惠券代码',
    apply: '应用',
    alreadyApplied: '此优惠券代码已使用',
    failedToApply: '优惠券代码使用失败',
    enterCodeValidation: '请输入优惠券代码',
  },
  totals: {
    subtotal: '小计',
    discount: '折扣',
    shipping: '配送费',
    tip: '小费',
    estimatedTaxes: '预估税费',
    totalDue: '应付总计',
    orderSummary: '订单摘要',
    itemCount: '件商品',
    noItems: '无商品',
  },
  lineItems: {
    note: '备注：',
  },
  ui: {
    autocomplete: {
      addressPlaceholder: '地址',
      suggestions: '建议',
    },
    form: {
      useFormFieldError: 'useFormField 应在 <FormField> 中使用',
    },
    pagination: {
      ariaLabel: '分页',
      previousPageAriaLabel: '转到上一页',
      previous: '上一页',
      nextPageAriaLabel: '转到下一页',
      next: '下一页',
      morePages: '更多页面',
    },
    sidebar: {
      useSidebarError: 'useSidebar 必须在 SidebarProvider 中使用。',
      toggleSidebar: '切换侧边栏',
    },
    accessibility: {
      payWithApplePay: '使用 Apple Pay 付款',
      applePayLogo: 'Apple Pay 标志',
      close: '关闭',
      additionalTipOptions: '其他小费选项',
      breadcrumb: '面包屑导航',
      more: '更多',
      previousSlide: '上一张幻灯片',
      nextSlide: '下一张幻灯片',
    },
  },
  errors: {
    failedToGetAccessToken: '获取访问令牌失败',
    invalidEnvironment: '无效环境',
    noPublicAccessToken: '未提供公共访问令牌',
    noSessionToken: '未提供会话令牌或 ID',
    errorCreatingSession: '创建结账会话时出错：',
    orderIdRequired: '订单 ID 是必需的',
    errorTrackingEvent: '跟踪事件出错',
    errorInTrackingSubscriber: '跟踪订阅者出错',
    useTrackingProviderError: 'useTracking 必须在 TrackingProvider 中使用',
    usePoyntCollectProviderError:
      'usePoyntCollect 必须在 PoyntCollectProvider 中使用',
    useSquareProviderError: 'useSquare 必须在 SquareProvider 中使用',
    errorProcessingPayment: '处理付款时出错',
    stripeConfigMissing: 'Stripe 配置缺失。请检查您的设置。',
    paymentSuccessful: '付款成功',
    paymentFailed: '付款失败',
    paypalConfigMissing: 'PayPal 配置缺失。请检查您的设置。',
    stripeNotReady: 'Stripe 未就绪',
    cardElementNotFound: '未找到 CardElement',
    errorProcessingCardPayment: '处理卡片付款时出错。',
    errorProcessingExpressPayment: '处理快捷付款时出错。',
    failedToInitializePayment: '付款初始化失败。',
    invalidPhoneNumber: '手机号码无效',
  },
  validation: {
    phoneRequired: '手机号码是必需的',
    emailRequired: '请输入邮箱',
    emailInvalid: '请输入有效的邮箱',
    phoneTooLong: '手机号码过长',
    invalidShippingAddress: '配送地址无效',
    invalidBillingAddress: '账单地址无效',
    selectPaymentMethod: '选择付款方式',
    enterValidBillingPhone: '请输入有效的账单手机号码',
    enterValidShippingPhone: '请输入有效的配送手机号码',
    enterFirstName: '请输入名',
    enterLastName: '请输入姓',
    enterAddress: '请输入地址',
    enterCity: '请输入城市',
    enterZipCode: '请输入邮政编码',
    enterZipPostalCode: '请输入邮政编码',
    selectState: '选择省份/地区',
    selectCountry: '选择国家',
    enterCountry: '请输入国家',
  },
  apiErrors: {
    INTERNAL_SERVER_ERROR: '服务器错误',
    SESSION_NOT_FOUND: '会话未找到',
    CHECKOUT_SESSION_RETRIEVAL_FAILED: '获取结账会话失败',
    CHECKOUT_SESSION_NOT_FOUND: '结账会话未找到',
    CHECKOUT_SESSION_FETCH_ERROR: '结账会话获取错误',
    DRAFT_ORDER_NOT_FOUND: '订单未找到',
    CHECKOUT_SESSION_CREATION_FAILED: '创建结账会话失败',
    CREATED_SESSION_DATA_NOT_FOUND: '创建的会话数据未找到',
    CHECKOUT_SESSION_CREATION_ERROR: '结账会话创建错误',
    CHECKOUT_SESSION_UPDATE_FAILED: '更新结账会话失败',
    UPDATED_SESSION_NOT_FOUND: '更新的会话未找到',
    CHECKOUT_SESSION_UPDATE_ERROR: '结账会话更新错误',
    ORDER_API_NOT_FOUND: '订单 API 数据源未找到',
    DRAFT_ORDER_RETRIEVAL_FAILED: '获取订单失败',
    DATA_SOURCES_NOT_FOUND: '数据源未找到',
    TRANSACTION_API_NOT_FOUND: '交易 API 数据源未找到',
    TRANSACTION_PROCESSING_FAILED: '处理交易失败',
    TRANSACTION_CREATION_FAILED: '查找或创建交易失败',
    ORDER_OPENING_FAILED: '打开订单失败',
    INVALID_FULFILLMENT_LOCATION: '履行地点无效',
    NO_VALID_PICKUP_LOCATION: '没有有效的取货地点',
    DRAFT_ORDER_FETCH_FAILED: '获取订单失败',
    LINE_ITEMS_FETCH_FAILED: '获取订单项目失败',
    CURRENT_ORDER_FETCH_FAILED: '获取当前订单失败',
    DRAFT_ORDER_UPDATE_FAILED: '更新订单失败',
    DISCOUNT_APPLICATION_FAILED: '应用优惠券失败',
    CONTEXT_UNAVAILABLE: '会话或数据源不可用',
    SHIPPING_LINES_UPDATE_FAILED: '更新配送线路失败',
    ORDER_TOTALS_UPDATE_FAILED: '更新订单总计失败',
    ORDER_TOTAL_CALCULATION_FAILED: '计算订单总计失败',
    SHIPPING_METHOD_APPLICATION_FAILED: '应用配送方式失败',
    SKU_FETCH_FAILED: '获取 SKU 失败',
    SHIPPING_RATES_CALCULATION_FAILED: '计算配送费率失败',
    SHIPPING_METHOD_NOT_FOUND: '配送方式未找到',
    SHIPPING_METHOD_REMOVAL_FAILED: '移除配送方式失败',
    SHIPPING_ADDRESS_REQUIRED: '需要配送地址',
    INVENTORY_VALIDATION_ERROR: '库存验证错误',
    INSUFFICIENT_INVENTORY: '库存不足',
    INVALID_ORDER_STATUS: '订单状态无效',
    TRANSACTION_CREATION_ERROR: '交易创建错误',
    TRANSACTION_PROCESSING_ERROR: '交易处理错误',
    UNKNOWN_ERROR: '未知错误',
    FULFILLMENT_CREATION_ERROR: '履行创建错误',
    TAX_CALCULATION_ERROR: '税费计算错误',
    ADDRESS_VERIFICATION_ERROR: '地址验证错误',
    ADDRESS_MATCHES_ERROR: '地址匹配错误',
    SHIPPING_CONFLICT_ERROR: '配送冲突错误',
    SHIPPING_ERROR: '配送错误',
    PRICE_ADJUSTMENT_CALCULATION_ERROR: '价格调整计算错误',
    ORDER_FETCH_ERROR: '订单获取错误',
    DRAFT_ORDER_UPDATE_ERROR: '订单更新错误',
    DISCOUNT_APPLICATION_ERROR: '优惠券应用错误',
    DRAFT_ORDER_OPEN_ERROR: '订单打开错误',
    ORDER_UPDATE_ERROR: '订单更新错误',
    CATALOG_FETCH_ERROR: '目录获取错误',
    STORE_ID_NOT_FOUND: '未找到商店ID',
    ORDER_NOT_DRAFT: '订单不处于有效状态',
    NO_LINE_ITEMS: '未找到商品',
    BAD_USER_INPUT: '用户输入无效',
    MISSING_SHIPPING_ADDRESS: '需要配送地址',
    MISSING_REQUIRED_FIELD: '缺少必填字段',
    CATALOG_API_ERROR: '目录服务错误',
    TAX_SERVICE_UNAVAILABLE: '税务服务不可用',
    SHIPPING_SERVICE_UNAVAILABLE: '配送服务不可用',
    PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE: '价格调整服务不可用',
    PRICE_ADJUSTMENTS_CALCULATION_FAILED: '价格调整计算失败',
    SERVICE_UNAVAILABLE: '服务暂时不可用',
    RATE_LIMITED: '请求过多，请稍后再试',
    TIMEOUT: '请求超时',
    INTERNAL_ERROR: '内部服务器错误',
    SHIPPING_POSTAL_CODE_REQUIRED: '配送邮政编码是必需的',
    SHIPPING_COUNTRY_CODE_REQUIRED: '配送国家代码是必需的',
    SHIPPING_METHOD_REQUIRED: '配送方式是必需的',
    SHIPPING_ADDRESS_VERIFICATION_FAILED: '配送地址验证失败',
    BILLING_ADDRESS_VERIFICATION_FAILED: '账单地址验证失败',
    MISSING_SHIPPING_INFO: '配送地址或方式应用失败',
    DEPENDENCY_ERROR: '我们目前无法处理您的订单。请稍等片刻再试',
  },
  storefront: {
    product: '产品',
    sale: '促销',
    noImage: '无图片',
    noImageAvailable: '无可用图片',
    selectOptions: '选择选项',
    adding: '正在添加...',
    addToCart: '添加到购物车',
    shoppingCart: '购物车',
    failedToLoadCart: '加载购物车失败:',
    retry: '重试',
    yourCartIsEmpty: '您的购物车是空的',
    addItemsToGetStarted: '添加商品以开始',
    errorLoadingProducts: '加载产品时出错:',
    errorLoadingProduct: '加载产品时出错:',
    productNotFound: '未找到产品',
    loadingVariantDetails: '正在加载变体详情...',
    combinationNotAvailable: '此组合不可用。请选择不同的选项。',
    variantsMatch: '个变体与您的选择匹配。选择更多属性以缩小范围。',
    quantity: '数量',
    addingToCart: '正在添加到购物车...',
    outOfStock: '缺货',
    viewDetails: '查看详情',
    productType: '产品类型:',
    productId: '产品ID:',
    selectedSku: '已选SKU:',
    stockStatus: '库存状态:',
    lowStock: '库存不足',
    inStock: '有货',
    remove: '删除',
    removing: '正在删除...',
    checkout: '结账',
    itemsPerPage: '每页项目数：',
    search: '搜索',
    searchPlaceholder: '搜索产品...',
  },
};
