export const zhSg = {
	general: {
		optional: "可选",
		notes: "备注",
		quantity: "数量",
		free: "免费",
		closed: "已关闭",
		apply: "应用",
		checkoutDisabled: "结账目前不可用。给您带来不便，深表歉意。",
	},
	contact: {
		title: "联系信息",
		description: "",
		email: "电子邮箱",
	},
	pickup: {
		title: "门店自取",
		description: "我们将尽力满足您的预期取货时间。实际取货时间可能有所不同。",
		location: "取货地点",
		date: "取货日期",
		time: "首选取货时间",
		selectStore: "选择门店地点",
		selectDate: "选择日期",
		selectTime: "选择取货时间",
		storeHours: "营业时间",
		seeDetails: "查看详情",
		noTimeSlots: "所选日期没有可用的时间段。请选择其他日期。",
		hoursDisplayed: "显示的时间为您当地时区。",
		storeOperatesIn: "门店以 {timezone} 时区运营。",
		asap: "尽快",
		hour: "小时",
		hours: "小时",
		minutes: "分钟",
		searchCountry: "搜索国家...",
		noCountryFound: "未找到国家。",
	},
	days: {
		sunday: "星期日",
		monday: "星期一",
		tuesday: "星期二",
		wednesday: "星期三",
		thursday: "星期四",
		friday: "星期五",
		saturday: "星期六",
	},
	delivery: {
		title: "配送",
		method: "配送方式",
		shipping: "运送",
		shipToAddress: "运送到您的地址",
		localPickup: "门店自取",
		pickupFromStore: "从门店地点取货",
	},
	tips: {
		title: "添加小费",
		noTip: "无小费",
		customAmount: "自定义金额",
		customTipAmount: "自定义小费金额",
		placeholder: "S$0.00",
	},
	shipping: {
		title: "运送",
		description: "运送地址",
		method: "运送方式",
		noShippingMethodAddress: "输入您的地址以查看可用的运送方式。",
		noShippingMethods: "未找到运送方式。",
		phone: "电话号码",
		country: "国家",
		selectCountry: "选择国家",
		searchCountry: "搜索国家...",
		noCountryFound: "未找到国家",
		firstName: "姓名",
		lastName: "姓氏",
		address1: "地址",
		address2: "公寓、套房等（可选）",
		city: "城市",
		region: "州/省",
		postalCode: "邮政编码",
		notesPlaceholder: "备注或特殊说明",
		addressSuggestion: "您是否意思是",
		addressSuggestionEnd: "？",
		noShippingOriginAddress: "未提供运送起始地址。",
	},
	billing: {
		title: "账单",
		description: "账单描述",
	},
	payment: {
		title: "付款",
		description: "所有付款都是安全且加密的。",
		billingAddress: {
			title: "账单地址",
			description: "输入您的账单地址。",
			useShippingAddress: "使用运送地址作为账单地址",
		},
		methods: {
			creditCard: "信用卡或借记卡",
			paypal: "PayPal",
			applePay: "Apple Pay",
			googlePay: "Google Pay",
			paze: "Paze",
			offline: "线下付款",
		},
		descriptions: {
			creditCard: "",
			paypal: "",
			applePay: "",
			googlePay: "",
			paze: "",
			offline: "",
		},
		noMethodsAvailable: "无可用付款方式",
		cardNumber: "卡号",
		cardNumberPlaceholder: "1234 1234 1234 1234",
		expirationDate: "有效期（MM / YY）",
		securityCode: "安全码",
		cvvPlaceholder: "CVV",
		nameOnCard: "持卡人姓名",
		payNow: "立即付款",
		standardShipping: "标准运送",
		cardDetails: "卡片详情",
		payWithApplePay: "使用 Apple Pay 付款",
		expirationDatePlaceholder: "MM / YY",
		failedToInitializePayment: "付款初始化失败。",
		orderTotal: "订单总额",
		subtotal: "小计",
		tax: "税费",
		shipping: "运费",
		discount: "优惠券",
		processingPayment: "正在处理付款...",
		completingOrder: "正在完成订单...",
		freePayment: "完成您的免费订单",
	},
	phone: {
		placeholder: "+65 9123 4567",
		searchCountry: "搜索国家...",
		noCountryFound: "未找到国家。",
	},
	discounts: {
		placeholder: "优惠券代码",
		enterCode: "输入优惠券代码",
		apply: "应用",
		alreadyApplied: "此优惠券代码已经应用",
		failedToApply: "优惠券代码应用失败",
		enterCodeValidation: "请输入优惠券代码",
	},
	totals: {
		subtotal: "小计",
		discount: "折扣",
		shipping: "运费",
		tip: "小费",
		estimatedTaxes: "预估税费",
		totalDue: "应付总额",
		orderSummary: "订单摘要",
		itemCount: "件商品",
		noItems: "无商品",
	},
	lineItems: {
		note: "备注：",
	},
	ui: {
		autocomplete: {
			addressPlaceholder: "地址",
			suggestions: "建议",
		},
		form: {
			useFormFieldError: "useFormField 应在 <FormField> 内使用",
		},
		pagination: {
			ariaLabel: "分页",
			previousPageAriaLabel: "转到上一页",
			previous: "上一页",
			nextPageAriaLabel: "转到下一页",
			next: "下一页",
			morePages: "更多页面",
		},
		sidebar: {
			useSidebarError: "useSidebar 必须在 SidebarProvider 内使用。",
			toggleSidebar: "切换侧边栏",
		},
		accessibility: {
			payWithApplePay: "使用 Apple Pay 付款",
			applePayLogo: "Apple Pay 标志",
		},
	},
	errors: {
		failedToGetAccessToken: "获取访问令牌失败",
		invalidEnvironment: "无效环境",
		noPublicAccessToken: "未提供公共访问令牌",
		noSessionToken: "未提供会话令牌或ID",
		errorCreatingSession: "创建结账会话错误：",
		orderIdRequired: "需要订单ID",
		errorTrackingEvent: "跟踪事件错误",
		errorInTrackingSubscriber: "跟踪订阅者错误",
		useTrackingProviderError: "useTracking 必须在 TrackingProvider 内使用",
		usePoyntCollectProviderError:
			"usePoyntCollect 必须在 PoyntCollectProvider 内使用",
		useSquareProviderError: "useSquare 必须在 SquareProvider 内使用",
		errorProcessingPayment: "处理付款错误",
		stripeConfigMissing: "Stripe 配置缺失。请检查您的设置。",
		paymentSuccessful: "付款成功",
		paymentFailed: "付款失败",
		paypalConfigMissing: "PayPal 配置缺失。请检查您的设置。",
		stripeNotReady: "Stripe 未就绪",
		cardElementNotFound: "未找到 CardElement",
		errorProcessingCardPayment: "处理卡片付款错误。",
		errorProcessingExpressPayment: "处理快速付款错误。",
		failedToInitializePayment: "付款初始化失败。",
		invalidPhoneNumber: "无效电话号码",
	},
	validation: {
		phoneRequired: "电话号码必填",
		emailRequired: "输入电子邮箱",
		emailInvalid: "输入有效的电子邮箱",
		phoneTooLong: "电话号码过长",
		invalidShippingAddress: "无效运送地址",
		invalidBillingAddress: "无效账单地址",
		selectPaymentMethod: "选择付款方式",
		enterValidBillingPhone: "输入有效的账单电话号码",
		enterValidShippingPhone: "输入有效的运送电话号码",
		enterFirstName: "输入姓名",
		enterLastName: "输入姓氏",
		enterAddress: "输入地址",
		enterCity: "输入城市",
		enterZipCode: "输入邮政编码",
		enterZipPostalCode: "输入邮政编码",
		selectState: "选择州/省",
		selectCountry: "选择国家",
		enterCountry: "输入国家",
	},
	apiErrors: {
		INTERNAL_SERVER_ERROR: "服务器错误",
		SESSION_NOT_FOUND: "会话未找到",
		CHECKOUT_SESSION_RETRIEVAL_FAILED: "检索结账会话失败",
		CHECKOUT_SESSION_NOT_FOUND: "结账会话未找到",
		CHECKOUT_SESSION_FETCH_ERROR: "结账会话获取错误",
		DRAFT_ORDER_NOT_FOUND: "草稿订单未找到",
		CHECKOUT_SESSION_CREATION_FAILED: "创建结账会话失败",
		CREATED_SESSION_DATA_NOT_FOUND: "创建的会话数据未找到",
		CHECKOUT_SESSION_CREATION_ERROR: "结账会话创建错误",
		CHECKOUT_SESSION_UPDATE_FAILED: "更新结账会话失败",
		UPDATED_SESSION_NOT_FOUND: "更新的会话未找到",
		CHECKOUT_SESSION_UPDATE_ERROR: "结账会话更新错误",
		ORDER_API_NOT_FOUND: "订单API数据源未找到",
		DRAFT_ORDER_RETRIEVAL_FAILED: "检索草稿订单失败",
		DATA_SOURCES_NOT_FOUND: "数据源未找到",
		TRANSACTION_API_NOT_FOUND: "交易API数据源未找到",
		TRANSACTION_PROCESSING_FAILED: "处理交易失败",
		TRANSACTION_CREATION_FAILED: "查找或创建交易失败",
		ORDER_OPENING_FAILED: "打开订单失败",
		INVALID_FULFILLMENT_LOCATION: "无效的履行地点",
		NO_VALID_PICKUP_LOCATION: "无有效的取货地点",
		DRAFT_ORDER_FETCH_FAILED: "获取草稿订单失败",
		LINE_ITEMS_FETCH_FAILED: "获取行项目失败",
		CURRENT_ORDER_FETCH_FAILED: "获取当前草稿订单失败",
		DRAFT_ORDER_UPDATE_FAILED: "更新草稿订单失败",
		DISCOUNT_APPLICATION_FAILED: "应用优惠券失败",
		CONTEXT_UNAVAILABLE: "会话或数据源不可用",
		SHIPPING_LINES_UPDATE_FAILED: "更新运送行失败",
		ORDER_TOTALS_UPDATE_FAILED: "更新订单总额失败",
		SHIPPING_METHOD_APPLICATION_FAILED: "应用运送方式失败",
		SKU_FETCH_FAILED: "获取SKU失败",
		SHIPPING_RATES_CALCULATION_FAILED: "计算运送费率失败",
		SHIPPING_METHOD_NOT_FOUND: "运送方式未找到",
		SHIPPING_METHOD_REMOVAL_FAILED: "移除运送方式失败",
		SHIPPING_ADDRESS_REQUIRED: "需要运送地址",
		INVENTORY_VALIDATION_ERROR: "库存验证错误",
		INSUFFICIENT_INVENTORY: "库存不足",
		INVALID_ORDER_STATUS: "无效订单状态",
		TRANSACTION_CREATION_ERROR: "交易创建错误",
		TRANSACTION_PROCESSING_ERROR: "交易处理错误",
		UNKNOWN_ERROR: "未知错误",
		FULFILLMENT_CREATION_ERROR: "履行创建错误",
		TAX_CALCULATION_ERROR: "税费计算错误",
		ADDRESS_VERIFICATION_ERROR: "地址验证错误",
		ADDRESS_MATCHES_ERROR: "地址匹配错误",
		SHIPPING_CONFLICT_ERROR: "运送冲突错误",
		SHIPPING_ERROR: "运送错误",
		PRICE_ADJUSTMENT_CALCULATION_ERROR: "价格调整计算错误",
		ORDER_FETCH_ERROR: "订单获取错误",
		DRAFT_ORDER_UPDATE_ERROR: "草稿订单更新错误",
		DISCOUNT_APPLICATION_ERROR: "优惠券应用错误",
		DRAFT_ORDER_OPEN_ERROR: "草稿订单打开错误",
		ORDER_UPDATE_ERROR: "订单更新错误",
		CATALOG_FETCH_ERROR: "目录获取错误",
		STORE_ID_NOT_FOUND: "未找到商店ID",
		ORDER_NOT_DRAFT: "订单不处于草稿状态",
		NO_LINE_ITEMS: "未找到商品",
		BAD_USER_INPUT: "用户输入无效",
		MISSING_SHIPPING_ADDRESS: "需要运送地址",
		MISSING_REQUIRED_FIELD: "缺少必填字段",
		CATALOG_API_ERROR: "目录服务错误",
		TAX_SERVICE_UNAVAILABLE: "税务服务不可用",
		SHIPPING_SERVICE_UNAVAILABLE: "运送服务不可用",
		PRICE_ADJUSTMENTS_SERVICE_UNAVAILABLE: "价格调整服务不可用",
		PRICE_ADJUSTMENTS_CALCULATION_FAILED: "价格调整计算失败",
		SERVICE_UNAVAILABLE: "服务暂时不可用",
		RATE_LIMITED: "请求过多，请稍后再试",
		TIMEOUT: "请求超时",
		INTERNAL_ERROR: "内部服务器错误",
		SHIPPING_POSTAL_CODE_REQUIRED: "配送邮政编码是必需的",
		SHIPPING_COUNTRY_CODE_REQUIRED: "配送国家代码是必需的",
		SHIPPING_METHOD_REQUIRED: "配送方式是必需的",
		SHIPPING_ADDRESS_VERIFICATION_FAILED: "配送地址验证失败",
		BILLING_ADDRESS_VERIFICATION_FAILED: "账单地址验证失败",
	},
};
