name: CICD
on: 
  push:
    branches:
      - 'main'
  pull_request:
    branches:
     - '*'

jobs:
  cicd:
    runs-on: ubuntu-latest
    concurrency: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6 # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v6 # v5.0.0
      - name: Setup Node.js
        uses: actions/setup-node@v6 # v6.3.0
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Test
        run: pnpm test
