name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  id-token: write  # Required for OIDC
  contents: write # Required to push tags and releases

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6 # v6.0.2

      - name: Setup pnpm
        uses: pnpm/action-setup@v5 # v5.0.0

      - name: Setup Node
        uses: actions/setup-node@v6 # v6.3.0
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --prefer-offline

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1 # v1.7.0
        with:
          version: pnpm run version
          publish: pnpm publish -r
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
