name: Close Stale PRs

on:
  workflow_dispatch:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - name: Close Stale Issues
      uses: actions/stale@v8.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-message: |
          'This PR is stale as it has been open for 30 days with no activity. Remove stale label or comment or this will be closed in 5 days.'
        close-pr-message: |
          'This PR was closed because it has been stalled for 5 days with no activity.'
        days-before-pr-stale: 30
        days-before-pr-close: 5
